<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Maintain\\Admin\\DriverDataGrid',
        'type'       => 'data-grid',
        'name'       => 'core.maintain.driver',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Maintain\\Admin\\EventDataGrid',
        'type'       => 'data-grid',
        'name'       => 'core.maintain.event',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Maintain\\Admin\\RouteDataGrid',
        'type'       => 'data-grid',
        'name'       => 'core.maintain.route',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\StatsContentType\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'core.statistic.type',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\AdminSearch',
        'type'       => 'entity',
        'name'       => 'admin_search',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\Attachment',
        'type'       => 'entity',
        'name'       => 'core_attachment',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\AttachmentFileType',
        'type'       => 'entity',
        'name'       => 'core_attachment_file_type',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\Driver',
        'type'       => 'entity',
        'name'       => 'core-driver',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\Privacy',
        'type'       => 'entity',
        'name'       => 'core_privacy',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\PrivacyMember',
        'type'       => 'entity',
        'name'       => 'core_privacy_member',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\PrivacyStream',
        'type'       => 'entity',
        'name'       => 'core_privacy_stream',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\Link',
        'type'       => 'entity',
        'name'       => 'link',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\StatsContent',
        'type'       => 'entity',
        'name'       => 'stat_content',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Models\\Link',
        'type'       => 'entity-content',
        'name'       => 'link',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Links',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\DestroyCacheForm',
        'type'       => 'form',
        'name'       => 'core.admin.destroy_cache',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\CreateFeedForm',
        'type'       => 'form',
        'name'       => 'link.feed_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Form\\SelectPackageField',
        'type'       => 'form-field',
        'name'       => 'selectPackage',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form Field',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Form\\SelectPackageAliasField',
        'type'       => 'form-field',
        'name'       => 'selectPackageAlias',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form Field',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Form\\YesNoChoice',
        'type'       => 'form-field',
        'name'       => 'yesNoChoice',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form Field',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'core',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/core/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\LicenseKeySettingForm',
        'type'       => 'form-settings',
        'name'       => 'core.license_key',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.license_settings',
        'url'        => '/core/setting/license_key',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\SecuritySettingForm',
        'type'       => 'form-settings',
        'name'       => 'core.security',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.security',
        'url'        => '/core/setting/security',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\ProviderSettingForm',
        'type'       => 'form-settings',
        'name'       => 'core.provider',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.service_keys',
        'url'        => '/core/setting/provider',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\SiteModeSettingForm',
        'type'       => 'form-settings',
        'name'       => 'core.site_mode',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/core/setting/site-mode',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Admin\\SpamSettingForm',
        'type'       => 'form-settings',
        'name'       => 'core.spam',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.spam_assistance',
        'url'        => '/core/setting/spam',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Jobs\\DeleteImageJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Core\\Jobs\\DeleteImageJob',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Jobs\\UpdateAdminSearch',
        'type'       => 'job',
        'name'       => 'MetaFox\\Core\\Jobs\\UpdateAdminSearch',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Attachment\\AttachmentItemCollection',
        'type'       => 'json-collection',
        'name'       => 'core_attachment.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\LinkEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'link.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\LinkItemCollection',
        'type'       => 'json-collection',
        'name'       => 'link.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\SiteSetting\\Admin\\SiteSettingItemCollection',
        'type'       => 'json-collection',
        'name'       => 'site_setting.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Error\\Forbidden',
        'type'       => 'json-resource',
        'name'       => 'forbidden.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\LinkDetail',
        'type'       => 'json-resource',
        'name'       => 'link.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\LinkEmbed',
        'type'       => 'json-resource',
        'name'       => 'link.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\FeedEmbed',
        'type'       => 'json-resource',
        'name'       => 'link.feed_embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\LinkItem',
        'type'       => 'json-resource',
        'name'       => 'link.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\SiteSetting\\Admin\\SiteSettingItem',
        'type'       => 'json-resource',
        'name'       => 'site_setting.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'core',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\LinkPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Core\\Models\\Link',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanApprove',
        'type'       => 'policy-rule',
        'name'       => 'approve',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanFeature',
        'type'       => 'policy-rule',
        'name'       => 'feature',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanPublish',
        'type'       => 'policy-rule',
        'name'       => 'publish',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanPurchaseSponsor',
        'type'       => 'policy-rule',
        'name'       => 'purchaseSponsor',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanPurchaseSponsorInFeed',
        'type'       => 'policy-rule',
        'name'       => 'purchaseSponsorInFeed',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanShowSponsorLabel',
        'type'       => 'policy-rule',
        'name'       => 'showSponsorLabel',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanSponsor',
        'type'       => 'policy-rule',
        'name'       => 'sponsor',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanSponsorInFeed',
        'type'       => 'policy-rule',
        'name'       => 'sponsorInFeed',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanUnsponsor',
        'type'       => 'policy-rule',
        'name'       => 'unsponsor',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanUnsponsorInFeed',
        'type'       => 'policy-rule',
        'name'       => 'unsponsorInFeed',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanUpdatePrivacy',
        'type'       => 'policy-rule',
        'name'       => 'updatePrivacy',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanViewApprove',
        'type'       => 'policy-rule',
        'name'       => 'viewApprove',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Policies\\Handlers\\CanViewApproveListing',
        'type'       => 'policy-rule',
        'name'       => 'viewApproveListing',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Privacy\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'privacy',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Link\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'link',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Core\\Http\\Resources\\v1\\Privacy\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'privacy',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
];
