<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_change_to_moderator'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'change_to_moderator',
        'label'    => 'group::phrase.change_to_moderator',
        'ordering' => 2,
        'value'    => 'changeToModerator',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_remove_as_admin'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'remove_as_admin',
        'label'    => 'group::phrase.remove_as_admin',
        'ordering' => 3,
        'value'    => 'removeAsAdmin',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_reassign_owner'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'reassign_owner',
        'label'    => 'group::phrase.reassign_owner',
        'ordering' => 5,
        'value'    => 'reassignOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 2],
            ['truthy', 'item.extra.can_add_as_admin'],
            ['falsy', 'item.extra.can_cancel_admin_invite'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'add_as_admin',
        'label'    => 'group::phrase.add_as_admin',
        'ordering' => 6,
        'value'    => 'addAsAdmin',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 2],
            ['truthy', 'item.extra.can_add_as_admin'],
            ['truthy', 'item.extra.can_cancel_admin_invite'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'cancel_admin_invite_from_moderator',
        'label'    => 'group::phrase.remove_admin_invite',
        'ordering' => 6,
        'value'    => 'cancelAdminInvite',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 2],
            ['truthy', 'item.extra.can_remove_as_moderator'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'remove_as_moderator',
        'label'    => 'group::phrase.remove_as_moderator',
        'ordering' => 7,
        'value'    => 'removeAsModerator',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_admin'],
            ['falsy', 'item.extra.can_cancel_admin_invite'],
            ['falsy', 'item.extra.can_cancel_moderator_invite'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'set_as_admin',
        'label'    => 'group::phrase.set_as_admin',
        'ordering' => 9,
        'value'    => 'setAsAdmin',
    ],
    [
        'showWhen' => [
            'and',
            ['gte', 'item.answers.length', 1],
        ],
        'menu'     => 'group.group_request.itemActionMenu',
        'name'     => 'view_answer',
        'label'    => 'group::phrase.view_answers',
        'ordering' => 1,
        'value'    => 'group/viewAnswers',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'group.group_request.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'group::phrase.approve',
        'ordering' => 2,
        'value'    => 'group/approvePendingRequest',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'group.group_request.itemActionMenu',
        'name'     => 'decline',
        'label'    => 'group::phrase.decline',
        'ordering' => 3,
        'value'    => 'group/declinePendingRequest',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_view_reason'],
        ],
        'menu'     => 'group.group_request.itemActionMenu',
        'name'     => 'view_reason',
        'label'    => 'group::phrase.view_reason',
        'ordering' => 4,
        'value'    => 'group/viewReason',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_admin'],
            ['truthy', 'item.extra.can_cancel_admin_invite'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'cancel_admin_invite',
        'label'    => 'group::phrase.remove_admin_invite',
        'ordering' => 10,
        'value'    => 'cancelAdminInvite',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_moderator'],
            ['falsy', 'item.extra.can_cancel_moderator_invite'],
            ['falsy', 'item.extra.can_cancel_admin_invite'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'set_as_moderator',
        'label'    => 'group::phrase.set_as_moderator',
        'ordering' => 11,
        'value'    => 'setAsModerator',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_moderator'],
            ['truthy', 'item.extra.can_cancel_moderator_invite'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'cancel_moderator_invite',
        'label'    => 'group::phrase.cancel_moderator_invite',
        'ordering' => 12,
        'value'    => 'cancelModeratorInvite',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_block'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'block_from_group',
        'label'    => 'group::phrase.block_from_group',
        'ordering' => 13,
        'value'    => 'blockFromGroup',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mute_in_group'],
            ['falsy', 'item.is_muted'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'mute_in_group',
        'label'    => 'group::phrase.mute_in_group',
        'ordering' => 14,
        'value'    => 'muteInGroupForm',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unmute_in_group'],
            ['truthy', 'item.is_muted'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'unmute_in_group',
        'label'    => 'group::phrase.unmute_in_group',
        'ordering' => 15,
        'value'    => 'unmuteInGroup',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_leave'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'style'    => 'danger',
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'leave_group',
        'label'    => 'group::phrase.leave_group',
        'ordering' => 16,
        'value'    => 'unjoin',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_remove_member'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'style'    => 'danger',
        'menu'     => 'group.group_member.itemActionMenu',
        'name'     => 'remove_member',
        'label'    => 'group::phrase.remove_member',
        'ordering' => 17,
        'value'    => 'removeMember',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 0],
            ['truthy', 'item.extra.can_add_friend'],
        ],
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'add_friend',
        'label'    => 'group::phrase.add_friend',
        'ordering' => 2,
        'value'    => 'addFriend',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 3],
        ],
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 3,
        'value'    => 'cancelRequest',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_friend'],
            ['eq', 'item.friendship', 2],
        ],
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'confirm_request',
        'label'    => 'group::phrase.confirm',
        'ordering' => 4,
        'value'    => 'acceptFriendRequest',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_friend'],
            ['eq', 'item.friendship', 2],
        ],
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'delete_request',
        'label'    => 'group::phrase.delete',
        'ordering' => 5,
        'value'    => 'denyFriendRequest',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'edit_profile',
        'label'    => 'group::phrase.edit_profile',
        'ordering' => 6,
        'value'    => 'editProfile',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['neq', 'item.friendship', 5],
        ],
        'params'   => [
            'module_name'   => 'chatplus',
            'resource_name' => 'room',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'message',
        'label'    => 'group::phrase.message',
        'ordering' => 7,
        'value'    => 'openChatRoom',
    ],
    [
        'color'     => 'primary',
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_poke'],
            ['neq', 'item.friendship', 5],
        ],
        'params'    => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'      => 'group.group_member.profileActionMenu',
        'name'      => 'poke',
        'label'     => 'group::phrase.poke',
        'ordering'  => 8,
        'value'     => 'pokeItem',
        'is_active' => 0,
        'is_delete' => 1,
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_featured'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'feature',
        'label'    => 'group::phrase.featured_this_user',
        'ordering' => 9,
        'value'    => 'featureItem',
    ],
    [
        'style'    => 'danger',
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 1],
        ],
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'un_friend',
        'label'    => 'group::phrase.un_friend',
        'ordering' => 10,
        'value'    => 'user/unFriend',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature'],
            ['truthy', 'item.is_featured'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'unfeature',
        'label'    => 'group::phrase.un_featured_this_user',
        'ordering' => 10,
        'value'    => 'unfeatureItem',
    ],
    [
        'style'    => 'danger',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'block',
        'label'    => 'group::phrase.block_this_user',
        'ordering' => 11,
        'value'    => 'blockItem',
    ],
    [
        'style'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'unblock',
        'label'    => 'group::phrase.un_block_this_user',
        'ordering' => 12,
        'value'    => 'unblockItem',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['neq', 'item.friendship', 5],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group_member.profileActionMenu',
        'name'     => 'gift_points',
        'label'    => 'group::phrase.gift_points',
        'ordering' => 14,
        'value'    => 'comingSoon',
    ],
    [
        'tab'            => 'home',
        'showWhen'       => [
            'and',
            ['truthy', 'item.extra.can_view_tab_discussion'],
        ],
        'menu'           => 'group.group.profileMenu',
        'name'           => 'home',
        'label'          => 'group::phrase.discussions',
        'ordering'       => 1,
        'to'             => '/',
        'params'         => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'value'          => 'overview',
        'useScrollToTop' => true,
    ],
    [
        'tab'      => 'about',
        'menu'     => 'group.group.profileMenu',
        'name'     => 'about',
        'label'    => 'group::phrase.about',
        'ordering' => 2,
        'to'       => '/about',
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'value'    => 'groupInfo',
    ],
    [
        'menu'     => 'group.group_rule.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'group::phrase.edit_rule',
        'ordering' => 1,
        'value'    => 'updateGroupRule',
    ],
    [
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group_rule',
        ],
        'style'    => 'danger',
        'menu'     => 'group.group_rule.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'group::phrase.delete_rule',
        'ordering' => 2,
        'value'    => 'deleteItem',
    ],
    [
        'menu'     => 'group.group.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'group.group.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'group.group.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'group.group.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_generate_invite_link'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionInviteMenu',
        'name'     => 'generate',
        'label'    => 'group::phrase.generate_invite_link',
        'ordering' => 1,
        'value'    => 'group/generateLinkInvite',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionInviteMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 2,
        'value'    => 'group_invite/inviteFriends',
    ],
    [
        'showWhen' => ['eq', 'item.membership', 2],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 3,
        'value'    => 'cancelRequest',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'group::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
    ],
    [
        'variant'  => 'contained',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_accept_or_decline_invite'],
            ['falsy', 'item.is_member'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'accept',
        'label'    => 'group::phrase.accept',
        'ordering' => 4,
        'value'    => 'acceptInvite',
    ],
    [
        'variant'  => 'outlined-square',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_accept_or_decline_invite'],
            ['falsy', 'item.is_member'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'decline',
        'label'    => 'group::phrase.decline_invite',
        'ordering' => 5,
        'value'    => 'declineInvite',
    ],
    [
        'showWhen' => [
            'or',
            ['truthy', 'item.extra.can_edit'],
            ['truthy', 'item.extra.can_manage_member_report_content'],
            ['truthy', 'item.extra.can_manage_pending_posts'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'group::phrase.manage',
        'ordering' => 7,
        'value'    => 'manage',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'group::phrase.sponsor_this_item',
        'ordering' => 11,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'group::phrase.sponsor_this_item',
        'ordering' => 11,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'group::phrase.un_sponsor_this_item',
        'ordering' => 11,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 10,
        'value'    => 'group/inviteFriends',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 12,
        'value'    => 'featureItem',
        'icon'     => 'ico-feature',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'group::phrase.un_feature',
        'ordering' => 13,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'style'    => 'danger',
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'group::phrase.delete',
        'ordering' => 16,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'item.extra.can_add_cover'],
        ],
        'menu'       => 'group.group.profileActionMenu',
        'name'       => 'update_cover',
        'label'      => 'group::phrase.update_cover',
        'ordering'   => 1,
        'value'      => '@app/EDIT_ITEM_COVER',
        'icon'       => '',
        'is_deleted' => 1,
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'item.extra.can_edit_cover'],
            ['truthy', 'item.cover_photo_id'],
        ],
        'params'     => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'       => 'group.group.profileActionMenu',
        'name'       => 'remove_cover',
        'label'      => 'group::phrase.remove_cover',
        'ordering'   => 2,
        'value'      => 'remove_cover',
        'icon'       => '',
        'is_deleted' => 0,
    ],
    [
        'variant'  => 'contained',
        'disabled' => false,
        'showWhen' => [
            'and',
            ['eq', 'item.membership', 0],
            ['falsy', 'item.is_pending'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'join',
        'label'    => 'group::phrase.join_group',
        'ordering' => 3,
        'value'    => 'join',
    ],
    [
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'copy_link',
        'label'    => 'group::phrase.copy_link',
        'ordering' => 5,
        'value'    => 'copyLink',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group_invite',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 5,
        'value'    => 'group/inviteFriends',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_generate_invite_link'],
            ['eq', 'item.reg_method', 2],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'generate',
        'label'    => 'group::phrase.generate_invite_link',
        'ordering' => 5,
        'value'    => 'group/generateInviteLink',
    ],
    [
        'showWhen' => ['eq', 'item.membership', 2],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 6,
        'value'    => 'cancelRequest',
    ],
    [
        'showWhen' => [
            'or',
            ['truthy', 'item.extra.can_edit'],
            ['truthy', 'item.extra.can_manage_member_report_content'],
            ['truthy', 'item.extra.can_manage_pending_posts'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'manage',
        'label'    => 'group::phrase.manage',
        'ordering' => 7,
        'value'    => 'manage',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_pending_request_tab'],
            [
                'or',
                ['truthy', 'item.extra.can_manage_setting'],
                ['truthy', 'item.is_moderator'],
            ],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'manage_pending_requests',
        'label'    => 'group::phrase.pending_request',
        'ordering' => 8,
        'value'    => 'pendingRequests',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 10,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'unfeature',
        'label'    => 'group::phrase.un_feature',
        'ordering' => 11,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'sponsor',
        'label'    => 'group::phrase.sponsor_this_item',
        'ordering' => 13,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'group::phrase.sponsor_this_item',
        'ordering' => 13,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'group::phrase.un_sponsor_this_item',
        'ordering' => 13,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_owner'],
            ['falsy', 'item.is_pending'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'reassign_owner',
        'label'    => 'group::phrase.reassign_owner',
        'ordering' => 14,
        'value'    => 'reassignOwnerDialog',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_leave'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'leave_group',
        'label'    => 'group::phrase.leave_group',
        'ordering' => 15,
        'value'    => 'unjoin',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'params'    => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'style'     => 'danger',
        'menu'      => 'group.group.profileActionMenu',
        'name'      => 'delete',
        'label'     => 'group::phrase.delete',
        'ordering'  => 16,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_leave'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'edit',
        'label'    => 'group::phrase.leave_group',
        'ordering' => 2,
        'value'    => 'unjoin',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profilePopoverMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 3,
        'value'    => 'group_invite/inviteFriends',
    ],
    [
        'menu'     => 'group.group.sort_menu',
        'name'     => 'latest',
        'label'    => 'core::phrase.sort.latest',
        'ordering' => 1,
        'value'    => 'latest',
    ],
    [
        'menu'     => 'group.group.sort_menu',
        'name'     => 'most_member',
        'label'    => 'core::phrase.sort.most_joined',
        'ordering' => 2,
        'value'    => 'most_member',
    ],
    [
        'tab'      => 'all',
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'all',
        'label'    => 'group::phrase.all_groups',
        'ordering' => 1,
        'value'    => 'viewAll',
        'to'       => '/group/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'my',
        'label'    => 'group::phrase.my_groups',
        'ordering' => 2,
        'value'    => 'viewMyGroups',
        'to'       => '/group/my',
    ],
    [
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'group::phrase.my_pending_groups',
        'ordering' => 3,
        'value'    => 'viewMyPendingGroups',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'group::phrase.friends_groups',
        'ordering' => 4,
        'value'    => 'viewFriendGroups',
        'to'       => '/group/friend',
    ],
    [
        'tab'      => 'joined',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'joined',
        'label'    => 'group::phrase.joined_groups',
        'ordering' => 5,
        'value'    => 'viewJoinedGroups',
        'to'       => '/group/joined',
    ],
    [
        'tab'      => 'invited',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'invited',
        'label'    => 'group::phrase.group_invites',
        'ordering' => 6,
        'value'    => 'viewInvitedGroups',
        'to'       => '/group/invited',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'or',
            ['truthy', 'acl.group.group.approve'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'group::phrase.pending_groups',
        'ordering' => 7,
        'value'    => 'viewPendingGroups',
        'to'       => '/group/pending',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.group.group.view'],
            ['falsy', 'is_hashtag'],
        ],
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'group',
        'label'         => 'group::phrase.group_global_search_label',
        'ordering'      => 6,
        'value'         => 'searchGlobalGroup',
        'module_name'   => 'group',
        'resource_name' => 'group',
    ],
    [
        'tab'      => 'group',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.group'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'group',
        'label'    => 'group::phrase.groups',
        'ordering' => 6,
        'to'       => '/group',
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'module_name'   => 'group',
        'resource_name' => 'group',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'all',
        'label'         => 'core::phrase.all',
        'ordering'      => 0,
        'value'         => 'searchGlobalInGroup',
    ],
    [
        'showWhen' => ['eq', 'item.membership', 2],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'group::phrase.cancel_request',
        'ordering' => 3,
        'value'    => 'cancelRequest',
    ],
    [
        'variant'  => 'contained',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_accept_or_decline_invite'],
            ['falsy', 'item.is_member'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'accept',
        'label'    => 'group::phrase.accept',
        'ordering' => 4,
        'value'    => 'acceptInvite',
    ],
    [
        'variant'  => 'outlined-square',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_accept_or_decline_invite'],
            ['falsy', 'item.is_member'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'decline',
        'label'    => 'group::phrase.decline_invite',
        'ordering' => 5,
        'value'    => 'declineInvite',
    ],
    [
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_member'],
                ['truthy', 'item.extra.can_edit'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'invite',
        'label'    => 'group::phrase.invite_friends',
        'ordering' => 10,
        'value'    => 'inviteFriends',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'group::phrase.sponsor_this_item',
        'ordering' => 11,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'group::phrase.sponsor_this_item',
        'ordering' => 11,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'group::phrase.un_sponsor_this_item',
        'ordering' => 11,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 12,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'unfeature',
        'label'    => 'group::phrase.un_feature',
        'ordering' => 13,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'style'    => 'danger',
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'group::phrase.delete',
        'ordering' => 16,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'group',
        'label'     => 'group::phrase.groups',
        'ordering'  => 13,
        'value'     => '',
        'to'        => '/group',
        'as'        => 'item',
        'icon'      => 'user3-three',
        'iconColor' => '#b132fb',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_on_group',
        'label'    => 'activity::phrase.share_on_group',
        'ordering' => 5,
        'value'    => 'shareOnGroupProfile',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_pending', 0],
            ['truthy', 'item.extra.can_pin_item'],
            ['falsy', 'item.extra.can_review_feed'],
            ['truthy', 'profile_id'],
            ['or', ['eqeqeq', 'params._identity', '$.item.user'], ['eqeqeq', 'params._identity', '$.item.parent_user']],
            ['eq', 'profile_type', 'group'],
            ['noneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'pinItemOnGroup',
        'label'    => 'group::phrase.pin_post_on_group',
        'ordering' => 2,
        'value'    => 'pinItem',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_pending', 0],
            ['truthy', 'item.extra.can_pin_item'],
            ['truthy', 'profile_id'],
            ['or', ['eqeqeq', 'params._identity', '$.item.user'], ['eqeqeq', 'params._identity', '$.item.parent_user']],
            ['eq', 'profile_type', 'group'],
            ['oneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'unpinItemOnGroup',
        'label'    => 'activity::phrase.unpin_post',
        'ordering' => 3, 'value' => 'unpinItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mark_announcement'],
            ['truthy', 'profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'mark_as_announcement',
        'label'    => 'group::phrase.mark_as_announcement',
        'ordering' => 22,
        'value'    => 'announcementItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_remove_announcement'],
            ['truthy', 'profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'remove_announcement',
        'label'    => 'group::phrase.remove_announcement',
        'ordering' => 22,
        'value'    => 'removeAnnouncementItem',
    ],
    [
        'showWhen' => [
            'and',
            ['gte', 'apiVersion', 'v1.11'],
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'group_setting',
        'label'    => 'group::phrase.group_settings_uppercase_label',
        'ordering' => 1,
        'as'       => 'section',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_setting'],
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'group_info',
        'label'    => 'core::web.edit_group_info',
        'ordering' => 2,
        'value'    => 'group/editInfoGroupItem',
        'icon'     => 'pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_setting'],
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'about_group',
        'label'    => 'group::web.edit_about_group',
        'ordering' => 3,
        'value'    => 'group/editAboutGroupItem',
        'icon'     => 'info-circle-alt-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_setting'],
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'privacy',
        'label'    => 'core::web.privacy',
        'ordering' => 4,
        'value'    => 'group/editPrivacyGroupItem',
        'icon'     => 'pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['gte', 'apiVersion', 'v1.11'],
            [
                'or',
                ['truthy', 'item.extra.can_edit'],
                ['truthy', 'item.extra.can_manage_member_report_content'],
                ['truthy', 'item.extra.can_manage_pending_posts'],
            ],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'manager_group',
        'label'    => 'group::phrase.manage_group_uppercase_label',
        'ordering' => 5,
        'as'       => 'section',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_membership_question'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'membership_questions',
        'label'    => 'group::phrase.membership_questions',
        'ordering' => 7,
        'icon'     => 'user2-question-o',
        'value'    => 'group/groupMembershipQuestion',
    ],
    [
        'showWhen' => [
            'and',
            ['gte', 'apiVersion', 'v1.10'],
            ['truthy', 'item.extra.can_manage_membership_request'],
            ['truthy', 'item.extra.can_manage_pending_request_tab'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'membership_requests',
        'label'    => 'group::phrase.membership_requests',
        'ordering' => 8,
        'icon'     => 'newspaper-o',
        'value'    => 'group/groupMembershipRequest',
    ],
    [
        'showWhen' => [
            'and',
            ['gte', 'apiVersion', 'v1.16'],
            ['truthy', 'item.extra.can_manage_membership_invites'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'membership_invites',
        'label'    => 'group::phrase.membership_invitations',
        'ordering' => 8,
        'icon'     => 'ico-envelope-o',
        'value'    => 'group/groupMembershipInvites',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_update_rule_confirmation'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'group_rules',
        'label'    => 'group::phrase.group_rules',
        'ordering' => 9,
        'icon'     => 'list-bullet-o',
        'value'    => 'group/groupRules',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_setting'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'moderation_rights',
        'label'    => 'group::phrase.moderation_rights',
        'ordering' => 11,
        'icon'     => 'shield-o',
        'value'    => 'group/editModerationRightGroupItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_new_admin'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'add_new_admin',
        'label'    => 'group::phrase.admins',
        'ordering' => 12,
        'icon'     => 'bell2-o',
        'value'    => 'group/addNewAdmin',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_new_moderate'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'add_new_moderate',
        'label'    => 'group::phrase.moderators',
        'ordering' => 13,
        'icon'     => 'shield-o',
        'value'    => 'group/addNewModerate',
    ],
    [
        'showWhen' => [
            'and',
            ['gte', 'apiVersion', 'v1.11'],
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'privacy_settings',
        'label'    => 'group::phrase.privacy_settings_uppercase_label',
        'ordering' => 16,
        'as'       => 'section',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_setting'],
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'permissions',
        'label'    => 'core::phrase.permissions',
        'ordering' => 17,
        'icon'     => 'shield',
        'value'    => 'group/editPermissionGroupItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['gte', 'apiVersion', 'v1.11'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'group_menu_settings',
        'label'    => 'group::phrase.group_menu_settings_uppercase_label',
        'ordering' => 20,
        'as'       => 'section',
    ],
    [
        'tab'      => 'menu',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_setting'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'menu',
        'label'    => 'core::web.menu_settings',
        'ordering' => 21,
        'icon'     => 'layers',
        'value'    => 'group/menuSetting',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'group.group.headerItemActionOnUserProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'acl.group.group.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'       => 'group.group.headerItemActionOnUserProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'group.group.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'group.group.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 9,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
        ],
        'menu'     => 'group.group_invite.itemActionMenu',
        'name'     => 'cancel',
        'label'    => 'core::phrase.cancel',
        'ordering' => 1,
        'value'    => 'group/cancelInvitation',
    ],
];
