<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.story.story.create'],
        ],
        'menu'     => 'story.addStoryMenu',
        'name'     => 'photo_story',
        'label'    => 'story::phrase.create_a_media_story',
        'ordering' => 1,
        'value'    => 'story/addPhotoStory',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.story.story.create'],
        ],
        'menu'     => 'story.addStoryMenu',
        'name'     => 'text_story',
        'label'    => 'story::phrase.create_a_text_story',
        'ordering' => 2,
        'value'    => 'story/addTextStory',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.story.story.create'],
        ],
        'menu'     => 'core.quickCreateMenu',
        'name'     => 'story',
        'label'    => 'story::phrase.story',
        'ordering' => 1,
        'icon'     => 'ico-movie',
        'to'       => '/story/add',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_owner'],
            ['falsy', 'item.is_muted'],
        ],
        'menu'     => 'story.story.itemActionMenu',
        'name'     => 'mute',
        'label'    => 'mute_user_stories',
        'ordering' => 5,
        'as'       => 'storyItemLabel',
        'value'    => 'story/mute',
        'icon'     => 'ico-eye-alt-blocked',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_owner'],
            ['truthy', 'item.is_muted'],
        ],
        'menu'     => 'story.story.itemActionMenu',
        'name'     => 'unmute',
        'label'    => 'unmute_user_stories',
        'ordering' => 5,
        'as'       => 'storyItemLabel',
        'value'    => 'story/unmute',
        'icon'     => 'ico-eye-alt',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_archive'],
        ],
        'menu'     => 'story.story.itemActionMenu',
        'name'     => 'copy_link',
        'label'    => 'story::phrase.copy_link',
        'ordering' => 8,
        'value'    => 'copyLink',
        'icon'     => 'ico-link',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'story.story.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'story::phrase.delete_story',
        'ordering' => 10,
        'value'    => 'story/deleteItem',
        'icon'     => 'ico-trash',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'isMobile'],
        ],
        'menu'     => 'core.accountMenu',
        'name'     => 'story_archive',
        'label'    => 'story::phrase.story_archive',
        'ordering' => 2,
        'value'    => 'viewArchives',
        'icon'     => 'ico-clock',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'isMobile'],
        ],
        'tab'      => 'muted',
        'menu'     => 'core.accountMenu',
        'name'     => 'muted',
        'label'    => 'story::phrase.story_you_have_muted',
        'ordering' => 2,
        'value'    => 'story/openMutedDialog',
        'icon'     => 'ico-eye-alt-blocked',
    ],
    [
        'showWhen' => [],
        'menu'     => 'story.story_mute.itemActionMenu',
        'name'     => 'unmute',
        'label'    => 'story::phrase.unmute',
        'ordering' => 2,
        'as'       => 'storyItemLabel',
        'value'    => 'deleteItem',
    ],
];
