<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\CurrencyConverter\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'ewallet.conversion_provider',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\ConversionRate\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'ewallet.exchange_rate',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'ewallet.request',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Transaction\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'ewallet.transaction',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawMethod\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'ewallet.withdraw_provider',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Models\\ConversionRate',
        'type'       => 'entity',
        'name'       => 'ewallet_conversion_rate',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Models\\CurrencyConversionRateLog',
        'type'       => 'entity',
        'name'       => 'ewallet_currency_conversion_rate_log',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Models\\CurrencyConverter',
        'type'       => 'entity',
        'name'       => 'ewallet_currency_converter',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Models\\Statistic',
        'type'       => 'entity',
        'name'       => 'ewallet_statistic',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Models\\Transaction',
        'type'       => 'entity',
        'name'       => 'ewallet_transaction',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Models\\WithdrawMethod',
        'type'       => 'entity',
        'name'       => 'ewallet_withdraw_method',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Models\\WithdrawRequest',
        'type'       => 'entity',
        'name'       => 'ewallet_withdraw_request',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Models\\WithdrawRequestReason',
        'type'       => 'entity',
        'name'       => 'ewallet_withdraw_request_reason',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Transaction\\SearchTransactionMobileForm',
        'type'       => 'form',
        'name'       => 'emoney_transaction.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Transaction\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'ewallet.transaction',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\SearchWithdrawRequestMobileForm',
        'type'       => 'form',
        'name'       => 'emoney_withdraw_request.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Gateway\\Admin\\GatewayForm',
        'type'       => 'form',
        'name'       => 'ewallet.gateway.form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\Admin\\DenyWithdrawRequestForm',
        'type'       => 'form',
        'name'       => 'ewallet.request.deny',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\Admin\\SearchWithdrawRequestForm',
        'type'       => 'form',
        'name'       => 'ewallet.request.search_form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\CreateWithdrawRequestMobileForm',
        'type'       => 'form',
        'name'       => 'ewallet.request.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\CreateWithdrawRequestForm',
        'type'       => 'form',
        'name'       => 'ewallet.request.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Transaction\\SearchTransactionMobileForm',
        'type'       => 'form',
        'name'       => 'ewallet_transaction.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\SearchWithdrawRequestMobileForm',
        'type'       => 'form',
        'name'       => 'ewallet_withdraw_request.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\SearchWithdrawRequestForm',
        'type'       => 'form',
        'name'       => 'request.search_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Transaction\\SearchTransactionForm',
        'type'       => 'form',
        'name'       => 'transaction.search_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Transaction\\Admin\\SearchTransactionForm',
        'type'       => 'form',
        'name'       => 'ewallet.transaction.search_form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\CurrencyConverter\\Admin\\EditVisaForm',
        'type'       => 'form-ewallet-converter',
        'name'       => 'ewallet.edit.visa',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'ewallet',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/ewallet/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Policies\\WithdrawRequestPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\EMoney\\Models\\WithdrawRequest',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Statistic\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'emoney_statistic',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Transaction\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'emoney_transaction',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'emoney_withdraw_request',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Statistic\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'ewallet_statistic',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Transaction\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'ewallet_transaction',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'ewallet_withdraw_request',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Statistic\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'ewallet_statistic',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Transaction\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'ewallet_transaction',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\Transaction\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'transaction',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'ewallet_withdraw_request',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\WithdrawRequest\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'request',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\UserBalance\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'ewallet.user_balance',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\UserBalance\\Admin\\Form\\SearchUserBalanceForm',
        'type'       => 'form',
        'name'       => 'ewallet.user_balance.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\UserBalance\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user-balance',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\UserBalance\\Admin\\Form\\SendUserBalanceForm',
        'type'       => 'form',
        'name'       => 'ewallet.user_balance.send',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\UserBalance\\Admin\\Form\\ReduceUserBalanceForm',
        'type'       => 'form',
        'name'       => 'ewallet.user_balance.reduce',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Models\\BalanceAdjustment',
        'type'       => 'entity',
        'name'       => 'ewallet_balance_adjustment',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Balance Adjustment',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\UserBalance\\Admin\\AdjustmentHistoryDataGrid',
        'type'       => 'data-grid',
        'name'       => 'ewallet.user_balance.adjustment_history',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\UserBalance\\Admin\\Form\\SearchAdjustmentHistoryForm',
        'type'       => 'form',
        'name'       => 'ewallet.adjustment_history.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\EMoney\\Http\\Resources\\v1\\UserBalance\\Admin\\AdjustmentHistoryWebSetting',
        'type'       => 'resource-web',
        'name'       => 'adjustment-history',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
];
