<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeAdminApiForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_admin_api',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeCategoryForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_category',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeDataGridForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_data_grid',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeExportForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_export',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeFormForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_form',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeInspectForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_inspect',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeJobForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_job',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeImporterForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_importer',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeListenerForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_listener',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeMailForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_mail',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeMigrationForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_migration',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeModelForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_model',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeNotificationForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_notification',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakePackageForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_package',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakePolicyForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_policy',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeRequestForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_request',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeRuleForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_rule',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeSeederForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_seeder',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Rad\\Http\\Resources\\v1\\Code\\Admin\\MakeWebApiForm',
        'type'       => 'form',
        'name'       => 'rad.code.make_web_api',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'  => 'MetaFox\\Rad\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'rad',
        'version' => 'v1',
    ],
];
