<?php
/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\Invite\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'invite',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\Invite\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'invite',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\InviteCode\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'invite.invite_code',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Models\\Invite',
        'type'       => 'entity',
        'name'       => 'invite',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Models\\InviteTransaction',
        'type'       => 'entity',
        'name'       => 'invite_apt_transactions',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Models\\InviteCode',
        'type'       => 'entity',
        'name'       => 'invite_code',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\Invite\\SearchInviteForm',
        'type'       => 'form',
        'name'       => 'invite.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\InviteCode\\Admin\\SearchInviteCodeForm',
        'type'       => 'form',
        'name'       => 'invite_code.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\Invite\\SearchInviteMobileForm',
        'type'       => 'form',
        'name'       => 'invite.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\Invite\\StoreInviteForm',
        'type'       => 'form',
        'name'       => 'invite.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\Invite\\StoreInviteMobileForm',
        'type'       => 'form',
        'name'       => 'invite.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'      => 'MetaFox\\Invite\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'        => 'form-settings',
        'name'        => 'invite',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'is_active'   => true,
        'is_preload'  => false,
        'title'       => 'core::phrase.settings',
        'url'         => '/invite/setting',
        'description' => 'invite::phrase.edit_invite_setting_desc',
        'type_label'  => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Jobs\\SendInviteJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Invite\\Jobs\\SendInviteJob',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\Invite\\InviteItemCollection',
        'type'       => 'json-collection',
        'name'       => 'invite.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\Invite\\InviteDetail',
        'type'       => 'json-resource',
        'name'       => 'invite.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\Invite\\InviteItem',
        'type'       => 'json-resource',
        'name'       => 'invite.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\Invite\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'invite',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\Invite\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'invite',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\InviteCode\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'invite_code',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\InviteCode\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'invite_code',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\InviteCode\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'invite_code',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Http\\Resources\\v1\\InviteCode\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'invite_code',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Invite\\Support\\Form\\InviteCodeField',
        'type'       => 'form',
        'name'       => 'inviteCode',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
];
