<?php
/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\BackgroundSet\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'story.background_set',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'story.service',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Models\\BackgroundSet',
        'type'       => 'entity',
        'name'       => 'background_set',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Story Background Set',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Models\\Story',
        'type'       => 'entity',
        'name'       => 'story',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Story',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Models\\StoryBackground',
        'type'       => 'entity',
        'name'       => 'story_background',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Story Background',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Models\\PrivacyStream',
        'type'       => 'entity',
        'name'       => 'story_privacy_streams',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Story Privacy Streams',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Models\\StoryReaction',
        'type'       => 'entity',
        'name'       => 'story_reaction',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Story Reaction',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Models\\StoryReactionData',
        'type'       => 'entity',
        'name'       => 'story_reaction_data',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Story Reaction Data',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Models\\StorySet',
        'type'       => 'entity',
        'name'       => 'story_set',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Story Set',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Models\\StoryTagData',
        'type'       => 'entity',
        'name'       => 'story_tag_data',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Story Tag Data',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Models\\StoryText',
        'type'       => 'entity',
        'name'       => 'story_text',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Story Text',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\BackgroundSet\\Admin\\StoreBackgroundSetForm',
        'type'       => 'form',
        'name'       => 'story.background-set.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\BackgroundSet\\Admin\\UpdateBackgroundSetForm',
        'type'       => 'form',
        'name'       => 'story.background-set.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\CreateStoryPhotoMobileForm',
        'type'       => 'form',
        'name'       => 'story.photo.mobile.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\AddExpandLinkMobileForm',
        'type'       => 'form',
        'name'       => 'story.expand_link.mobile',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'is_deleted' => true,
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\AddExpandLinkMobileForm',
        'type'       => 'form',
        'name'       => 'story.expand_link_mobile',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\CreateStoryPhotoForm',
        'type'       => 'form',
        'name'       => 'story.photo.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\CreateStoryTextMobileForm',
        'type'       => 'form',
        'name'       => 'story.text.mobile.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\CreateStoryTextForm',
        'type'       => 'form',
        'name'       => 'story.text.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'story',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/story/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\StoryArchiveCollection',
        'type'       => 'json-collection',
        'name'       => 'story.archive',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\StoryItemCollection',
        'type'       => 'json-collection',
        'name'       => 'story.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryBackground\\StoryBackgroundEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'story_background.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryReaction\\StoryReactionItemCollection',
        'type'       => 'json-collection',
        'name'       => 'story_background.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryView\\StoryViewItemCollection',
        'type'       => 'json-collection',
        'name'       => 'story_view.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\UserStoryCollection',
        'type'       => 'json-collection',
        'name'       => 'user_story.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\BackgroundSet\\BackgroundSetDetail',
        'type'       => 'json-resource',
        'name'       => 'background_set.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\BackgroundSet\\BackgroundSetEmbed',
        'type'       => 'json-resource',
        'name'       => 'background_set.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\StoryArchive',
        'type'       => 'json-resource',
        'name'       => 'story.archive',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\StoryDetail',
        'type'       => 'json-resource',
        'name'       => 'story.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\StoryItem',
        'type'       => 'json-resource',
        'name'       => 'story.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryBackground\\StoryBackgroundDetail',
        'type'       => 'json-resource',
        'name'       => 'story_background.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryBackground\\StoryBackgroundEmbed',
        'type'       => 'json-resource',
        'name'       => 'story_background.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryBackground\\StoryBackgroundItem',
        'type'       => 'json-resource',
        'name'       => 'story_background.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryReaction\\StoryReactionDetail',
        'type'       => 'json-resource',
        'name'       => 'story_reaction.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryReaction\\StoryReactionItem',
        'type'       => 'json-resource',
        'name'       => 'story_reaction.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryView\\StoryViewDetail',
        'type'       => 'json-resource',
        'name'       => 'story_view.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryView\\StoryViewItem',
        'type'       => 'json-resource',
        'name'       => 'story_view.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\UserStory',
        'type'       => 'json-resource',
        'name'       => 'user_story.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'story',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Story\\Policies\\StoryPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Story\\Models\\Story',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'story',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\BackgroundSet\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'story_background_set',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryReaction\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'story_reaction',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryView\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'story_view',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Mute\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'story_mute',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Story\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'story',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\BackgroundSet\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'story_background_set',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryReaction\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'story_reaction',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\StoryView\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'story_view',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Mute\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'story_mute',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Mute\\CreateMuteForm',
        'type'       => 'form',
        'name'       => 'story.mute.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Story\\Http\\Resources\\v1\\Mute\\CreateMuteMobileForm',
        'type'       => 'form',
        'name'       => 'story.mute.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
];
