<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'blog::phrase.edit_blog',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_publish'],
            ['truthy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'publish',
        'label'    => 'blog::phrase.publish',
        'ordering' => 3,
        'value'    => 'publishBlog',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'blog::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'blog::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'blog::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'blog::phrase.un_sponsor_in_feed',
        'ordering' => 6,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'blog::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'blog::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'blog::phrase.unsponsor_this_item',
        'ordering' => 8,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion'],
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_draft'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureFreeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 9,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion'],
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'remove_feature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'blog.blog.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'blog.blog.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'blog::phrase.delete',
        'ordering'  => 13,
        'value'     => 'deleteItem',
    ],
    [
        'menu'     => 'blog.blog.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'blog.blog.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'blog.blog.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'blog.blog.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'blog::phrase.edit_blog',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_publish'],
            ['truthy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'publish',
        'label'    => 'blog::phrase.publish',
        'ordering' => 3,
        'value'    => 'publishBlog',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'blog::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'blog::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'blog::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'blog::phrase.un_sponsor_in_feed',
        'ordering' => 6,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'blog::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'blog::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'advertise/purchaseSponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'blog::phrase.unsponsor_this_item',
        'ordering' => 8,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion'],
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_draft'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureFreeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 9,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion'],
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_draft'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'remove_feature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'blog.blog.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'blog.blog.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'blog::phrase.delete',
        'ordering'  => 13,
        'value'     => 'deleteItem',
    ],
    [
        'menu'     => 'blog.blog.sort_menu',
        'name'     => 'latest',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'latest',
    ],
    [
        'menu'     => 'blog.blog.sort_menu',
        'name'     => 'most_viewed',
        'label'    => 'core::phrase.sort.most_viewed',
        'ordering' => 2,
        'value'    => 'most_viewed',
    ],
    [
        'menu'     => 'blog.blog.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 3,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'blog.blog.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 4,
        'value'    => 'most_discussed',
    ],
    [
        'tab'      => 'all',
        'params'   => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'all',
        'label'    => 'blog::phrase.all_blogs',
        'ordering' => 1,
        'value'    => 'viewAll',
        'to'       => '/blog/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
        ],
        'params'   => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'my',
        'label'    => 'blog::phrase.my_blogs',
        'ordering' => 2,
        'value'    => 'viewMyBlogs',
        'to'       => '/blog/my',
    ],
    [
        'params'   => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'showWhen' => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'blog::phrase.my_pending_blogs',
        'ordering' => 3,
        'value'    => 'viewMyPendingBlogs',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
        ],
        'params'   => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'friends',
        'label'    => 'blog::phrase.friends_blogs',
        'ordering' => 4,
        'value'    => 'viewFriendBlogs',
        'to'       => '/blog/friend',
    ],
    [
        'tab'      => 'draft',
        'showWhen' => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
        ],
        'params'   => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'draft',
        'label'    => 'blog::phrase.my_draft_blogs',
        'ordering' => 5,
        'value'    => 'viewDraftBlogs',
        'to'       => '/blog/draft',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'or',
            ['truthy', 'acl.blog.blog.approve'],
        ],
        'params'   => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'menu'     => 'blog.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'blog::phrase.pending_blogs',
        'ordering' => 6,
        'value'    => 'viewPendingBlogs',
        'to'       => '/blog/pending',
    ],
    [
        'tab'      => 'blog',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.blogs',
        'ordering' => 9,
        'to'       => '/blog',
        'params'   => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'tab'      => 'blog',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.blogs',
        'ordering' => 9,
        'to'       => '/blog',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
        ],
        'module_name'   => 'blog',
        'resource_name' => 'blog',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'blog',
        'label'         => 'blog::phrase.blog_global_search_label',
        'ordering'      => 3,
        'value'         => 'searchGlobalBlog',
    ],
    [
        'tab'      => 'blog',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.blog'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'blog',
        'label'    => 'blog::phrase.blogs',
        'ordering' => 9,
        'to'       => '/blog',
        'params'   => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
        ],
        'module_name'   => 'blog',
        'resource_name' => 'blog',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'blog',
        'label'         => 'blog::phrase.blog_global_search_label',
        'ordering'      => 3,
        'value'         => 'searchGlobalBlog',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
        ],
        'module_name'   => 'blog',
        'resource_name' => 'blog',
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'blog',
        'label'         => 'blog::phrase.blog_global_search_label',
        'ordering'      => 3,
        'value'         => 'searchGlobalBlog',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.blog.blog.view'],
        ],
        'menu'          => 'search.mobileHashtagCategoryMenu',
        'name'          => 'blog',
        'label'         => 'blog::phrase.blog_global_search_label',
        'ordering'      => 2,
        'module_name'   => 'blog',
        'resource_name' => 'blog',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'blog',
        'label'     => 'blog::phrase.blogs',
        'ordering'  => 9,
        'value'     => '',
        'to'        => '/blog',
        'as'        => 'item',
        'icon'      => 'newspaper-alt',
        'iconColor' => '#0097fc',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'blog.blog.headerItemActionOnUserProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["truthy", "acl.blog.blog.create"],
            ["truthy", "item.is_owner"],
        ],
        'menu'       => 'blog.blog.headerItemActionOnUserProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'blog.blog.headerItemActionOnPageProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["truthy", "acl.blog.blog.create"],
            ["truthy", "item.profile_settings.blog_share_blogs"],
            ["falsy", "item.is_pending"],
        ],
        'menu'       => 'blog.blog.headerItemActionOnPageProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'blog.blog.headerItemActionOnGroupProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["truthy", "acl.blog.blog.create"],
            ["truthy", "item.profile_settings.blog_share_blogs"],
            ["falsy", "item.is_muted"],
            ["falsy", "item.is_pending"],
        ],
        'menu'       => 'blog.blog.headerItemActionOnGroupProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'blog',
            'resource_name' => 'blog',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
];
