<?php
/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\AntiSpamQuestion\\Http\\Resources\\v1\\Question\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'antispamquestion.question',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\AntiSpamQuestion\\Models\\Answer',
        'type'       => 'entity',
        'name'       => 'answer',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\AntiSpamQuestion\\Models\\Question',
        'type'       => 'entity',
        'name'       => 'question',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\AntiSpamQuestion\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'antispamquestion',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/anti-spam-question/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\AntiSpamQuestion\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'antispamquestion',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\AntiSpamQuestion\\Http\\Resources\\v1\\Question\\Admin\\ViewAnswersForm',
        'type'       => 'form',
        'name'       => 'antispamquestion.view_answer',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\AntiSpamQuestion\\Http\\Resources\\v1\\Question\\Admin\\SearchQuestionForm',
        'type'       => 'form',
        'name'       => 'antispamquestion.question.search_form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\AntiSpamQuestion\\Http\\Resources\\v1\\Question\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'question',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
];
