<?php
/* this is auto generated file */
return [
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Package\\Admin\\DataGrid',
        'type' => 'data-grid',
        'name' => 'featured.package',
        'version' => 'v1',
        'resolution' => 'admin',
        'is_active' => true,
        'is_preload' => false,
        'title' => 'Data Grid Settings',
        'type_label' => 'Data Grid'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Item\\Admin\\SearchSettingItemForm',
        'type' => 'form',
        'name' => 'featured.item.search_setting_form',
        'version' => 'v1',
        'resolution' => 'admin',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Form'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type' => 'form-settings',
        'name' => 'featured',
        'version' => 'v1',
        'resolution' => 'admin',
        'is_active' => true,
        'is_preload' => false,
        'title' => 'core::phrase.settings',
        'url' => '/featured/setting',
        'description' => 'featured::phrase.edit_featured_setting_desc',
        'type_label' => 'Form Settings'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\PackageSetting',
        'type' => 'package-setting',
        'name' => 'featured',
        'version' => 'v1',
        'is_active' => true,
        'is_preload' => false
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Item\\Admin\\WebSetting',
        'type' => 'resource-web',
        'name' => 'featured_item',
        'version' => 'v1',
        'resolution' => 'admin',
        'alias' => 'item',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Resource Web'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Package\\Admin\\WebSetting',
        'type' => 'resource-web',
        'name' => 'featured_package',
        'version' => 'v1',
        'resolution' => 'admin',
        'alias' => 'package',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Resource Web'
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Http\\Resources\\v1\\Package\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'featured.package',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Package\\Admin\\SearchPackageForm',
        'type' => 'form',
        'name' => 'featured.package.search_form',
        'version' => 'v1',
        'resolution' => 'admin',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Form'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Item\\Admin\\SettingItemForm',
        'type' => 'form-settings',
        'name' => 'featured.item',
        'version' => 'v1',
        'resolution' => 'admin',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Form'
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Policies\\Handlers\\CanFeatureFree',
        'type'       => 'policy-rule',
        'name'       => 'featureFree',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Policies\\Handlers\\CanPurchaseFeature',
        'type'       => 'policy-rule',
        'name'       => 'purchaseFeature',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Policies\\Handlers\\CanUnfeature',
        'type'       => 'policy-rule',
        'name'       => 'unfeature',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Http\\Resources\\v1\\Package\\PackageEmbed',
        'type'       => 'json-resource',
        'name'       => 'featured_package.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Http\\Resources\\v1\\Invoice\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'featured.invoice',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Http\\Resources\\v1\\Item\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'featured.item',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Http\\Resources\\v1\\Invoice\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'featured_invoice',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Http\\Resources\\v1\\Item\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'featured_item',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Transaction\\Admin\\DataGrid',
        'type' => 'data-grid',
        'name' => 'featured.transaction',
        'version' => 'v1',
        'resolution' => 'admin',
        'is_active' => true,
        'is_preload' => false,
        'title' => 'Data Grid Settings',
        'type_label' => 'Data Grid'
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Http\\Resources\\v1\\Transaction\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'featured_transaction',
        'version'    => 'v1',
        'resolution' => 'admin',
        'alias'      => 'transaction',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Transaction\\Admin\\SearchTransactionForm',
        'type' => 'form',
        'name' => 'featured.transaction.search_form',
        'version' => 'v1',
        'resolution' => 'admin',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Form'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Invoice\\Admin\\DataGrid',
        'type' => 'data-grid',
        'name' => 'featured.invoice',
        'version' => 'v1',
        'resolution' => 'admin',
        'is_active' => true,
        'is_preload' => false,
        'title' => 'Data Grid Settings',
        'type_label' => 'Data Grid'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Invoice\\Admin\\SearchInvoiceForm',
        'type' => 'form',
        'name' => 'featured.invoice.search_form',
        'version' => 'v1',
        'resolution' => 'admin',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Form'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Invoice\\SearchInvoiceForm',
        'type' => 'form',
        'name' => 'featured.invoice.search_form',
        'version' => 'v1',
        'resolution' => 'web',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Form'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Invoice\\SearchInvoiceMobileForm',
        'type' => 'form',
        'name' => 'featured.invoice.search_form',
        'version' => 'v1',
        'resolution' => 'mobile',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Form'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Item\\SearchItemForm',
        'type' => 'form',
        'name' => 'featured.item.search_form',
        'version' => 'v1',
        'resolution' => 'web',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Form'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Item\\SearchItemMobileForm',
        'type' => 'form',
        'name' => 'featured.item.search_form',
        'version' => 'v1',
        'resolution' => 'mobile',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Form'
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Http\\Resources\\v1\\Invoice\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'featured_invoice',
        'version'    => 'v1',
        'resolution' => 'admin',
        'alias'      => 'invoice',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Models\\Package',
        'type'       => 'entity',
        'name'       => 'featured_package',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Featured Package',
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Models\\Invoice',
        'type'       => 'entity',
        'name'       => 'featured_invoice',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Featured Invoice',
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Models\\Item',
        'type'       => 'entity',
        'name'       => 'featured_item',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Featured Item',
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Models\\Transaction',
        'type'       => 'entity',
        'name'       => 'featured_transaction',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Featured Transaction',
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Invoice\\PaymentInvoiceForm',
        'type' => 'form',
        'name' => 'featured.invoice.payment',
        'version' => 'v1',
        'resolution' => 'web',
        'is_active' => true,
        'is_preload' => false,
        'type_label' => 'Form'
    ],

    [
        'driver'     => 'MetaFox\\Featured\\Http\\Resources\\v1\\Item\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'featured_item',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Featured\\Http\\Resources\\v1\\Invoice\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'featured_invoice',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Item\\SearchItemMobileForm',
        'type' => 'form',
        'name' => 'featured_item.search',
        'version' => 'v1',
        'resolution' => 'mobile',
        'is_active' => true,
        'is_preload' => true,
        'type_label' => 'Form'
    ],
    [
        'driver' => 'MetaFox\\Featured\\Http\\Resources\\v1\\Invoice\\SearchInvoiceMobileForm',
        'type' => 'form',
        'name' => 'featured_invoice.search',
        'version' => 'v1',
        'resolution' => 'mobile',
        'is_active' => true,
        'is_preload' => true,
        'type_label' => 'Form'
    ],
];
