<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionCancelReason\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'subscription.cancel_reason',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionComparison\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'subscription.comparison',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionInvoice\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'subscription.invoice',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionInvoiceTransaction\\TransactionDataGrid',
        'type'       => 'data-grid',
        'name'       => 'subscription.invoice.detail',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionPackage\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'subscription.package',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Models\\SubscriptionCancelReason',
        'type'       => 'entity',
        'name'       => 'subscription_cancel_reason',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Models\\SubscriptionComparison',
        'type'       => 'entity',
        'name'       => 'subscription_comparison',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Models\\SubscriptionComparisonData',
        'type'       => 'entity',
        'name'       => 'subscription_comparison_data',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Models\\SubscriptionDependencyPackage',
        'type'       => 'entity',
        'name'       => 'subscription_dependency_package',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Models\\SubscriptionInvoice',
        'type'       => 'entity',
        'name'       => 'subscription_invoice',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Models\\SubscriptionInvoiceTransaction',
        'type'       => 'entity',
        'name'       => 'subscription_invoice_transaction',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Models\\SubscriptionPackage',
        'type'       => 'entity',
        'name'       => 'subscription_package',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Subscription Packages',
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Models\\SubscriptionPackageText',
        'type'       => 'entity',
        'name'       => 'subscription_packages_text',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Models\\SubscriptionPendingRegistrationUser',
        'type'       => 'entity',
        'name'       => 'subscription_pending_registration_user',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Models\\SubscriptionUserCancelReason',
        'type'       => 'entity',
        'name'       => 'subscription_user_cancel_reason',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionCancelReason\\Admin\\CreateSubscriptionCancelReasonForm',
        'type'       => 'form',
        'name'       => 'subscription.cancel_reason.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionCancelReason\\Admin\\EditSubscriptionCancelReasonForm',
        'type'       => 'form',
        'name'       => 'subscription.cancel_reason.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionComparison\\Admin\\CreateSubscriptionComparisonForm',
        'type'       => 'form',
        'name'       => 'subscription.comparison.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionComparison\\Admin\\EditSubscriptionComparisonForm',
        'type'       => 'form',
        'name'       => 'subscription.comparison.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionInvoice\\Admin\\SearchSubscriptionInvoiceForm',
        'type'       => 'form',
        'name'       => 'subscription.invoice.search_form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionPackage\\Admin\\SearchSubscriptionPackageForm',
        'type'       => 'form',
        'name'       => 'subscription.package.search_form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionPackage\\Admin\\CreateSubscriptionPackageForm',
        'type'       => 'form',
        'name'       => 'subscription.package.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionPackage\\Admin\\EditSubscriptionPackageForm',
        'type'       => 'form',
        'name'       => 'subscription.package.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionInvoice\\CancelSubscriptionInvoiceMobileForm',
        'type'       => 'form',
        'name'       => 'subscription.subscription_invoice.cancel',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionInvoice\\CancelSubscriptionInvoiceForm',
        'type'       => 'form',
        'name'       => 'subscription.subscription_invoice.cancel',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionInvoice\\Admin\\SearchSubscriptionInvoiceForm',
        'type'       => 'form',
        'name'       => 'subscription.subscription_invoice.search_form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'subscription',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/subscription/setting',
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Jobs\\DowngradeSubscription',
        'type'       => 'job',
        'name'       => 'MetaFox\\Subscription\\Jobs\\DowngradeSubscription',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionInvoice\\Admin\\SubscriptionInvoiceItemCollection',
        'type'       => 'json-collection',
        'name'       => 'subscription_invoice.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionComparison\\SubscriptionComparisonItem',
        'type'       => 'json-resource',
        'name'       => 'subscription_comparison.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionComparison\\Admin\\SubscriptionComparisonItem',
        'type'       => 'json-resource',
        'name'       => 'subscription_comparison.item_admincp',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionInvoice\\SubscriptionInvoiceItem',
        'type'       => 'json-resource',
        'name'       => 'subscription_invoice.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'subscription',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Policies\\SubscriptionCancelReasonPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Subscription\\Models\\SubscriptionCancelReason',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Policies\\SubscriptionPackagePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Subscription\\Models\\SubscriptionPackage',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Policies\\SubscriptionInvoicePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Subscription\\Models\\SubscriptionInvoice',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionCancelReason\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'subscription_cancel_reason',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionComparison\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'subscription_comparison',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionInvoice\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'subscription_invoice',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionPackage\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'subscription_package',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionCancelReason\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'subscription_cancel_reason',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionCancelReason\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'subscription_cancel_reason',
        'version'    => 'v1',
        'resolution' => 'admin',
        'alias'      => 'cancel-reason',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionComparison\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'subscription_comparison',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionComparison\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'subscription_comparison',
        'version'    => 'v1',
        'resolution' => 'admin',
        'alias'      => 'comparison',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionInvoice\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'subscription_invoice',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionInvoice\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'subscription_invoice',
        'version'    => 'v1',
        'resolution' => 'admin',
        'alias'      => 'invoice',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionPackage\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'subscription_package',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Subscription\\Http\\Resources\\v1\\SubscriptionPackage\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'subscription_package',
        'version'    => 'v1',
        'resolution' => 'admin',
        'alias'      => 'package',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
