<?php
/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationModule\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'notification.module',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationChannel\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'notification.channel',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Type\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'notification.type',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Models\\Notification',
        'type'       => 'entity',
        'name'       => 'notification',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Models\\NotificationChannel',
        'type'       => 'entity',
        'name'       => 'notification_channel',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Models\\Type',
        'type'       => 'entity',
        'name'       => 'notification_type',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Type\\MailNotificationFromForm',
        'type'       => 'form',
        'name'       => 'notification.mail_settings',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Type\\Admin\\UpdateTypeForm',
        'type'       => 'form',
        'name'       => 'notification.notification_type.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'notification',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/notification/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Notification\\NotificationItemCollection',
        'type'       => 'json-collection',
        'name'       => 'notification.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Type\\Admin\\TypeItemCollection',
        'type'       => 'json-collection',
        'name'       => 'notification_type.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Notification\\NotificationItem',
        'type'       => 'json-resource',
        'name'       => 'notification.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Type\\Admin\\TypeDetail',
        'type'       => 'json-resource',
        'name'       => 'notification_type.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Type\\Admin\\TypeItem',
        'type'       => 'json-resource',
        'name'       => 'notification_type.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationSetting\\NotificationSettingMobileForm',
        'type'       => 'notification-channel-form',
        'name'       => 'database',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationSetting\\NotificationSettingForm',
        'type'       => 'notification-channel-form',
        'name'       => 'database',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationSetting\\NotificationSettingForm',
        'type'       => 'notification-channel-form',
        'name'       => 'mail',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationSetting\\NotificationSettingMobileForm',
        'type'       => 'notification-channel-form',
        'name'       => 'mail',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationSetting\\NotificationSettingMobileForm',
        'type'       => 'notification-channel-form',
        'name'       => 'sms',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationSetting\\NotificationSettingForm',
        'type'       => 'notification-channel-form',
        'name'       => 'sms',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'notification',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Policies\\NotificationPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Notification\\Models\\Notification',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Policies\\TypePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Notification\\Models\\Type',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Notification\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'notification',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationSetting\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'notification_setting',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Notification\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'notification',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Notification\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'notification',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationSetting\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'notification_setting',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\Type\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'notification_type',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationSetting\\NotificationSettingForm',
        'type'       => 'form',
        'name'       => 'notification.notification_setting.channel',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Notification\\Http\\Resources\\v1\\NotificationSetting\\NotificationSettingMobileForm',
        'type'       => 'form',
        'name'       => 'notification.notification_setting.channel',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
