<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.view'],
            ['truthy', 'acl.friend.friend_list.update'],
        ],
        'menu'     => 'friend.friend_list.itemActionMenu',
        'name'     => 'add',
        'label'    => 'friend::phrase.add_friends',
        'ordering' => 1,
        'value'    => 'friend_list/addFriend',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.update'],
        ],
        'menu'     => 'friend.friend_list.itemActionMenu',
        'name'     => 'edit_list',
        'label'    => 'friend::phrase.edit_friend_list',
        'ordering' => 2,
        'value'    => 'friend_list/editList',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'friend.friend_list.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'friend::phrase.delete',
        'ordering' => 3,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen' => [],
        'tab'      => 'landing',
        'params'   => [
            'module_name'   => 'friend',
            'resource_name' => 'friend',
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'friend::phrase.all_friends',
        'ordering' => 1,
        'value'    => 'viewAll',
        'to'       => '/friend',
    ],
    [
        'tab'      => 'incoming',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'friend',
            'resource_name' => 'friend_request',
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'incoming_request',
        'label'    => 'friend::phrase.friend_requests',
        'ordering' => 2,
        'value'    => 'viewAll',
        'to'       => '/friend/requests',
    ],
    [
        'tab'      => 'send_request',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'friend',
            'resource_name' => 'friend_request',
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'send_request',
        'label'    => 'friend::phrase.sent_requests',
        'ordering' => 3,
        'value'    => 'viewSentRequests',
        'to'       => '/friend/send-requests',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.view'],
        ],
        'params' => [
            'module_name'   => 'friend',
            'resource_name' => 'friend_list',
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'friend_list',
        'label'    => 'friend::phrase.friend_lists',
        'ordering' => 4,
        'value'    => 'viewAll',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'setting.friend.enable_birthday_notices'],
        ],
        'params' => [
            'module_name'   => 'friend',
            'resource_name' => 'friend',
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'birthday',
        'label'    => 'friend::phrase.birthdays',
        'ordering' => 5,
        'value'    => 'getFriendBirthday',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.friend'],
            ['truthy', 'item.profile_settings.friend_view_friend'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'friend',
        'label'    => 'friend::phrase.friends',
        'ordering' => 3,
        'to'       => '/friend',
        'params'   => [
            'module_name'   => 'friend',
            'resource_name' => 'friend',
        ],
        'value' => 'viewFriend',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'friend',
        'label'     => 'friend::phrase.friends',
        'ordering'  => 3,
        'value'     => '',
        'to'        => '/friend',
        'as'        => 'item',
        'icon'      => 'user1-two',
        'iconColor' => '#2e88ed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
            ['gte', 'session.user.statistic.total_friend', 1],
        ],
        'params' => [
            'module_name'   => 'friend',
            'resource_name' => 'friend',
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_on_friends',
        'label'    => 'activity::phrase.share_on_friends',
        'ordering' => 3,
        'value'    => 'shareOnFriendProfile',
    ],
    [
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'friend',
            'resource_name' => 'friend',
        ],
        'menu'       => 'friend.friend.headerItemActionOnUserProfileMenu',
        'name'       => 'search',
        'label'      => '',
        'ordering'   => 1,
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen' => [
            'and',
            [
                'includes',
                'item.friendship',
                [0, 7],
            ],
            ['truthy', 'item.extra.can_add_friend'],
        ],
        'params' => [
            'module_name'   => 'friend',
            'resource_name' => 'friend_suggestion',
        ],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'add_friend',
        'label'    => 'user::phrase.add_friend',
        'ordering' => 1,
        'value'    => 'user/addFriend',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 3],
        'params'   => [
            'module_name'   => 'friend',
            'resource_name' => 'friend_suggestion',
        ],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'user::phrase.cancel_request',
        'ordering' => 1,
        'value'    => 'user/cancelRequest',
    ],
    [
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'friend',
            'resource_name' => 'friend_suggestion',
        ],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'remove',
        'label'    => 'friend::phrase.remove',
        'ordering' => 2,
        'value'    => 'friend/hideUserSuggestion',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 2],
        ],
        'params' => [
            'module_name'   => 'friend',
            'resource_name' => 'friend_suggestion',
        ],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'confirm_request',
        'label'    => 'user::phrase.accept_friend_request',
        'ordering' => 3,
        'value'    => 'user/acceptFriendRequest',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 2],
        ],
        'params' => [
            'module_name'   => 'friend',
            'resource_name' => 'friend_suggestion',
        ],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'delete_request',
        'label'    => 'user::phrase.delete_friend_request',
        'ordering' => 4,
        'value'    => 'user/denyFriendRequest',
    ],
    [
        'style'  => 'danger',
        'params' => [
            'module_name'   => 'friend',
            'resource_name' => 'friend_suggestion',
        ],
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_block'],
            ['falsy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'block',
        'label'    => 'user::phrase.block_this_user',
        'ordering' => 6,
        'value'    => 'blockItem',
    ],
];
