<?php

/* this is auto generated file */
return [
    [
        'menu'       => 'core.accountMenu',
        'name'       => 'manage_friends',
        'label'      => 'friend::phrase.manage_friends',
        'ordering'   => 4,
        'icon'       => 'ico-user-couple',
        'to'         => '/friend',
        'is_deleted' => 1,
    ],
    [
        'subInfo'  => 'friend::phrase.see_your_friends',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'friends',
        'label'    => 'friend::phrase.friends',
        'ordering' => 2,
        'icon'     => 'ico-user1-two',
        'to'       => '/friend',
    ],
    [
        'placement' => 'bottom',
        'content'   => [
            'component' => 'friend_request.ui.friendRequestsPopper',
        ],
        'menu'     => 'core.headerSubMenu',
        'name'     => 'new_friend_request',
        'label'    => 'friend::phrase.friend_requests',
        'ordering' => 2,
        'as'       => 'popover',
        'icon'     => 'ico-user-man-plus-o',
        'to'       => '/friend_request',
    ],
    [
        'menu'     => 'core.primaryMenu',
        'name'     => 'friends',
        'label'    => 'friend::phrase.friends',
        'ordering' => 2,
        'icon'     => 'ico-user1-two',
        'to'       => '/friend',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.view'],
            ['truthy', 'acl.friend.friend_list.update'],
        ],
        'menu'     => 'friend.friend_list.itemActionMenu',
        'name'     => 'add',
        'label'    => 'friend::phrase.add_friends',
        'ordering' => 1,
        'value'    => 'friend_list/addFriend',
        'icon'     => 'ico-plus',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.update'],
        ],
        'menu'     => 'friend.friend_list.itemActionMenu',
        'name'     => 'edit_list',
        'label'    => 'friend::phrase.edit_friend_list',
        'ordering' => 2,
        'value'    => 'friend_list/editList',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.delete'],
        ],
        'menu'     => 'friend.friend_list.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'friend::phrase.delete',
        'ordering' => 3,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.user.user.isLoggedIn'],
        ],
        'tab'      => 'landing',
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'friend::phrase.all_friends',
        'ordering' => 1,
        'icon'     => 'ico-user1-two-o',
        'to'       => '/friend',
    ],
    [
        'tab'      => 'incoming',
        'showWhen' => [
            'and',
            ['truthy', 'acl.user.user.isLoggedIn'],
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'incoming_request',
        'label'    => 'friend::phrase.friend_requests',
        'ordering' => 2,
        'icon'     => 'ico-user2-down-o',
        'to'       => '/friend/requests',
    ],
    [
        'tab'      => 'send_request',
        'showWhen' => [
            'and',
            ['truthy', 'acl.user.user.isLoggedIn'],
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'send_request',
        'label'    => 'friend::phrase.sent_requests',
        'ordering' => 3,
        'icon'     => 'ico-user3-clock-o',
        'to'       => '/friend/send-requests',
    ],
    [
        'tab'      => 'birthday',
        'showWhen' => [
            'and',
            ['truthy', 'setting.friend.enable_birthday_notices'],
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'birthday',
        'label'    => 'friend::phrase.birthdays',
        'ordering' => 4,
        'icon'     => 'ico-gift-o',
        'to'       => '/friend/birthday',
    ],
    [
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'showWhen' => [
            'and',
            ['truthy', 'acl.user.user.isLoggedIn'],
            ['truthy', 'acl.friend.friend_list.create'],
        ],
        'menu'     => 'friend.sidebarMenu',
        'name'     => 'add_new_list',
        'label'    => 'friend::phrase.add_new_list',
        'ordering' => 5,
        'as'       => 'sidebarButton',
        'value'    => 'friend/addNewList',
        'icon'     => 'ico-plus',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.friend'],
            ['truthy', 'item.profile_settings.friend_view_friend'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'friend',
        'label'    => 'friend::phrase.friends',
        'ordering' => 3,
        'to'       => '/friend',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
            ['gte', 'session.user.statistic.total_friend', 1],
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_on_friends',
        'label'    => 'activity::phrase.share_on_friends',
        'ordering' => 3,
        'value'    => 'friend/shareOnFriendProfile',
        'icon'     => 'ico-user1-two',
    ],
    [
        'showWhen' => [
            'and',
            [
                'includes',
                'item.friendship',
                [0, 7],
            ],
            ['truthy', 'item.extra.can_add_friend'],
        ],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'add_friend',
        'label'    => 'user::phrase.add_friend',
        'ordering' => 1,
        'value'    => 'user/addFriend',
        'icon'     => 'ico-plus',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 3],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'user::phrase.cancel_request',
        'ordering' => 1,
        'value'    => 'user/cancelRequest',
        'icon'     => 'ico-user2-del-o',
    ],
    [
        'showWhen' => [],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'remove',
        'label'    => 'friend::phrase.remove',
        'ordering' => 2,
        'value'    => 'friend/hideUserSuggestion',
        'icon'     => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 2],
        ],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'confirm_request',
        'label'    => 'user::phrase.accept_friend_request',
        'ordering' => 3,
        'value'    => 'user/acceptFriendRequest',
        'icon'     => 'ico-check',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 2],
        ],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'delete_request',
        'label'    => 'user::phrase.delete_friend_request',
        'ordering' => 4,
        'value'    => 'user/denyFriendRequest',
        'icon'     => 'ico-close',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'item.extra.can_block'],
            ['falsy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'friend.friend_suggestion.itemActionMenu',
        'name'     => 'block',
        'label'    => 'user::phrase.block_this_user',
        'ordering' => 6,
        'value'    => 'blockItem',
        'icon'     => 'ico-ban',
    ],
];
