<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelReason\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user.cancel_reason',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelFeedback\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user.cancelled.feedback',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\ExportProcess\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user.export_process',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserInactive\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user.inactive',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\InactiveProcess\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user.inactive_process',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user.relation',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'user.user_gender',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserShortcut',
        'type'       => 'entity',
        'name'       => 'shortcut',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\User',
        'type'       => 'entity',
        'name'       => 'user',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Users',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\ExportProcess',
        'type'       => 'entity',
        'name'       => 'user_export_process',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Users',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserActivity',
        'type'       => 'entity',
        'name'       => 'user_activity',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserBlocked',
        'type'       => 'entity',
        'name'       => 'user_blocked',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\CancelFeedback',
        'type'       => 'entity',
        'name'       => 'user_cancel_feedback',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\CancelReason',
        'type'       => 'entity',
        'name'       => 'user_cancel_reason',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserGender',
        'type'       => 'entity',
        'name'       => 'user_gender',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserProfile',
        'type'       => 'entity',
        'name'       => 'user_profile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserPromotion',
        'type'       => 'entity',
        'name'       => 'user_promotion',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserRelation',
        'type'       => 'entity',
        'name'       => 'user_relation',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserRelationData',
        'type'       => 'entity',
        'name'       => 'user_relation_data',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserRelationHistory',
        'type'       => 'entity',
        'name'       => 'user_relation_history',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserValue',
        'type'       => 'entity',
        'name'       => 'user_value',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserVerify',
        'type'       => 'entity',
        'name'       => 'user_verify',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\UserVerifyError',
        'type'       => 'entity',
        'name'       => 'user_verify_error',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\User',
        'type'       => 'entity-content',
        'name'       => 'user',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Users',
    ],
    [
        'driver'     => 'MetaFox\\User\\Models\\User',
        'type'       => 'entity-user',
        'name'       => 'user',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Content Type',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\AccountCancelForm',
        'type'       => 'form',
        'name'       => 'user.account.cancel',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\AccountCancelMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.cancel',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditCurrencyMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_currency_id',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditCurrencyForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_currency_id',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditEmailAddressForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_email',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditEmailAddressMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_email',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditNameMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_full_name',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditNameForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_full_name',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditLanguageMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_language_id',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditLanguageForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_language_id',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditPasswordMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_password',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditPasswordForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_password',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditPaymentForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_payment',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditPhoneNumberForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_phone_number',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditPhoneNumberMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_phone_number',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditTimezoneForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_timezone',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditUserNameMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_user_name',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditUserNameForm',
        'type'       => 'form',
        'name'       => 'user.account.edit_user_name',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\AccountSettingMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.info',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\LanguageForm',
        'type'       => 'form',
        'name'       => 'user.account.language_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditReviewTagPostMobileForm',
        'type'       => 'form',
        'name'       => 'user.account.review_tag',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\EditVideoSettingsForm',
        'type'       => 'form',
        'name'       => 'user.account_setting.video',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\AccountPopupForm',
        'type'       => 'form',
        'name'       => 'user.add_account_popup',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\BanUserForm',
        'type'       => 'form',
        'name'       => 'user.ban',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\BatchMoveRoleForm',
        'type'       => 'form',
        'name'       => 'user.batch_move_role',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelFeedback\\Admin\\ViewFeedbackForm',
        'type'       => 'form',
        'name'       => 'user.cancelled.view_feedback',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\DenyUserForm',
        'type'       => 'form',
        'name'       => 'user.deny',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\DenyUserMobileForm',
        'type'       => 'form',
        'name'       => 'user.deny',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\DenyUserForm',
        'type'       => 'form',
        'name'       => 'user.deny_user',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\ExportUserForm',
        'type'       => 'form',
        'name'       => 'user.export',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\ExportProcess\\Admin\\ExportUserForm',
        'type'       => 'form',
        'name'       => 'user.export_process.create',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\ExportProcess\\Admin\\SearchExportProcessForm',
        'type'       => 'form',
        'name'       => 'export_process.search_form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\PasswordRequestForm',
        'type'       => 'form',
        'name'       => 'user.forgot_password',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\PasswordRequestMobileForm',
        'type'       => 'form',
        'name'       => 'user.forgot_password',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserInactive\\Admin\\SearchUserInactiveForm',
        'type'       => 'form',
        'name'       => 'user.inactive.search_form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\InactiveProcess\\Admin\\CreateInactiveProcessForm',
        'type'       => 'form',
        'name'       => 'user.inactive_process.create',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserLoginForm',
        'type'       => 'form',
        'name'       => 'user.login',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserLoginMobileForm',
        'type'       => 'form',
        'name'       => 'user.login',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\UserLoginForm',
        'type'       => 'form',
        'name'       => 'user.login',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\LoginPopupUserForm',
        'type'       => 'form',
        'name'       => 'user.login_popup',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\UpdatePasswordForm',
        'type'       => 'form',
        'name'       => 'user.password.edit',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\UpdatePasswordMobileForm',
        'type'       => 'form',
        'name'       => 'user.password.edit',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\LogoutAllDeviceForm',
        'type'       => 'form',
        'name'       => 'user.password.logout_all',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\RequestMethodMobileForm',
        'type'       => 'form',
        'name'       => 'user.password.request_method',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\RequestMethodForm',
        'type'       => 'form',
        'name'       => 'user.password.request_method',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\VerifyRequestMobileForm',
        'type'       => 'form',
        'name'       => 'user.password.verify_request',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPassword\\VerifyRequestForm',
        'type'       => 'form',
        'name'       => 'user.password.verify_request',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserProfileForm',
        'type'       => 'form',
        'name'       => 'user.profile',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserProfileMobileForm',
        'type'       => 'form',
        'name'       => 'user.profile',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserRegisterForm',
        'type'       => 'form',
        'name'       => 'user.register',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserRegisterMobileForm',
        'type'       => 'form',
        'name'       => 'user.register',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\SearchUserMobileForm',
        'type'       => 'form',
        'name'       => 'user.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\SearchUserForm',
        'type'       => 'form',
        'name'       => 'user.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\SmallUserLoginForm',
        'type'       => 'form',
        'name'       => 'user.small_login',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\AccountSettingForm',
        'type'       => 'form',
        'name'       => 'user.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\AccountInfoSettingForm',
        'type'       => 'form',
        'name'       => 'user.update.basic_info',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\AccountCustomFieldSettingForm',
        'type'       => 'form',
        'name'       => 'user.update.custom_fields',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\AccountNotificationSettingForm',
        'type'       => 'form',
        'name'       => 'user.update.notification',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\AccountPrivacySettingForm',
        'type'       => 'form',
        'name'       => 'user.update.privacy',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\SearchUserGenderForm',
        'type'       => 'form',
        'name'       => 'user.user_gender.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\StoreUserGenderForm',
        'type'       => 'form',
        'name'       => 'user.user_gender.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\UpdateUserGenderForm',
        'type'       => 'form',
        'name'       => 'user.user_gender.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPromotion\\Admin\\CreateForm',
        'type'       => 'form',
        'name'       => 'user.user_promotion.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPromotion\\Admin\\EditForm',
        'type'       => 'form',
        'name'       => 'user.user_promotion.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\CreateForm',
        'type'       => 'form',
        'name'       => 'user.user_relation.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\EditForm',
        'type'       => 'form',
        'name'       => 'user.user_relation.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\ResendEmailMobileForm',
        'type'       => 'form',
        'name'       => 'user_verify.resend',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\ResendPhoneNumberMobileForm',
        'type'       => 'form',
        'name'       => 'user_verify.resend_phone_number',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\VerifyEmailForm',
        'type'       => 'form',
        'name'       => 'user_verify.web.verify_email.home',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\VerifyEmailMobileForm',
        'type'       => 'form',
        'name'       => 'user_verify.web.verify_email.home',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\UpdateAccountVerifyEmailMobileForm',
        'type'       => 'form',
        'name'       => 'user_verify.web.verify_email.update_account',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\UpdateAccountVerifyEmailForm',
        'type'       => 'form',
        'name'       => 'user_verify.web.verify_email.update_account',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\VerifyPhoneNumberForm',
        'type'       => 'form',
        'name'       => 'user_verify.web.verify_phone_number.home',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\VerifyPhoneNumberMobileForm',
        'type'       => 'form',
        'name'       => 'user_verify.web.verify_phone_number.home',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\UpdateAccountVerifyPhoneNumberForm',
        'type'       => 'form',
        'name'       => 'user_verify.web.verify_phone_number.update_account',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\UpdateAccountVerifyPhoneNumberMobileForm',
        'type'       => 'form',
        'name'       => 'user_verify.web.verify_phone_number.update_account',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\User\\Form\\Html\\AvatarUploadField',
        'type'       => 'form-field',
        'name'       => 'avatarUpload',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form Field',
    ],
    [
        'driver'     => 'MetaFox\\User\\Form\\Mobile\\AvatarUploadField',
        'type'       => 'form-field',
        'name'       => 'avatarUpload',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form Field',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Admin\\UserSettingForm',
        'type'       => 'form-settings',
        'name'       => 'user',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'user::phrase.user_settings',
        'url'        => '/user/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Admin\\UserRegistrationSettingForm',
        'type'       => 'form-settings',
        'name'       => 'user.registration',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'user::phrase.registration_settings',
        'url'        => '/user/setting/registration',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Admin\\UserSecuritySettingForm',
        'type'       => 'form-settings',
        'name'       => 'user.security',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'user::phrase.security_settings',
        'url'        => '/user/setting/security',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\User\\Jobs\\DeletedRelationJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\User\\Jobs\\DeletedRelationJob',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\User\\Jobs\\ExpiredUserBanJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\User\\Jobs\\ExpiredUserBanJob',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserShortcut\\UserShortcutItemCollection',
        'type'       => 'json-collection',
        'name'       => 'shortcut.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'user.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\UserItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserPreviewCollection',
        'type'       => 'json-collection',
        'name'       => 'user.preview',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\BirthdayItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_birthday.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\UserBlockedEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'user_blocked.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\UserBlockedItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_blocked.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelFeedback\\Admin\\CancelFeedbackItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_cancel_feedback.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelReason\\Admin\\CancelReasonItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_cancel_reason.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserEntity\\UserEntityCollection',
        'type'       => 'json-collection',
        'name'       => 'user_entity.',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserEntity\\UserEntityItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_entity.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\UserGenderItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_gender.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPromotion\\Admin\\UserPromotionItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_promotion.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\UserRelationItemCollection',
        'type'       => 'json-collection',
        'name'       => 'user_relation.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\Account\\AccountSetting',
        'type'       => 'json-resource',
        'name'       => 'account.setting',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserShortcut\\UserShortcutDetail',
        'type'       => 'json-resource',
        'name'       => 'shortcut.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserShortcut\\UserShortcutItem',
        'type'       => 'json-resource',
        'name'       => 'shortcut.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserAccount',
        'type'       => 'json-resource',
        'name'       => 'user.account',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserActivity',
        'type'       => 'json-resource',
        'name'       => 'user.activity',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserActivityItem',
        'type'       => 'json-resource',
        'name'       => 'user.activity_item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserDetail',
        'type'       => 'json-resource',
        'name'       => 'user.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserEmbed',
        'type'       => 'json-resource',
        'name'       => 'user.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\UserExport',
        'type'       => 'json-resource',
        'name'       => 'user.export',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserInfo',
        'type'       => 'json-resource',
        'name'       => 'user.info',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserItem',
        'type'       => 'json-resource',
        'name'       => 'user.item',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserMe',
        'type'       => 'json-resource',
        'name'       => 'user.me',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserPreview',
        'type'       => 'json-resource',
        'name'       => 'user.preview',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserPropertiesSchema',
        'type'       => 'json-resource',
        'name'       => 'user.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\UserSimple',
        'type'       => 'json-resource',
        'name'       => 'user.simple',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\BirthdayItem',
        'type'       => 'json-resource',
        'name'       => 'user_birthday.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\UserBlockedDetail',
        'type'       => 'json-resource',
        'name'       => 'user_blocked.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\UserBlockedEmbed',
        'type'       => 'json-resource',
        'name'       => 'user_blocked.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\UserBlockedItem',
        'type'       => 'json-resource',
        'name'       => 'user_blocked.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelFeedback\\Admin\\CancelFeedbackDetail',
        'type'       => 'json-resource',
        'name'       => 'user_cancel_feedback.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelFeedback\\Admin\\CancelFeedbackItem',
        'type'       => 'json-resource',
        'name'       => 'user_cancel_feedback.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelReason\\Admin\\CancelReasonDetail',
        'type'       => 'json-resource',
        'name'       => 'user_cancel_reason.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\CancelReason\\Admin\\CancelReasonItem',
        'type'       => 'json-resource',
        'name'       => 'user_cancel_reason.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserEntity\\UserEntityDetail',
        'type'       => 'json-resource',
        'name'       => 'user_entity.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserEntity\\UserEntityItem',
        'type'       => 'json-resource',
        'name'       => 'user_entity.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserEntity\\UserEntityPreview',
        'type'       => 'json-resource',
        'name'       => 'user_entity.preview',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserGender\\Admin\\UserGenderItem',
        'type'       => 'json-resource',
        'name'       => 'user_gender.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserProfile\\UserProfileEmbed',
        'type'       => 'json-resource',
        'name'       => 'user_profile.embed',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPromotion\\Admin\\UserPromotionDetail',
        'type'       => 'json-resource',
        'name'       => 'user_promotion.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserPromotion\\Admin\\UserPromotionItem',
        'type'       => 'json-resource',
        'name'       => 'user_promotion.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\UserRelationDetail',
        'type'       => 'json-resource',
        'name'       => 'user_relation.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelation\\Admin\\UserRelationItem',
        'type'       => 'json-resource',
        'name'       => 'user_relation.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserRelationHistory\\UserRelationHistoryEmbed',
        'type'       => 'json-resource',
        'name'       => 'user_relation_history.embed',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\User\\Notifications\\ResetPasswordTokenNotification',
        'type'       => 'notification',
        'name'       => 'new_password_requested',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Notification',
    ],
    [
        'driver'     => 'MetaFox\\User\\Notifications\\DirectUpdatedPassword',
        'type'       => 'notification',
        'name'       => 'new_password_updated',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Notification',
    ],
    [
        'driver'     => 'MetaFox\\User\\Notifications\\NewPostTimeline',
        'type'       => 'notification',
        'name'       => 'new_post_timeline',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Notification',
    ],
    [
        'driver'     => 'MetaFox\\User\\Notifications\\ProfileUpdatedByAdmin',
        'type'       => 'notification',
        'name'       => 'profile_updated_by_admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Notification',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'user',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Policies\\UserPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\User\\Models\\User',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\User\\Policies\\UserProfilePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\User\\Models\\UserProfile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\User\\Policies\\UserRelationHistoryPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\User\\Models\\UserRelationHistory',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\User\\Policies\\UserShortcutPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\User\\Models\\UserShortcut',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'user',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Mobile Resource',
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'user_verify',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserShortcut\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'shortcut',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\User\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserBlocked\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user_blocked',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserInactive\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user_inactive',
        'version'    => 'v1',
        'resolution' => 'admin',
        'alias'      => 'inactive',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\ExportProcess\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user_export_process',
        'version'    => 'v1',
        'resolution' => 'admin',
        'alias'      => 'export_process',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\User\\Http\\Resources\\v1\\UserVerify\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'user_verify',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\User\\Support\\SEO\\UserSchema',
        'type'       => 'schema-structured',
        'name'       => 'user',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Support\\Verify\\Action\\Admin\\Email',
        'type'       => 'user_verify.action_service.admin',
        'name'       => 'verify_email',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Support\\Verify\\Action\\Admin\\PhoneNumber',
        'type'       => 'user_verify.action_service.admin',
        'name'       => 'verify_phone_number',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Support\\Verify\\Action\\Email',
        'type'       => 'user_verify.action_service.web',
        'name'       => 'verify_email',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\User\\Support\\Verify\\Action\\PhoneNumber',
        'type'       => 'user_verify.action_service.web',
        'name'       => 'verify_phone_number',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
