<?php

/* this is auto generated file */
return [
    [
        'subInfo'   => '',
        'menu'      => 'core.primaryMenu',
        'name'      => 'advertises',
        'label'     => 'advertise::phrase.advertise',
        'ordering'  => 2,
        'to'        => '/advertise',
        'is_active' => 0,
    ],
    [
        'tab'      => 'my',
        'menu'     => 'advertise.sidebarMenu',
        'name'     => 'my',
        'label'    => 'advertise::phrase.all_ads',
        'ordering' => 1,
        'to'       => '/advertise',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'advertise',
            'resource_name' => 'advertise',
        ],
        'value'    => 'viewAll',
    ],
    [
        'tab'      => 'invoice',
        'menu'     => 'advertise.sidebarMenu',
        'name'     => 'invoice',
        'label'    => 'advertise::phrase.invoices',
        'ordering' => 2,
        'to'       => '/advertise/invoice',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'advertise',
            'resource_name' => 'advertise_invoice',
        ],
        'value'    => 'viewAll',
    ],
    [
        'tab'      => 'sponsorship',
        'menu'     => 'advertise.sidebarMenu',
        'name'     => 'sponsorship',
        'label'    => 'advertise::phrase.sponsorships',
        'ordering' => 3,
        'to'       => '/advertise/sponsor',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'advertise',
            'resource_name' => 'advertise_sponsor',
        ],
        'value'    => 'viewAll',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_active'],
        ],
        'menu'     => 'advertise.advertise.itemActionMenu',
        'name'     => 'active',
        'label'    => 'advertise::phrase.activate',
        'ordering' => 1,
        'value'    => 'advertise/activeItem',
        'variant'  => 'contained',
        'color'    => 'primary',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_active'],
        ],
        'menu'     => 'advertise.advertise.itemActionMenu',
        'name'     => 'inactive',
        'label'    => 'advertise::phrase.deactivate',
        'ordering' => 1,
        'value'    => 'advertise/inactiveItem',
        'variant'  => 'contained',
        'color'    => 'primary',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_payment'],
        ],
        'menu'     => 'advertise.advertise.itemActionMenu',
        'name'     => 'payment',
        'label'    => 'advertise::web.pay_price_mobile',
        'ordering' => 2,
        'value'    => 'advertise/paymentItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'advertise.advertise.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'core::phrase.edit',
        'ordering' => 3,
        'value'    => 'editItem',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'advertise.advertise.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'core::phrase.delete',
        'ordering'  => 4,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_active'],
        ],
        'menu'     => 'advertise.advertise.detailActionMenu',
        'name'     => 'active',
        'label'    => 'advertise::phrase.activate',
        'ordering' => 1,
        'value'    => 'advertise/activeItem',
        'variant'  => 'contained',
        'color'    => 'primary',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_active'],
        ],
        'menu'     => 'advertise.advertise.detailActionMenu',
        'name'     => 'inactive',
        'label'    => 'advertise::phrase.deactivate',
        'ordering' => 1,
        'value'    => 'advertise/inactiveItem',
        'variant'  => 'contained',
        'color'    => 'primary',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_payment'],
        ],
        'menu'     => 'advertise.advertise.detailActionMenu',
        'name'     => 'payment',
        'label'    => 'advertise::web.pay_price_mobile',
        'ordering' => 2,
        'value'    => 'advertise/paymentItem',
        'variant'  => 'contained',
        'color'    => 'primary',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'advertise.advertise.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'core::phrase.edit',
        'ordering' => 3,
        'value'    => 'editItem',
        'variant'  => 'outlined',
        'color'    => 'primary',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'advertise.advertise.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'core::phrase.delete',
        'ordering'  => 4,
        'value'     => 'deleteItem',
        'variant'   => 'outlined',
        'color'     => 'error',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_payment'],
        ],
        'menu'     => 'advertise.advertise_invoice.itemActionMenu',
        'name'     => 'payment',
        'label'    => 'advertise::web.pay_now',
        'ordering' => 1,
        'value'    => 'advertise/paymentItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_cancel'],
        ],
        'menu'     => 'advertise.advertise_invoice.itemActionMenu',
        'name'     => 'cancel',
        'label'    => 'core::phrase.cancel',
        'ordering' => 2,
        'value'    => 'advertise/cancelItem',
    ],
    [
        'menu'      => 'core.helperMenu',
        'name'      => 'advertise',
        'label'     => 'advertise::phrase.advertise',
        'ordering'  => 2,
        'to'        => '/advertise',
        'iconColor' => '#686868',
        'as'        => 'helper',
        'icon'      => 'bell-alt',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_payment'],
        ],
        'menu'     => 'advertise.advertise_sponsor.itemActionMenu',
        'name'     => 'payment',
        'label'    => 'advertise::web.pay_price_mobile',
        'ordering' => 1,
        'value'    => 'advertise/paymentItem',
        'icon'     => 'credit-card',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_active'],
        ],
        'menu'     => 'advertise.advertise_sponsor.itemActionMenu',
        'name'     => 'active',
        'label'    => 'advertise::phrase.activate',
        'ordering' => 1,
        'value'    => 'advertise/activeItem',
        'variant'  => 'contained',
        'color'    => 'primary',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_active'],
        ],
        'menu'     => 'advertise.advertise_sponsor.itemActionMenu',
        'name'     => 'inactive',
        'label'    => 'advertise::phrase.deactivate',
        'ordering' => 1,
        'value'    => 'advertise/inactiveItem',
        'variant'  => 'contained',
        'color'    => 'primary',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'advertise.advertise_sponsor.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'core::phrase.edit',
        'ordering' => 2,
        'value'    => 'editItem',
        'icon'     => 'pencilline',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'advertise.advertise_sponsor.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'core::phrase.delete',
        'ordering'  => 3,
        'value'     => 'deleteItem',
        'icon'      => 'trash',
    ],
];
