<?php
/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'music.music_album',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Genre\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'music.genre',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Genre\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'music.genre.genre',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'music.music_playlist',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'music.music_song',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Models\\Album',
        'type'       => 'entity',
        'name'       => 'music_album',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Music Albums',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Models\\AlbumText',
        'type'       => 'entity',
        'name'       => 'music_album_text',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Music Albums',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Models\\Genre',
        'type'       => 'entity',
        'name'       => 'music_genre',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Music Genre',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Models\\GenreData',
        'type'       => 'entity',
        'name'       => 'music_genre_data',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Models\\Playlist',
        'type'       => 'entity',
        'name'       => 'music_playlist',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Music Playlists',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Models\\PlaylistData',
        'type'       => 'entity',
        'name'       => 'music_playlist_data',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Models\\Song',
        'type'       => 'entity',
        'name'       => 'music_song',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Music Songs',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Models\\Album',
        'type'       => 'entity-content',
        'name'       => 'music_album',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Music Albums',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Models\\Playlist',
        'type'       => 'entity-content',
        'name'       => 'music_playlist',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Music Playlists',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Models\\Song',
        'type'       => 'entity-content',
        'name'       => 'music_song',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Music Songs',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\UpdateAlbumMobileForm',
        'type'       => 'form',
        'name'       => 'music.music_album.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Genre\\Admin\\DestroyGenreForm',
        'type'       => 'form',
        'name'       => 'music.music_genre.destroy',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Genre\\Admin\\StoreGenreForm',
        'type'       => 'form',
        'name'       => 'music.music_genre.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Genre\\Admin\\UpdateGenreForm',
        'type'       => 'form',
        'name'       => 'music.music_genre.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\StorePlaylistMobileForm',
        'type'       => 'form',
        'name'       => 'music.music_playlist.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\UpdatePlaylistMobileForm',
        'type'       => 'form',
        'name'       => 'music.music_playlist.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\AddSongMobileForm',
        'type'       => 'form',
        'name'       => 'music.music_song.add_to_playlist',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\AddSongForm',
        'type'       => 'form',
        'name'       => 'music.music_song.add_to_playlist',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\StoreSongMobileForm',
        'type'       => 'form',
        'name'       => 'music.music_song.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\UpdateSongMobileForm',
        'type'       => 'form',
        'name'       => 'music.music_song.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\EditSelectingSongForm',
        'type'       => 'form',
        'name'       => 'music_song.edit_selecting',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Music\\SearchMusicForm',
        'type'       => 'form',
        'name'       => 'music.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\SearchMobileForm',
        'type'       => 'form',
        'name'       => 'music_album.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\Admin\\SearchAlbumForm',
        'type'       => 'form',
        'name'       => 'music_album.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\SearchInOwnerMobileForm',
        'type'       => 'form',
        'name'       => 'music_album.search_in_owner',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\StoreAlbumForm',
        'type'       => 'form',
        'name'       => 'music_album.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\UpdateAlbumForm',
        'type'       => 'form',
        'name'       => 'music_album.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\SearchMobileForm',
        'type'       => 'form',
        'name'       => 'music_playlist.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\Admin\\SearchPlaylistForm',
        'type'       => 'form',
        'name'       => 'music_playlist.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\StorePlaylistForm',
        'type'       => 'form',
        'name'       => 'music_playlist.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\UpdatePlaylistForm',
        'type'       => 'form',
        'name'       => 'music_playlist.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\SearchMobileForm',
        'type'       => 'form',
        'name'       => 'music_song.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\Admin\\SearchSongForm',
        'type'       => 'form',
        'name'       => 'music_song.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\SearchInOwnerMobileForm',
        'type'       => 'form',
        'name'       => 'music_song.search_in_owner',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\StoreSongForm',
        'type'       => 'form',
        'name'       => 'music_song.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\UpdateSongForm',
        'type'       => 'form',
        'name'       => 'music_song.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'music',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/music/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\AlbumEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'music_album.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\AlbumItemCollection',
        'type'       => 'json-collection',
        'name'       => 'music_album.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Genre\\GenreEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'music_genre.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Genre\\GenreItemCollection',
        'type'       => 'json-collection',
        'name'       => 'music_genre.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\PlaylistEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'music_playlist.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\PlaylistItemCollection',
        'type'       => 'json-collection',
        'name'       => 'music_playlist.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\SongEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'music_song.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\SongItemCollection',
        'type'       => 'json-collection',
        'name'       => 'music_song.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\AlbumDetail',
        'type'       => 'json-resource',
        'name'       => 'music_album.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\AlbumEmbed',
        'type'       => 'json-resource',
        'name'       => 'music_album.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\FeedEmbed',
        'type'       => 'json-resource',
        'name'       => 'music_album.feed_embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\AlbumItem',
        'type'       => 'json-resource',
        'name'       => 'music_album.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\AlbumPropertiesSchema',
        'type'       => 'json-resource',
        'name'       => 'music_album.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Genre\\GenreEmbed',
        'type'       => 'json-resource',
        'name'       => 'music_genre.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Genre\\GenreItem',
        'type'       => 'json-resource',
        'name'       => 'music_genre.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Platform\\Http\\Resources\\v1\\Category\\CategoryPropertiesSEO',
        'type'       => 'json-resource',
        'name'       => 'music_genre.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\PlaylistDetail',
        'type'       => 'json-resource',
        'name'       => 'music_playlist.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\PlaylistEmbed',
        'type'       => 'json-resource',
        'name'       => 'music_playlist.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\PlaylistItem',
        'type'       => 'json-resource',
        'name'       => 'music_playlist.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\PlaylistPropertiesSchema',
        'type'       => 'json-resource',
        'name'       => 'music_playlist.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\SongDetail',
        'type'       => 'json-resource',
        'name'       => 'music_song.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\SongEmbed',
        'type'       => 'json-resource',
        'name'       => 'music_song.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\FeedEmbed',
        'type'       => 'json-resource',
        'name'       => 'music_song.feed_embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\SongItem',
        'type'       => 'json-resource',
        'name'       => 'music_song.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\SongPropertiesSchema',
        'type'       => 'json-resource',
        'name'       => 'music_song.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Music\\MobileSetting',
        'type'       => 'package-mobile',
        'name'       => 'music',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'music',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Policies\\AlbumPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Music\\Models\\Album',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Policies\\GenrePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Music\\Models\\Genre',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Policies\\PlaylistPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Music\\Models\\Playlist',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Policies\\SongPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Music\\Models\\Song',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'music_album',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'music_playlist',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'music_song',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Music\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'music',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'music_album',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'music_playlist',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'music_song',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Album\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'music_album',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Playlist\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'music_playlist',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Http\\Resources\\v1\\Song\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'music_song',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Music\\Support\\SEO\\AlbumSchema',
        'type'       => 'schema-structured',
        'name'       => 'music_album',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Support\\SEO\\GenreSchema',
        'type'       => 'schema-structured',
        'name'       => 'music_genre',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Support\\SEO\\PlaylistSchema',
        'type'       => 'schema-structured',
        'name'       => 'music_playlist',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Support\\SEO\\SongSchema',
        'type'       => 'schema-structured',
        'name'       => 'music_song',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Music\\Support\\SEO\\SongSchema',
        'type'       => 'schema-structured',
        'name'       => 'songs',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
