<?php
/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'video',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Category\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'video.category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Category\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'video.category.category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\VideoService\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'video.service',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\VerifyProcess\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'video.verify_process',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Models\\Video',
        'type'       => 'entity',
        'name'       => 'video',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Videos',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Models\\VerifyProcess',
        'type'       => 'entity',
        'name'       => 'video_verify_process',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Verify Processes',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Models\\Category',
        'type'       => 'entity',
        'name'       => 'video_category',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Video Categories',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Models\\Video',
        'type'       => 'entity-content',
        'name'       => 'video',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Videos',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\ShareVideoComposerMobileForm',
        'type'       => 'form',
        'name'       => 'video.composer.share',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\ShareVideoComposerForm',
        'type'       => 'form',
        'name'       => 'video.composer.share',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\EditSelectingVideoForm',
        'type'       => 'form',
        'name'       => 'video.edit_selecting_video',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\EditSelectingVideoMobileForm',
        'type'       => 'form',
        'name'       => 'video.edit_selecting_video',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\CreateFeedForm',
        'type'       => 'form',
        'name'       => 'video.feed_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\SearchVideoMobileForm',
        'type'       => 'form',
        'name'       => 'video.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\Admin\\SearchVideoForm',
        'type'       => 'form',
        'name'       => 'video.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\SearchVideoForm',
        'type'       => 'form',
        'name'       => 'video.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\SearchInOwnerMobileForm',
        'type'       => 'form',
        'name'       => 'video.search_in_owner',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\ShareVideoForm',
        'type'       => 'form',
        'name'       => 'video.share',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\CreateVideoForm',
        'type'       => 'form',
        'name'       => 'video.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\EditVideoForm',
        'type'       => 'form',
        'name'       => 'video.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\ShareVideoMobileForm',
        'type'       => 'form',
        'name'       => 'video.video.share',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\UpdateVideoMobileForm',
        'type'       => 'form',
        'name'       => 'video.video.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\UploadVideoMobileForm',
        'type'       => 'form',
        'name'       => 'video.video.upload',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Category\\Admin\\DestroyCategoryForm',
        'type'       => 'form',
        'name'       => 'video.video_category.destroy',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Category\\Admin\\StoreCategoryForm',
        'type'       => 'form',
        'name'       => 'video.video_category.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Category\\Admin\\UpdateCategoryForm',
        'type'       => 'form',
        'name'       => 'video.video_category.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Form\\Mobile\\SingleVideoField',
        'type'       => 'form-field',
        'name'       => 'singleVideo',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form Field',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\Fields\\VideoUrlField',
        'type'       => 'form-field',
        'name'       => 'videoUrl',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form Field',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'video',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/video/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Jobs\\DeleteCategoryJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Video\\Jobs\\DeleteCategoryJob',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Jobs\\VideoProcessingJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Video\\Jobs\\VideoProcessingJob',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\VideoEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'video.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\VideoItemCollection',
        'type'       => 'json-collection',
        'name'       => 'video.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\VideoDetail',
        'type'       => 'json-resource',
        'name'       => 'video.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\VideoEmbed',
        'type'       => 'json-resource',
        'name'       => 'video.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\FeedEditEmbed',
        'type'       => 'json-resource',
        'name'       => 'video.feed_edit',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\FeedEmbed',
        'type'       => 'json-resource',
        'name'       => 'video.feed_embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\VideoItem',
        'type'       => 'json-resource',
        'name'       => 'video.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\VideoPropertiesSchema',
        'type'       => 'json-resource',
        'name'       => 'video.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Category\\CategoryDetail',
        'type'       => 'json-resource',
        'name'       => 'video_category.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Category\\CategoryItem',
        'type'       => 'json-resource',
        'name'       => 'video_category.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Platform\\Http\\Resources\\v1\\Category\\CategoryPropertiesSEO',
        'type'       => 'json-resource',
        'name'       => 'video_category.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Notifications\\VideoDoneProcessingNotification',
        'type'       => 'notification',
        'name'       => 'video_done_processing',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Notification',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'video',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Video\\Policies\\CategoryPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Video\\Models\\Category',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Policies\\VideoPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Video\\Models\\Video',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'video',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'video',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Video\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'video',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Http\\Resources\\v1\\Category\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'video_category',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Video\\Support\\SEO\\VideoSchema',
        'type'       => 'schema-structured',
        'name'       => 'video',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Platform\\Support\\SEO\\CategorySchema',
        'type'       => 'schema-structured',
        'name'       => 'video_category',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
