<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.video.browse_category',
        'phrase_title' => 'core::phrase.categories',
        'url'          => 'video/category/browse',
    ],
    [
        'name'                 => 'admin.video.browse_child_category',
        'phrase_title'         => 'core::phrase.categories',
        'url'                  => 'video/category/{id}/category/browse',
        'custom_sharing_route' => 1,
    ],
    [
        'name'         => 'admin.video.browse_service',
        'phrase_title' => 'video::phrase.browse_service',
        'url'          => 'video/service/browse',
    ],
    [
        'name'         => 'admin.video.browse_video',
        'phrase_title' => 'video::phrase.manage_videos',
        'url'          => 'video/video/browse',
    ],
    [
        'name'         => 'admin.video.browse_verify_process',
        'phrase_title' => 'video::phrase.manage_verify_process',
        'url'          => 'video/verify-process/browse',
    ],
    [
        'name'         => 'admin.video.create_category',
        'phrase_title' => 'core::phrase.add_category',
        'url'          => 'video/category/create',
    ],
    [
        'name'         => 'admin.video.edit_category',
        'phrase_title' => 'core::phrase.edit_category',
        'url'          => 'video/category/edit/{id}',
    ],
    [
        'name'         => 'admin.video.ffmpeg_setting',
        'phrase_title' => 'video::phrase.ffmpeg_setting',
        'url'          => 'video/setting/ffmpeg',
    ],
    [
        'name'         => 'admin.video.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'video/permission',
    ],
    [
        'name'         => 'admin.video.video_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'video/setting',
    ],
    [
        'name'               => 'group.profile.video',
        'phrase_title'       => 'video::seo.group_profile_video_title',
        'phrase_description' => 'video::seo.group_profile_video_description',
        'phrase_keywords'    => 'video::seo.group_profile_video_keywords',
        'phrase_heading'     => 'video::seo.group_profile_video_heading',
        'url'                => 'group/{id}/video',
        'item_type'          => 'group',
        'resource_name'      => 'group',
    ],
    [
        'name'               => 'page.profile.video',
        'phrase_title'       => 'video::seo.page_profile_video_title',
        'phrase_description' => 'video::seo.page_profile_video_description',
        'phrase_keywords'    => 'video::seo.page_profile_video_keywords',
        'phrase_heading'     => 'video::seo.page_profile_video_heading',
        'url'                => 'page/{id}/video',
        'item_type'          => 'page',
        'resource_name'      => 'page',
    ],
    [
        'name'               => 'user.profile.video',
        'phrase_title'       => 'video::seo.user_profile_video_title',
        'phrase_description' => 'video::seo.user_profile_video_desription',
        'phrase_keywords'    => 'video::seo.user_profile_video_keywords',
        'phrase_heading'     => 'video::seo.user_profile_video_heading',
        'url'                => 'user/{id}/video',
        'item_type'          => 'user',
        'resource_name'      => 'user',
    ],
    [
        'name'               => 'video.browse_all_video',
        'phrase_title'       => 'video::seo.video_browse_all_title',
        'phrase_description' => 'video::seo.video_browse_all_description',
        'phrase_keywords'    => 'video::seo.video_browse_all_keywords',
        'phrase_heading'     => 'video::seo.video_browse_all_heading',
        'url'                => 'video/all',
        'item_type'          => 'video',
    ],
    [
        'name'               => 'video.browse_friend_video',
        'phrase_title'       => 'video::seo.video_browse_friend_title',
        'phrase_description' => 'video::seo.video_browse_friend_description',
        'phrase_keywords'    => 'video::seo.video_browse_friend_keywords',
        'phrase_heading'     => 'video::seo.video_browse_friend_heading',
        'url'                => 'video/friend',
        'item_type'          => 'video',
    ],
    [
        'name'               => 'video.browse_my_pending_video',
        'phrase_title'       => 'video::seo.video_browse_my_pending_title',
        'phrase_description' => 'video::seo.video_browse_my_pending_description',
        'phrase_keywords'    => 'video::seo.video_browse_my_pending_keywords',
        'phrase_heading'     => 'video::seo.video_browse_my_pending_heading',
        'url'                => 'video/my-pending',
        'item_type'          => 'video',
    ],
    [
        'name'               => 'video.browse_pending_video',
        'phrase_title'       => 'video::seo.video_browse_pending_title',
        'phrase_description' => 'video::seo.video_browse_pending_description',
        'phrase_keywords'    => 'video::seo.video_browse_pending_keywords',
        'phrase_heading'     => 'video::seo.video_browse_pending_heading',
        'url'                => 'video/pending',
        'item_type'          => 'video',
    ],
    [
        'name'               => 'video.video',
        'phrase_title'       => 'video::seo.video_search_title',
        'phrase_description' => 'video::seo.video_search_description',
        'phrase_keywords'    => 'video::seo.video_search_keywords',
        'phrase_heading'     => 'video::seo.video_search_heading',
        'url'                => 'video/search',
        'item_type'          => 'video',
    ],
    [
        'name'                 => 'video.video.create',
        'phrase_title'         => 'video::seo.video_create_title',
        'phrase_description'   => 'video::seo.video_create_description',
        'phrase_keywords'      => 'video::seo.video_create_keywords',
        'phrase_heading'       => 'video::seo.video_create_heading',
        'url'                  => 'video/share',
        'item_type'            => 'video',
        'custom_sharing_route' => 1,
    ],
    [
        'name'                 => 'video.video.edit',
        'phrase_title'         => 'video::seo.video_edit_title',
        'phrase_description'   => 'video::seo.video_edit_description',
        'phrase_keywords'      => 'video::seo.video_edit_keywords',
        'phrase_heading'       => 'video::seo.video_edit_heading',
        'url'                  => 'video/edit/{id}',
        'item_type'            => 'video',
        'custom_sharing_route' => 1,
    ],
    [
        'name'               => 'video.video.landing',
        'phrase_title'       => 'video::seo.video_landing_title',
        'phrase_description' => 'video::seo.video_landing_description',
        'phrase_keywords'    => 'video::seo.video_landing_keywords',
        'phrase_heading'     => 'video::seo.video_landing_heading',
        'url'                => 'video',
        'item_type'          => 'video',
    ],
    [
        'name'               => 'video.video.my',
        'phrase_title'       => 'video::seo.video_browse_my_title',
        'phrase_description' => 'video::seo.video_browse_my_description',
        'phrase_keywords'    => 'video::seo.video_browse_my_keywords',
        'phrase_heading'     => 'video::seo.video_browse_my_heading',
        'url'                => 'video/my',
        'item_type'          => 'video',
    ],
    [
        'name'               => 'video.video.view_detail',
        'phrase_title'       => 'video::seo.video_view_detail_title',
        'phrase_description' => 'video::seo.video_view_detail_description',
        'phrase_keywords'    => 'video::seo.video_view_detail_keywords',
        'phrase_heading'     => 'video::seo.video_view_detail_heading',
        'url'                => 'video/play/{id}/{slug?}',
        'item_type'          => 'video',
        'resource_name'      => 'video',
    ],
    [
        'name'                 => 'video.video_album.view_item_preview',
        'phrase_title'         => 'video::seo.video_view_detail_title',
        'phrase_description'   => 'video::seo.video_view_detail_description',
        'phrase_keywords'      => 'video::seo.video_view_detail_keywords',
        'phrase_heading'       => 'video::seo.video_view_detail_heading',
        'url'                  => 'media/album/{albumId}/video/{id}/{slug?}',
        'item_type'            => 'video',
        'custom_sharing_route' => 1,
    ],
];
