<?php

/* this is auto generated file */
return [
    [
        'subInfo'  => 'poll::phrase.browse_polls_you_like_to_vote',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.polls',
        'ordering' => 11,
        'icon'     => 'ico-barchart',
        'to'       => '/poll',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.poll.poll.create'],
        ],
        'menu'     => 'core.quickCreateMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.poll',
        'ordering' => 10,
        'icon'     => 'ico-barchart',
        'to'       => '/poll/add',
    ],
    [
        'subInfo'  => 'poll::phrase.browse_polls_you_like_to_vote',
        'menu'     => 'core.primaryMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.polls',
        'ordering' => 11,
        'icon'     => 'ico-barchart',
        'to'       => '/poll',
    ],
    [
        'tab'      => 'poll',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.polls',
        'ordering' => 6,
        'to'       => '/poll',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.view'],
        ],
        'menu'     => 'group.searchWebCategoryMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.poll_global_search_label',
        'ordering' => 6,
    ],
    [
        'tab'      => 'poll',
        'showWhen' => [],
        'menu'     => 'page.page.profileMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.polls',
        'ordering' => 6,
        'to'       => '/poll',
    ],
    [
        'tab'      => 'poll',
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.create'],
            ['truthy', 'item.profile_settings.poll_share_polls'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.headerItemActionOnGroupProfileMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.add_new_poll',
        'ordering' => 1,
        'to'       => '/poll/add?owner_id=:id',
    ],
    [
        'tab'      => 'poll',
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.create'],
            ['truthy', 'item.profile_settings.poll_share_polls'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'poll.poll.headerItemActionOnPageProfileMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.add_new_poll',
        'ordering' => 1,
        'to'       => '/poll/add?owner_id=:id',
    ],
    [
        'tab'      => 'poll',
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'poll.poll.headerItemActionOnUserProfileMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.add_new_poll',
        'ordering' => 1,
        'to'       => '/poll/add?owner_id=:id',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'poll::phrase.edit_poll_title',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'poll::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'poll::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'poll::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'poll::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'poll::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'poll::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'poll.poll.itemActionMenu',
        'name'       => 'feature',
        'label'      => 'core::phrase.feature',
        'ordering'   => 7,
        'value'      => 'featureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 7,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'poll.poll.itemActionMenu',
        'name'       => 'unfeature',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 8,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'poll.poll.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'poll::phrase.approve',
        'ordering' => 11,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'poll.poll.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'poll::phrase.delete',
        'ordering'  => 12,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash-o',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'poll::phrase.home',
        'ordering' => 1,
        'icon'     => 'ico-barchart-o',
        'to'       => '/poll',
    ],
    [
        'tab'      => 'all',
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'all',
        'label'    => 'poll::phrase.all_polls',
        'ordering' => 2,
        'icon'     => 'ico-hashtag',
        'to'       => '/poll/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'my',
        'label'    => 'poll::phrase.my_polls',
        'ordering' => 3,
        'icon'     => 'ico-user-man-o',
        'to'       => '/poll/my',
    ],
    [
        'tab'      => 'my_pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'poll::phrase.my_pending_polls',
        'ordering' => 4,
        'icon'     => 'ico-user1-clock-o',
        'to'       => '/poll/my-pending',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'poll::phrase.friends_polls',
        'ordering' => 5,
        'icon'     => 'ico-user1-two-o',
        'to'       => '/poll/friend',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.poll.poll.approve'],
        ],
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'poll::phrase.pending_polls',
        'ordering' => 6,
        'icon'     => 'ico-clock-o',
        'to'       => '/poll/pending',
    ],
    [
        'tab'      => 'add',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.poll.poll.create'],
        ],
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'menu'     => 'poll.sidebarMenu',
        'name'     => 'add',
        'label'    => 'poll::phrase.add_new_poll',
        'ordering' => 7,
        'as'       => 'sidebarButton',
        'icon'     => 'ico-plus',
        'to'       => '/poll/add',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.poll_global_search_label',
        'ordering' => 11,
        'to'       => '/search/poll',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.poll_global_search_label',
        'ordering' => 9,
    ],
    [
        'tab'      => 'poll',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.poll'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.polls',
        'ordering' => 10,
        'to'       => '/poll',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.poll.poll.view'],
        ],
        'menu'     => 'search.webHashtagCategoryMenu',
        'name'     => 'poll',
        'label'    => 'poll::phrase.poll_global_search_label',
        'ordering' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'poll::phrase.edit_poll_title',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'poll::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'poll::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'poll::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'poll::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'poll::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'poll::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'poll.poll.detailActionMenu',
        'name'       => 'feature',
        'label'      => 'core::phrase.feature',
        'ordering'   => 7,
        'value'      => 'featureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 7,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'poll.poll.detailActionMenu',
        'name'       => 'unfeature',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 8,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => true,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
        ],
        'menu'     => 'poll.poll.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'poll.poll.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'poll::phrase.delete',
        'ordering'  => 12,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash-o',
    ],
];
