<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'app-settings',
        'name'        => 'notification',
        'label'       => 'notification::phrase.notification',
        'ordering'    => 17,
        'to'          => '/notification/type/browse',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'notification.admin',
        'name'     => 'channels',
        'label'    => 'core::phrase.channels',
        'ordering' => 0,
        'to'       => '/notification/channel/browse',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'notification.admin',
        'name'     => 'modules',
        'label'    => 'core::phrase.apps',
        'ordering' => 5,
        'to'       => '/notification/module/browse',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'      => 'notification.admin',
        'name'      => 'settings',
        'label'     => 'notification::phrase.settings',
        'ordering'  => 10,
        'to'        => '/notification/setting',
        'is_active' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'notification.admin',
        'name'     => 'types',
        'label'    => 'notification::phrase.types',
        'ordering' => 15,
        'to'       => '/notification/type/browse',
    ],
    [
        'menu'     => 'notification.notificationSettingsMenu',
        'name'     => 'mark_all_as_read',
        'label'    => 'notification::phrase.mark_all_as_read',
        'ordering' => 1,
        'value'    => 'notification/markAllAsRead',
        'icon'     => 'ico-check',
    ],
    [
        'menu'     => 'notification.notificationSettingsMenu',
        'name'     => 'delete_all_notification',
        'label'    => 'notification::phrase.delete_all_notifications',
        'ordering' => 2,
        'value'    => 'notification/deleteAll',
        'icon'     => 'ico-trash',
    ],
    [
        'target'   => '_blank',
        'menu'     => 'notification.notificationSettingsMenu',
        'name'     => 'edit_notification_setting',
        'label'    => 'notification::phrase.notification_settings',
        'ordering' => 3,
        'to'       => '/settings/notifications',
        'icon'     => 'ico-gear-o',
    ],
    [
        'menu'     => 'notification.notificationSettingsMenu',
        'name'     => 'browse_notifications',
        'label'    => 'notification::phrase.open_notifications',
        'ordering' => 4,
        'to'       => '/notification',
        'target'   => '_blank',
        'icon'     => 'ico-wallet-o',
    ],
    [
        'menu'     => 'notification.notification.itemActionMenu',
        'name'     => 'mark_read',
        'label'    => 'notification::phrase.mark_as_read',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_read'],
        ],
        'ordering' => 1,
        'value'    => 'notification/markAsRead',
        'icon'     => 'ico-check',
    ],
    [
        'menu'     => 'notification.notification.itemActionMenu',
        'name'     => 'mark_unread',
        'label'    => 'notification::phrase.mark_as_unread',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_read'],
        ],
        'ordering' => 1,
        'value'    => 'notification/markAsUnread',
        'icon'     => 'ico-check',
    ],
    [
        'className' => 'itemDelete',
        'menu'      => 'notification.notification.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'notification::phrase.remove_this_notification',
        'ordering'  => 2,
        'value'     => 'notification/deleteItem',
        'icon'      => 'ico-trash-o',
    ],
];
