<?php

/* this is auto generated file */
return [
    [
        'menu'     => 'notification.mobile_menu_more',
        'name'     => 'mark_all_as_read',
        'label'    => 'notification::phrase.mark_all_as_read',
        'ordering' => 1,
        'value'    => '@notification/markAllRead',
    ],
    [
        'style'    => 'danger',
        'menu'     => 'notification.mobile_menu_more',
        'name'     => 'delete_all_notification',
        'label'    => 'notification::phrase.delete_all_notifications',
        'ordering' => 2,
        'value'    => '@notification/deleteAllNotifications',
    ],
    [
        'menu'     => 'notification.notification.detailActionMenu',
        'name'     => 'mark_read',
        'label'    => 'notification::phrase.mark_as_read',
        'ordering' => 1,
        'value'    => 'notification/markAsRead',
    ],
    [
        'className' => 'itemDelete',
        'menu'      => 'notification.notification.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'notification::phrase.delete',
        'ordering'  => 2,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_read'],
        ],
        'menu'     => 'notification.notification.itemActionMenu',
        'name'     => 'mark_read',
        'label'    => 'notification::phrase.mark_as_read',
        'ordering' => 1,
        'value'    => 'notification/markAsRead',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_read'],
        ],
        'menu'     => 'notification.notification.itemActionMenu',
        'name'     => 'mark_unread',
        'label'    => 'notification::phrase.mark_as_unread',
        'ordering' => 1,
        'value'    => 'notification/markAsUnread',
    ],
    [
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'notification.notification.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'notification::phrase.delete',
        'ordering'  => 2,
        'value'     => 'deleteItem',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'email_notifications',
        'label'    => 'notification::phrase.email_notifications',
        'ordering' => 12,
        'to'       => '/settings/emailNotifications',
        'showWhen' => [
            'and',
            ['includes', 'setting.notification.channels', 'mail'],
            ['truthy', 'setting.mail.mail_service_is_ready'],
        ],
        'icon'      => 'bell2-o',
        'iconColor' => '#17A2B8',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'notifications',
        'label'    => 'notification::phrase.in_app_notifications',
        'ordering' => 13,
        'to'       => '/settings/inAppNotifications',
        'showWhen' => [
            'and',
            ['includes', 'setting.notification.channels', 'database'],
        ],
        'icon'      => 'mobile-o',
        'iconColor' => '#17A2B8',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'sms_notifications',
        'label'    => 'notification::phrase.sms_notifications',
        'ordering' => 14,
        'to'       => '/settings/smsNotifications',
        'showWhen' => [
            'and',
            ['includes', 'setting.notification.channels', 'sms'],
            ['truthy', 'setting.sms.sms_service_is_ready'],
        ],
        'icon'      => 'mobile-o',
        'iconColor' => '#17A2B8',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'webpush_notifications',
        'label'    => 'notification::phrase.webpush_notifications',
        'ordering' => 15,
        'to'       => '/settings/notifications/webpush',
        'showWhen' => [
            'and',
            ['includes', 'setting.notification.channels_ready', 'webpush'],
            ['gte', 'apiVersion', 'v1.16'],
        ],
        'icon'      => 'mobile-o',
        'iconColor' => '#17A2B8',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'mobilepush_notifications',
        'label'    => 'notification::phrase.mobilepush_notifications',
        'ordering' => 16,
        'to'       => '/settings/notifications/mobilepush',
        'showWhen' => [
            'and',
            ['includes', 'setting.notification.channels_ready', 'mobilepush'],
            ['gte', 'apiVersion', 'v1.16'],
        ],
        'icon'      => 'mobile-o',
        'iconColor' => '#17A2B8',
    ],
];
