<?php

/* this is auto generated file */
return [
    [
        'placement' => 'bottom',
        'content'   => [
            'component' => 'notification.ui.notificationPopper',
        ],
        'menu'      => 'core.headerSubMenu',
        'name'      => 'new_notification',
        'label'     => 'notification::phrase.notifications',
        'ordering'  => 4,
        'as'        => 'popover',
        'icon'      => 'ico-bell2-o',
        'to'        => '/notification',
    ],
    [
        'menu'     => 'notification.notification.detailActionMenu',
        'name'     => 'mark_read',
        'label'    => 'notification::phrase.mark_as_read',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_read'],
        ],
        'ordering' => 1,
        'value'    => 'notification/markAsRead',
        'icon'     => 'ico-check',
    ],
    [
        'className' => 'itemDelete',
        'menu'      => 'notification.notification.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'notification::phrase.delete',
        'ordering'  => 2,
        'value'     => 'notification/deleteItem',
        'icon'      => 'ico-trash-o',
    ],
    [
        'menu'     => 'notification.notification.itemActionMenu',
        'name'     => 'mark_read',
        'label'    => 'notification::phrase.mark_as_read',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_read'],
        ],
        'ordering' => 1,
        'value'    => 'notification/markAsRead',
        'icon'     => 'ico-check',
    ],
    [
        'menu'     => 'notification.notification.itemActionMenu',
        'name'     => 'mark_unread',
        'label'    => 'notification::phrase.mark_as_unread',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_read'],
        ],
        'ordering' => 1,
        'value'    => 'notification/markAsUnread',
        'icon'     => 'ico-check',
    ],
    [
        'className' => 'itemDelete',
        'menu'      => 'notification.notification.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'notification::phrase.remove_this_notification',
        'ordering'  => 2,
        'value'     => 'notification/deleteItem',
        'icon'      => 'ico-trash-o',
    ],
    [
        'menu'     => 'notification.notificationSettingsMenu',
        'name'     => 'mark_all_as_read',
        'label'    => 'notification::phrase.mark_all_as_read',
        'ordering' => 1,
        'value'    => 'notification/markAllAsRead',
        'icon'     => 'ico-check',
    ],
    [
        'menu'     => 'notification.notificationSettingsMenu',
        'name'     => 'delete_all_notification',
        'label'    => 'notification::phrase.delete_all_notifications',
        'ordering' => 2,
        'value'    => 'notification/deleteAll',
        'icon'     => 'ico-trash-o',
    ],
    [
        'menu'     => 'notification.notificationSettingsMenu',
        'name'     => 'edit_notification_setting',
        'label'    => 'notification::phrase.notification_settings',
        'ordering' => 3,
        'value'    => 'notification/editNotificationSetting',
        'icon'     => 'ico-gear-o',
    ],
    [
        'menu'     => 'notification.notificationSettingsMenu',
        'name'     => 'browse_notifications',
        'label'    => 'notification::phrase.open_notifications',
        'ordering' => 4,
        'value'    => 'notification/browseNotifications',
        'icon'     => 'ico-wallet-o',
    ],
    [
        'tab'      => 'email-notifications',
        'menu'     => 'user.settingMenu',
        'name'     => 'email_notifications',
        'label'    => 'notification::phrase.email_notifications',
        'ordering' => 9,
        'to'       => '/settings/email-notifications',
        'showWhen' => [
            'and',
            ['includes', 'setting.notification.channels', 'mail'],
            ['truthy', 'setting.mail.mail_service_is_ready'],
        ],
    ],
    [
        'tab'      => 'notifications',
        'menu'     => 'user.settingMenu',
        'name'     => 'notifications',
        'label'    => 'notification::phrase.in_app_notifications',
        'ordering' => 10,
        'to'       => '/settings/notifications',
        'showWhen' => [
            'and',
            ['includes', 'setting.notification.channels', 'database'],
        ],
    ],
    [
        'tab'      => 'sms-notifications',
        'menu'     => 'user.settingMenu',
        'name'     => 'sms_notifications',
        'label'    => 'notification::phrase.sms_notifications',
        'ordering' => 11,
        'to'       => '/settings/sms-notifications',
        'showWhen' => [
            'and',
            ['includes', 'setting.notification.channels', 'sms'],
            ['truthy', 'setting.sms.sms_service_is_ready'],
        ],
    ],
    [
        'tab'      => 'webpush-notifications',
        'menu'     => 'user.settingMenu',
        'name'     => 'webpush_notifications',
        'label'    => 'notification::phrase.webpush_notifications',
        'ordering' => 12,
        'to'       => '/settings/notifications/webpush',
        'showWhen' => [
            'and',
            ['includes', 'setting.notification.channels_ready', 'webpush'],
        ],
    ],
    [
        'tab'      => 'mobilepush-notifications',
        'menu'     => 'user.settingMenu',
        'name'     => 'mobilepush_notifications',
        'label'    => 'notification::phrase.mobilepush_notifications',
        'ordering' => 13,
        'to'       => '/settings/notifications/mobilepush',
        'showWhen' => [
            'and',
            ['includes', 'setting.notification.channels_ready', 'mobilepush'],
        ],
    ],
];
