<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Type\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'activity.type',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\Post',
        'type'       => 'entity',
        'name'       => 'activity_post',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\PrivacyMember',
        'type'       => 'entity',
        'name'       => 'activity_privacy_member',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\Snooze',
        'type'       => 'entity',
        'name'       => 'activity_snooze',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\Hidden',
        'type'       => 'entity',
        'name'       => 'activity_hidden',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\Stream',
        'type'       => 'entity',
        'name'       => 'activity_stream',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\Subscription',
        'type'       => 'entity',
        'name'       => 'activity_subscription',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\Feed',
        'type'       => 'entity',
        'name'       => 'feed',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Feeds',
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\ActivitySchedule',
        'type'       => 'entity',
        'name'       => 'activity_schedule',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\Share',
        'type'       => 'entity',
        'name'       => 'share',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\Post',
        'type'       => 'entity-content',
        'name'       => 'activity_post',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Posts',
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\Feed',
        'type'       => 'entity-content',
        'name'       => 'feed',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Feeds',
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Models\\Share',
        'type'       => 'entity-content',
        'name'       => 'share',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Shares',
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Post\\CreateFeedForm',
        'type'       => 'form',
        'name'       => 'activity_post.feed_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\BlockAuthorForm',
        'type'       => 'form',
        'name'       => 'activity.block_author_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\BlockAuthorMobileForm',
        'type'       => 'form',
        'name'       => 'activity.block_author_form',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Type\\Admin\\UpdateTypeForm',
        'type'       => 'form',
        'name'       => 'activity.type.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Share\\FeedShareForm',
        'type'       => 'form',
        'name'       => 'share.feed_form',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'activity',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/activity/setting',
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Jobs\\ExpiredSnoozeJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Activity\\Jobs\\ExpiredSnoozeJob',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Snooze\\SnoozeItemCollection',
        'type'       => 'json-collection',
        'name'       => 'activity_snooze.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\FeedEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'feed.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\FeedItemCollection',
        'type'       => 'json-collection',
        'name'       => 'feed.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Share\\ShareEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'share.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Type\\Admin\\TypeItemCollection',
        'type'       => 'json-collection',
        'name'       => 'type.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => '',
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Snooze\\SnoozeDetail',
        'type'       => 'json-resource',
        'name'       => 'activity_snooze.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Snooze\\SnoozeItem',
        'type'       => 'json-resource',
        'name'       => 'activity_snooze.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\FeedDetail',
        'type'       => 'json-resource',
        'name'       => 'feed.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\FeedEmbed',
        'type'       => 'json-resource',
        'name'       => 'feed.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\FeedForEdit',
        'type'       => 'json-resource',
        'name'       => 'feed.for_edit',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\FeedItem',
        'type'       => 'json-resource',
        'name'       => 'feed.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Share\\ShareEmbed',
        'type'       => 'json-resource',
        'name'       => 'share.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Type\\Admin\\TypeDetail',
        'type'       => 'json-resource',
        'name'       => 'type.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => '',
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Type\\Admin\\TypeItem',
        'type'       => 'json-resource',
        'name'       => 'type.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => '',
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Notifications\\ApproveFeedNotification',
        'type'       => 'notification',
        'name'       => 'activity_feed_approved',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'activity',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Policies\\FeedPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Activity\\Models\\Feed',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Policies\\PostPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Activity\\Models\\Post',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Policies\\SharePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Activity\\Models\\Share',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Policies\\SnoozePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Activity\\Models\\Snooze',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Policies\\TypePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Activity\\Models\\Type',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Policies\\Handlers\\CanShare',
        'type'       => 'policy-rule',
        'name'       => 'share',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'feed',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\ActivityHistory\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'feed_history',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'feed',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Snooze\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'activity_snooze',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Snooze\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'activity_snooze',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\ActivityHistory\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'feed_history',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Type\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'type',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => '',
    ],
    [
        'driver'     => 'MetaFox\Activity\Http\Resources\v1\Post\PostEmbed',
        'type'       => 'json-resource',
        'name'       => 'activity_post.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'is_deleted' => true,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\ActivitySchedule\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'activity_schedule',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\ActivitySchedule\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'activity_schedule',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'activity.feed',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\SortFeedForm',
        'type'       => 'form',
        'name'       => 'feed.sort',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Snooze\\SearchSnoozeMobileForm',
        'type'       => 'form',
        'name'       => 'activity_snooze.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Snooze\\SearchSnoozeForm',
        'type'       => 'form',
        'name'       => 'activity_snooze.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Activity\\Http\\Resources\\v1\\Feed\\FeedPropertiesSchema',
        'type'       => 'json-resource',
        'name'       => 'feed.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
];
