<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.poll.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'poll/permission',
    ],
    [
        'name'         => 'admin.poll.poll_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'poll/setting',
    ],
    [
        'name'         => 'admin.poll.manage_polls',
        'phrase_title' => 'poll::phrase.manage_polls',
        'url'          => 'poll/poll/browse',
    ],
    [
        'name'               => 'group.profile.poll',
        'phrase_title'       => 'poll::seo.group_profile_poll_title',
        'phrase_description' => 'poll::seo.group_profile_poll_description',
        'phrase_keywords'    => 'poll::seo.group_profile_poll_keywords',
        'phrase_heading'     => 'poll::seo.group_profile_poll_heading',
        'url'                => 'group/{id}/poll',
        'item_type'          => 'group',
        'resource_name'      => 'group',
    ],
    [
        'name'               => 'page.profile.poll',
        'phrase_title'       => 'poll::seo.page_profile_poll_title',
        'phrase_description' => 'poll::seo.page_profile_poll_description',
        'phrase_keywords'    => 'poll::seo.page_profile_poll_keywords',
        'phrase_heading'     => 'poll::seo.page_profile_poll_heading',
        'url'                => 'page/{id}/poll',
        'item_type'          => 'page',
        'resource_name'      => 'page',
    ],
    [
        'name'               => 'poll.browse_all_poll',
        'phrase_title'       => 'poll::seo.poll_browse_all_title',
        'phrase_description' => 'poll::seo.poll_browse_all_description',
        'phrase_keywords'    => 'poll::seo.poll_browse_all_keywords',
        'phrase_heading'     => 'poll::seo.poll_browse_all_heading',
        'url'                => 'poll/all',
        'item_type'          => 'poll',
    ],
    [
        'name'               => 'poll.browse_friend_poll',
        'phrase_title'       => 'poll::seo.poll_browse_friend_title',
        'phrase_description' => 'poll::seo.poll_browse_friend_description',
        'phrase_keywords'    => 'poll::seo.poll_browse_friend_keywords',
        'phrase_heading'     => 'poll::seo.poll_browse_friend_heading',
        'url'                => 'poll/friend',
        'item_type'          => 'poll',
    ],
    [
        'name'               => 'poll.browse_my_pending_poll',
        'phrase_title'       => 'poll::seo.poll_browse_my_pending_title',
        'phrase_description' => 'poll::seo.poll_browse_my_pending_description',
        'phrase_keywords'    => 'poll::seo.poll_browse_my_pending_keywords',
        'phrase_heading'     => 'poll::seo.poll_browse_my_pending_heading',
        'url'                => 'poll/my-pending',
        'item_type'          => 'poll',
    ],
    [
        'name'               => 'poll.browse_pending_poll',
        'phrase_title'       => 'poll::seo.poll_browse_pending_title',
        'phrase_description' => 'poll::seo.poll_browse_pending_description',
        'phrase_keywords'    => 'poll::seo.poll_browse_pending_keywords',
        'phrase_heading'     => 'poll::seo.poll_browse_pending_heading',
        'url'                => 'poll/pending',
        'item_type'          => 'poll',
    ],
    [
        'name'               => 'poll.poll',
        'phrase_title'       => 'poll::seo.poll_search_title',
        'phrase_description' => 'poll::seo.poll_search_description',
        'phrase_keywords'    => 'poll::seo.poll_search_keywords',
        'phrase_heading'     => 'poll::seo.poll_search_heading',
        'url'                => 'poll/search',
        'item_type'          => 'poll',
    ],
    [
        'name'                 => 'poll.poll.create',
        'phrase_title'         => 'poll::seo.poll_create_title',
        'phrase_description'   => 'poll::seo.poll_create_description',
        'phrase_keywords'      => 'poll::seo.poll_create_keywords',
        'phrase_heading'       => 'poll::seo.poll_create_heading',
        'url'                  => 'poll/add',
        'item_type'            => 'poll',
        'custom_sharing_route' => 1,
    ],
    [
        'name'                 => 'poll.poll.edit',
        'phrase_title'         => 'poll::seo.poll_edit_title',
        'phrase_description'   => 'poll::seo.poll_edit_description',
        'phrase_keywords'      => 'poll::seo.poll_edit_keywords',
        'phrase_heading'       => 'poll::seo.poll_edit_heading',
        'url'                  => 'poll/edit/{id}',
        'item_type'            => 'poll',
        'custom_sharing_route' => 1,
    ],
    [
        'name'               => 'poll.poll.landing',
        'phrase_title'       => 'poll::seo.poll_landing_title',
        'phrase_description' => 'poll::seo.poll_landing_description',
        'phrase_keywords'    => 'poll::seo.poll_landing_keywords',
        'phrase_heading'     => 'poll::seo.poll_landing_heading',
        'url'                => 'poll',
        'item_type'          => 'poll',
    ],
    [
        'name'               => 'poll.poll.my',
        'phrase_title'       => 'poll::seo.poll_browse_my_title',
        'phrase_description' => 'poll::seo.poll_browse_my_description',
        'phrase_keywords'    => 'poll::seo.poll_browse_my_keywords',
        'phrase_heading'     => 'poll::seo.poll_browse_my_heading',
        'url'                => 'poll/my',
        'item_type'          => 'poll',
    ],
    [
        'name'               => 'poll.poll.view_detail',
        'phrase_title'       => 'poll::seo.poll_view_detail_title',
        'phrase_description' => 'poll::seo.poll_view_detail_description',
        'phrase_keywords'    => 'poll::seo.poll_view_detail_keywords',
        'phrase_heading'     => 'poll::seo.poll_view_detail_heading',
        'url'                => 'poll/{id}/{slug?}',
        'item_type'          => 'poll',
        'resource_name'      => 'poll',
    ],
    [
        'name'               => 'user.profile.poll',
        'phrase_title'       => 'poll::seo.user_profile_poll_title',
        'phrase_description' => 'poll::seo.user_profile_poll_desription',
        'phrase_keywords'    => 'poll::seo.user_profile_poll_keywords',
        'phrase_heading'     => 'poll::seo.user_profile_poll_heading',
        'url'                => 'user/{id}/poll',
        'item_type'          => 'user',
        'resource_name'      => 'user',
    ],
];
