<?php
/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Reaction\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'like.reaction',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Models\\Like',
        'type'       => 'entity',
        'name'       => 'like',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Models\\LikeAgg',
        'type'       => 'entity',
        'name'       => 'like_aggregation',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Models\\Reaction',
        'type'       => 'entity',
        'name'       => 'like_reaction',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Models\\Reaction',
        'type'       => 'entity',
        'name'       => 'preaction',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'like',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/like/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Like\\LikeEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'like.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Like\\LikeItemCollection',
        'type'       => 'json-collection',
        'name'       => 'like.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Reaction\\ReactionEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'preaction.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Reaction\\ReactionItemCollection',
        'type'       => 'json-collection',
        'name'       => 'preaction.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Like\\LikeDetail',
        'type'       => 'json-resource',
        'name'       => 'like.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Like\\LikeEmbed',
        'type'       => 'json-resource',
        'name'       => 'like.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Like\\LikeItem',
        'type'       => 'json-resource',
        'name'       => 'like.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Reaction\\ReactionDetail',
        'type'       => 'json-resource',
        'name'       => 'preaction.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Reaction\\ReactionEmbed',
        'type'       => 'json-resource',
        'name'       => 'preaction.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Reaction\\ReactionItem',
        'type'       => 'json-resource',
        'name'       => 'preaction.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Notifications\\LikeNotification',
        'type'       => 'notification',
        'name'       => 'like_notification',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Notification',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'like',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Like\\Policies\\LikePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Like\\Models\\Like',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Policies\\ReactionPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Like\\Models\\Reaction',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Policies\\Handlers\\CanLike',
        'type'       => 'policy-rule',
        'name'       => 'like',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
    [
        'driver'     => 'MetaFox\\Like\\Http\\Resources\\v1\\Like\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'like',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
];
