<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Ban\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'ban',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Ban\\Http\\Resources\\v1\\BanRule\\Admin\\Email\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'ban.email',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Ban\\Http\\Resources\\v1\\BanRule\\Admin\\IPAddress\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'ban.ip',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Ban\\Http\\Resources\\v1\\BanRule\\Admin\\Word\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'ban.word',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Ban\\TypeHandlers\\EmailHandler',
        'type'       => \MetaFox\Ban\Supports\Constants::BAN_RULE_TYPE_DRIVER_TYPE,
        'name'       => \MetaFox\Ban\Supports\Constants::BAN_EMAIL_TYPE,
        'version'    => 'v1',
        'resolution' => \MetaFox\Platform\MetaFoxConstant::RESOLUTION_WEB,
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Type Handler',
    ],
    [
        'driver'     => 'MetaFox\\Ban\\TypeHandlers\\IPAddressHandler',
        'type'       => \MetaFox\Ban\Supports\Constants::BAN_RULE_TYPE_DRIVER_TYPE,
        'name'       => \MetaFox\Ban\Supports\Constants::BAN_IP_ADDRESS_TYPE,
        'version'    => 'v1',
        'resolution' => \MetaFox\Platform\MetaFoxConstant::RESOLUTION_WEB,
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Type Handler',
    ],
    [
        'driver'     => 'MetaFox\\Ban\\TypeHandlers\\WordHandler',
        'type'       => \MetaFox\Ban\Supports\Constants::BAN_RULE_TYPE_DRIVER_TYPE,
        'name'       => \MetaFox\Ban\Supports\Constants::BAN_WORD_TYPE,
        'version'    => 'v1',
        'resolution' => \MetaFox\Platform\MetaFoxConstant::RESOLUTION_WEB,
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Type Handler',
    ],
];
