// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ45FatclTAFkf8m8J-LgHFStyiaPuP4c',
    appId: '1:117453057789:web:ac9bd3d9594a8992a71894',
    messagingSenderId: '117453057789',
    projectId: 'lloyalty-application',
    authDomain: 'lloyalty-application.firebaseapp.com',
    storageBucket: 'lloyalty-application.firebasestorage.app',
    measurementId: 'G-54VC83N2PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYMzYkBPm5-Xy153PNWe-JrWqjr93z7b8',
    appId: '1:117453057789:android:074aa20f750ab5b9a71894',
    messagingSenderId: '117453057789',
    projectId: 'lloyalty-application',
    storageBucket: 'lloyalty-application.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPyEIUPpXvTKNHZJokBfJnDBPl6fI8Md0',
    appId: '1:117453057789:ios:2361836cdb863ccda71894',
    messagingSenderId: '117453057789',
    projectId: 'lloyalty-application',
    storageBucket: 'lloyalty-application.firebasestorage.app',
    iosBundleId: 'com.example.loyaltyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPyEIUPpXvTKNHZJokBfJnDBPl6fI8Md0',
    appId: '1:117453057789:ios:2361836cdb863ccda71894',
    messagingSenderId: '117453057789',
    projectId: 'lloyalty-application',
    storageBucket: 'lloyalty-application.firebasestorage.app',
    iosBundleId: 'com.example.loyaltyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ45FatclTAFkf8m8J-LgHFStyiaPuP4c',
    appId: '1:117453057789:web:3bc67cfc4e3ce907a71894',
    messagingSenderId: '117453057789',
    projectId: 'lloyalty-application',
    authDomain: 'lloyalty-application.firebaseapp.com',
    storageBucket: 'lloyalty-application.firebasestorage.app',
    measurementId: 'G-X7TQCRDSPQ',
  );
}
