// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNY9LhjqXF3j7oPJCNOU5We2_ftKAbj5M',
    appId: '1:661244516021:web:081745dbb8c8daeb9950fc',
    messagingSenderId: '661244516021',
    projectId: 'angelopoulos--hair',
    authDomain: 'angelopoulos--hair.firebaseapp.com',
    storageBucket: 'angelopoulos--hair.firebasestorage.app',
    measurementId: 'G-09SECP810C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD8QqAK_K5tzm-4awmBOvtEj_lHWlCplc',
    appId: '1:661244516021:android:2a87d837946b425f9950fc',
    messagingSenderId: '661244516021',
    projectId: 'angelopoulos--hair',
    storageBucket: 'angelopoulos--hair.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcJNHcg6vJpFYQII6HMm6-ae1qad8_jt8',
    appId: '1:661244516021:ios:dcb8fd7416da3fd29950fc',
    messagingSenderId: '661244516021',
    projectId: 'angelopoulos--hair',
    storageBucket: 'angelopoulos--hair.firebasestorage.app',
    iosBundleId: 'com.angelopouloshair.app',
  );
}
