<?php

/* this is auto generated file */
return [
    [
        'description' => 'Say something about this photo...',
        'post_type'   => 'photo',
        'icon_color'  => '#48c260',
        'menu'        => 'event.event.feedComposerMenu',
        'name'        => 'compose_photo',
        'label'       => 'photo::phrase.media_label_saved',
        'ordering'    => 4,
        'as'          => 'post.photo',
        'value'       => 'photo_set',
        'icon'        => 'photos',
        'to'          => '2',
        'showWhen'    => [
            'and',
            [
                'or',
                [
                    'and',
                    ['truthy', 'acl.photo.photo.create'],
                    ['truthy', 'setting.feed.types.photo_set.can_create_feed'],
                ],
                [
                    'and',
                    ['truthy', 'acl.video.video.create'],
                    ['truthy', 'setting.feed.types.photo_set.can_create_feed'],
                    ['truthy', 'setting.video.video_service_is_ready'],
                ],
            ],
            [
                'or',
                ['truthy', 'isHomeScreen'],
                [
                    'or',
                    ['eq', 'attachmentType', 'photo'],
                    ['eq', 'attachmentType', 'photo_set'],
                ],
                [
                    'and',
                    ['falsy', 'hasShareValue'],
                    ['falsy', 'pstatusbg_enable'],
                    ['falsy', 'hasPoll'],
                    ['falsy', 'hasVideoUrl'],
                    ['falsy', 'isEdit'],
                ],
            ],
        ],
    ],
    [
        'description' => 'Say something about this photo...',
        'post_type'   => 'photo',
        'icon_color'  => '#48c260',
        'menu'        => 'feed.feed.feedComposerMenu',
        'name'        => 'compose_photo',
        'label'       => 'photo::phrase.media_label_saved',
        'ordering'    => 4,
        'as'          => 'post.photo',
        'value'       => 'photo_set',
        'icon'        => 'photos',
        'to'          => '2',
        'showWhen'    => [
            'and',
            [
                'or',
                [
                    'and',
                    ['truthy', 'acl.photo.photo.create'],
                    ['truthy', 'setting.feed.types.photo_set.can_create_feed'],
                ],
                [
                    'and',
                    ['truthy', 'acl.video.video.create'],
                    ['truthy', 'setting.feed.types.photo_set.can_create_feed'],
                    ['truthy', 'setting.video.video_service_is_ready'],
                ],
            ],
            [
                'or',
                ['truthy', 'isHomeScreen'],
                [
                    'or',
                    ['eq', 'attachmentType', 'photo'],
                    ['eq', 'attachmentType', 'photo_set'],
                ],
                [
                    'and',
                    ['falsy', 'hasShareValue'],
                    ['falsy', 'pstatusbg_enable'],
                    ['falsy', 'hasPoll'],
                    ['falsy', 'hasVideoUrl'],
                    ['falsy', 'isEdit'],
                ],
            ],
        ],
    ],
    [
        'description' => 'Say something about this photo...',
        'post_type'   => 'photo',
        'icon_color'  => '#48c260',
        'menu'        => 'group.group.feedComposerMenu',
        'name'        => 'compose_photo',
        'label'       => 'photo::phrase.media_label_saved',
        'ordering'    => 4,
        'as'          => 'post.photo',
        'value'       => 'photo_set',
        'icon'        => 'photos',
        'to'          => '2',
        'showWhen'    => [
            'and',
            [
                'or',
                [
                    'and',
                    ['truthy', 'acl.photo.photo.create'],
                    ['truthy', 'setting.feed.types.photo_set.can_create_feed'],
                    ['truthy', 'item.profile_settings.photo_share_photos'],
                ],
                [
                    'and',
                    ['truthy', 'acl.video.video.create'],
                    ['truthy', 'setting.feed.types.photo_set.can_create_feed'],
                    ['truthy', 'item.profile_settings.video_share_videos'],
                    ['truthy', 'setting.video.video_service_is_ready'],
                ],
            ],
            [
                'or',
                ['truthy', 'isHomeScreen'],
                [
                    'or',
                    ['eq', 'attachmentType', 'photo'],
                    ['eq', 'attachmentType', 'photo_set'],
                ],
                [
                    'and',
                    ['falsy', 'hasShareValue'],
                    ['falsy', 'pstatusbg_enable'],
                    ['falsy', 'hasPoll'],
                    ['falsy', 'hasVideoUrl'],
                    ['falsy', 'isEdit'],
                ],
            ],
        ],
    ],
    [
        'tab'      => 'photo',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            ['truthy', 'acl.group.group.moderate'],
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'photo',
        'label'    => 'photo::phrase.photos',
        'ordering' => 5,
        'to'       => '/photo',
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'tab'      => 'photo_album',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            ['truthy', 'acl.group.group.moderate'],
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'photo_album',
        'label'    => 'photo::phrase.photo_albums',
        'ordering' => 5,
        'to'       => '/photo-album',
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'description' => 'Say something about this photo...',
        'post_type'   => 'photo',
        'icon_color'  => '#48c260',
        'menu'        => 'page.page.feedComposerMenu',
        'name'        => 'compose_photo',
        'label'       => 'photo::phrase.media_label_saved',
        'ordering'    => 4,
        'as'          => 'post.photo',
        'value'       => 'photo_set',
        'icon'        => 'photos',
        'to'          => '2',
        'showWhen'    => [
            'and',
            [
                'or',
                [
                    'and',
                    ['truthy', 'acl.photo.photo.create'],
                    ['truthy', 'setting.feed.types.photo_set.can_create_feed'],
                    ['truthy', 'item.profile_settings.photo_share_photos'],
                ],
                [
                    'and',
                    ['truthy', 'acl.video.video.create'],
                    ['truthy', 'setting.feed.types.photo_set.can_create_feed'],
                    ['truthy', 'item.profile_settings.video_share_videos'],
                    ['truthy', 'setting.video.video_service_is_ready'],
                ],
            ],
            [
                'or',
                ['truthy', 'isHomeScreen'],
                [
                    'or',
                    ['eq', 'attachmentType', 'photo'],
                    ['eq', 'attachmentType', 'photo_set'],
                ],
                [
                    'and',
                    ['falsy', 'hasShareValue'],
                    ['falsy', 'pstatusbg_enable'],
                    ['falsy', 'hasPoll'],
                    ['falsy', 'hasVideoUrl'],
                    ['falsy', 'isEdit'],
                ],
            ],
        ],
    ],
    [
        'tab'      => 'photo',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'photo',
        'label'    => 'photo::phrase.photos',
        'ordering' => 4,
        'to'       => '/photo',
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'tab'      => 'photo_album',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'photo_album',
        'label'    => 'photo::phrase.photo_albums',
        'ordering' => 4,
        'to'       => '/photo-album',
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.photo.photo.create'],
        ],
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'menu'     => 'photo.addPhotoMenu',
        'name'     => 'upload_photo',
        'label'    => 'photo::phrase.add_new_photos',
        'ordering' => 1,
        'value'    => 'addItem',
        'icon'     => 'plus',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.photo.photo_album.create'],
        ],
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'menu'     => 'photo.addPhotoMenu',
        'name'     => 'create_album',
        'label'    => 'photo::phrase.create_new_album',
        'ordering' => 2,
        'value'    => 'addItem',
        'icon'     => 'plus',
    ],
    [
        'menu'     => 'photo.photo.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'photo.photo.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'photo.photo.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'photo.photo.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'photo::phrase.edit_photo',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_set_profile_avatar'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'make-avatar',
        'label'    => 'photo::phrase.make_profile_picture',
        'ordering' => 2,
        'value'    => 'updateAvatarFromPhoto',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_set_profile_cover'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'make-cover',
        'label'    => 'photo::phrase.make_cover_photo',
        'ordering' => 3,
        'value'    => 'updateCoverFromListingPhoto',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_download'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'download-photo',
        'label'    => 'photo::phrase.download',
        'ordering' => 4,
        'value'    => 'photo/downloadItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'photo::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_set_parent_cover'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'make-parent-cover',
        'label'    => 'photo::phrase.make_owner_type_name_s_cover_photo',
        'ordering' => 9,
        'value'    => 'updateParentCoverFromPhoto',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_set_parent_avatar'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'make-parent-avatar',
        'label'    => 'photo::phrase.make_owner_type_name_s_avatar_photo',
        'ordering' => 10,
        'value'    => 'updateParentAvatarPhoto',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'photo::phrase.sponsor_in_feed',
        'ordering' => 8,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'photo::phrase.sponsor_in_feed',
        'ordering' => 8,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'photo::phrase.un_sponsor_in_feed',
        'ordering' => 8,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'photo::phrase.sponsor_this_item',
        'ordering' => 11,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'photo::phrase.sponsor_this_item',
        'ordering' => 11,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'photo::phrase.unsponsor_this_item',
        'ordering' => 11,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 12,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 12,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 12,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 13,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'photo.photo.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 13,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'photo.photo.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'photo::phrase.delete',
        'ordering'  => 15,
        'value'     => 'deleteItem',
    ],
    [
        'menu'     => 'photo.photo.sort_menu',
        'name'     => 'recent',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'photo.photo.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 2,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'photo.photo.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 3,
        'value'    => 'most_discussed',
    ],
    [
        'menu'     => 'photo.photo.sort_menu',
        'name'     => 'a_to_z',
        'label'    => 'core::phrase.sort.a_to_z',
        'ordering' => 4,
        'value'    => 'a_to_z',
    ],
    [
        'menu'     => 'photo.photo.sort_menu',
        'name'     => 'z_to_a',
        'label'    => 'core::phrase.sort.z_to_a',
        'ordering' => 5,
        'value'    => 'z_to_a',
    ],
    [
        'menu'     => 'photo.photo_album.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'photo.photo_album.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'photo.photo_album.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'photo.photo_album.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'photo::phrase.edit_photo_album',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'photo::phrase.sponsor_this_item',
        'ordering' => 3,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'photo::phrase.sponsor_this_item',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'photo::phrase.unsponsor_this_item',
        'ordering' => 3,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 7,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'photo.photo_album.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'photo::phrase.delete',
        'ordering' => 11,
        'value'    => 'deleteItem',
    ],
    [
        'menu'     => 'photo.photo_album.sort_menu',
        'name'     => 'recent',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'photo.photo_album.sort_menu',
        'name'     => 'most_viewed',
        'label'    => 'core::phrase.sort.most_viewed',
        'ordering' => 2,
        'value'    => 'most_viewed',
    ],
    [
        'menu'     => 'photo.photo_album.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 2,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'photo.photo_album.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 3,
        'value'    => 'most_discussed',
    ],
    [
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'menu'     => 'photo.sidebarMenu',
        'name'     => 'all',
        'label'    => 'photo::phrase.all_photos',
        'ordering' => 1,
        'value'    => 'viewAll',
    ],
    [
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'menu'     => 'photo.sidebarMenu',
        'name'     => 'my',
        'label'    => 'photo::phrase.my_photos',
        'ordering' => 2,
        'value'    => 'viewMyPhotos',
    ],
    [
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'photo.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'photo::phrase.my_pending_photos',
        'ordering' => 3,
        'value'    => 'viewMyPendingPhotos',
    ],
    [
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'menu'     => 'photo.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'photo::phrase.friend_s_photos',
        'ordering' => 4,
        'value'    => 'viewFriendPhotos',
    ],
    [
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'menu'     => 'photo.sidebarMenu',
        'name'     => 'all_albums',
        'label'    => 'photo::phrase.all_albums',
        'ordering' => 5,
        'value'    => 'viewAll',
    ],
    [
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'menu'     => 'photo.sidebarMenu',
        'name'     => 'my_albums',
        'label'    => 'photo::phrase.my_albums',
        'ordering' => 6,
        'value'    => 'viewMyAlbums',
    ],
    [
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'showWhen' => [
            'or',
            ['truthy', 'acl.photo.photo.approve'],
        ],
        'menu'     => 'photo.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'photo::phrase.pending_photos',
        'ordering' => 7,
        'value'    => 'viewPendingPhotos',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.photo.photo.view'],
            ['falsy', 'is_hashtag'],
        ],
        'module_name'   => 'photo',
        'resource_name' => 'photo',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'photo',
        'label'         => 'photo::phrase.photo_global_search_label',
        'ordering'      => 10,
        'value'         => 'searchGlobalPhoto',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.photo.photo.view'],
            ['falsy', 'is_hashtag'],
        ],
        'module_name'   => 'photo',
        'resource_name' => 'photo_album',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'photo_album',
        'label'         => 'photo::phrase.photo_album_global_search_label',
        'ordering'      => 10,
        'value'         => 'searchGlobalPhotoAlbum',
    ],
    [
        'description' => 'Say something about this photo...',
        'post_type'   => 'photo',
        'icon_color'  => '#48c260',
        'menu'        => 'user.user.feedComposerMenu',
        'name'        => 'compose_photo',
        'label'       => 'photo::phrase.media_label_saved',
        'ordering'    => 4,
        'as'          => 'post.photo',
        'value'       => 'photo_set',
        'icon'        => 'photos',
        'to'          => '2',
        'showWhen'    => [
            'and',
            [
                'or',
                [
                    'and',
                    ['truthy', 'acl.photo.photo.create'],
                    ['truthy', 'setting.feed.types.photo_set.can_create_feed'],
                ],
                [
                    'and',
                    ['truthy', 'acl.video.video.create'],
                    ['truthy', 'setting.feed.types.photo_set.can_create_feed'],
                    ['truthy', 'setting.video.video_service_is_ready'],
                ],
            ],
            [
                'or',
                ['truthy', 'isHomeScreen'],
                [
                    'or',
                    ['eq', 'attachmentType', 'photo'],
                    ['eq', 'attachmentType', 'photo_set'],
                ],
                [
                    'and',
                    ['falsy', 'hasShareValue'],
                    ['falsy', 'pstatusbg_enable'],
                    ['falsy', 'hasPoll'],
                    ['falsy', 'hasVideoUrl'],
                    ['falsy', 'isEdit'],
                ],
            ],

        ],
    ],
    [
        'tab'      => 'photo',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_settings.photo_display_on_profile'],
            ['truthy', 'item.profile_menu_settings.photo'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'photo',
        'label'    => 'photo::phrase.photos',
        'ordering' => 4,
        'to'       => '/photo',
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'tab'      => 'photo_album',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_settings.photo_display_on_profile'],
            ['truthy', 'item.profile_menu_settings.photo'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'photo_album',
        'label'    => 'photo::phrase.photo_albums',
        'ordering' => 4,
        'to'       => '/photo_album',
        'params'   => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.photo.photo.view'],
        ],
        'module_name'   => 'photo',
        'resource_name' => 'photo',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'photo',
        'label'         => 'photo::phrase.photo_global_search_label',
        'ordering'      => 10,
        'value'         => 'searchGlobalPhoto',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.photo.photo.view'],
        ],
        'module_name'   => 'photo',
        'resource_name' => 'photo_album',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'photo_album',
        'label'         => 'photo::phrase.photo_album_global_search_label',
        'ordering'      => 10,
        'value'         => 'searchGlobalPhotoAlbum',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.photo.photo.view'],
        ],
        'module_name'   => 'photo',
        'resource_name' => 'photo',
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'photo',
        'label'         => 'photo::phrase.photo_global_search_label',
        'ordering'      => 10,
        'value'         => 'searchGlobalPhoto',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.photo.photo.view'],
        ],
        'module_name'   => 'photo',
        'resource_name' => 'photo_album',
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'photo_album',
        'label'         => 'photo::phrase.photo_album_global_search_label',
        'ordering'      => 10,
        'value'         => 'searchGlobalPhotoAlbum',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'photo::phrase.edit_photo',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_set_profile_avatar'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'make-avatar',
        'label'    => 'photo::phrase.make_profile_picture',
        'ordering' => 2,
        'value'    => 'updateAvatarFromPhoto',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_set_profile_cover'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'make-cover',
        'label'    => 'photo::phrase.make_cover_photo',
        'ordering' => 3,
        'value'    => 'updateCoverFromListingPhoto',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_tag_friend'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'tag-friend',
        'label'    => 'photo::phrase.tag_friends',
        'ordering' => 4,
        'value'    => 'photo/tagFriend',
        'icon'     => 'price-tag-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_download'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'download-photo',
        'label'    => 'photo::phrase.download',
        'ordering' => 4,
        'value'    => 'photo/downloadItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'photo::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_set_parent_cover'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'make-parent-cover',
        'label'    => 'photo::phrase.make_owner_type_name_s_cover_photo',
        'ordering' => 9,
        'value'    => 'updateParentCoverFromPhoto',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_set_parent_avatar'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'make-parent-avatar',
        'label'    => 'photo::phrase.make_owner_type_name_s_avatar_photo',
        'ordering' => 10,
        'value'    => 'updateParentAvatarPhoto',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'photo::phrase.sponsor_in_feed',
        'ordering' => 8,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'photo::phrase.sponsor_in_feed',
        'ordering' => 8,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'photo::phrase.un_sponsor_in_feed',
        'ordering' => 8,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'photo::phrase.sponsor_this_item',
        'ordering' => 11,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'photo::phrase.sponsor_this_item',
        'ordering' => 11,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'photo::phrase.unsponsor_this_item',
        'ordering' => 11,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 12,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 12,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 12,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 13,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'photo.photo.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 13,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'photo.photo.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'photo::phrase.delete',
        'ordering'  => 15,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'photo.photo_album.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'photo::phrase.edit_photo_album',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'photo.photo_album.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'photo::phrase.sponsor_this_item',
        'ordering' => 3,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'photo.photo_album.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'photo::phrase.sponsor_this_item',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'photo.photo_album.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'photo::phrase.unsponsor_this_item',
        'ordering' => 3,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'photo.photo_album.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'photo.photo_album.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'photo.photo_album.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 7,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'photo.photo_album.detailActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'photo.photo_album.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'photo.photo_album.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'photo::phrase.delete',
        'ordering' => 11,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'photo',
        'label'     => 'photo::phrase.photos',
        'ordering'  => 11,
        'value'     => '',
        'to'        => '/photo',
        'as'        => 'item',
        'icon'      => 'photos-alt',
        'iconColor' => '#00b7f4',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.photo.photo.view'],
        ],
        'menu'          => 'search.mobileHashtagCategoryMenu',
        'name'          => 'photo',
        'label'         => 'photo::phrase.photo_global_search_label',
        'ordering'      => 6,
        'module_name'   => 'photo',
        'resource_name' => 'photo',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'photo.photo.headerItemActionOnUserProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["truthy", "acl.photo.photo.create"],
            ["truthy", "item.is_owner"],
        ],
        'menu'       => 'photo.photo.headerItemActionOnUserProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'photo.photo_album.headerItemActionOnUserProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["truthy", "acl.photo.photo_album.create"],
            ["truthy", "item.is_owner"],
        ],
        'menu'       => 'photo.photo_album.headerItemActionOnUserProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'photo.photo.headerItemActionOnPageProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["truthy", "acl.photo.photo.create"],
            ["truthy", "item.profile_settings.photo_share_photos"],
            ["falsy", "item.is_pending"],
        ],
        'menu'       => 'photo.photo.headerItemActionOnPageProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'photo.photo_album.headerItemActionOnPageProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["truthy", "acl.photo.photo_album.create"],
            ["truthy", "item.profile_settings.photo_album_share_albums"],
            ["falsy", "item.is_pending"],
        ],
        'menu'       => 'photo.photo_album.headerItemActionOnPageProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'photo.photo.headerItemActionOnGroupProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["falsy", "item.is_muted"],
            ["falsy", "item.is_pending"],
            [
                "or",
                [
                    "and",
                    ["truthy", "acl.photo.photo.create"],
                    ["truthy", "item.profile_settings.photo_share_photos"],
                ],
                [
                    "and",
                    ["truthy", "acl.video.video.create"],
                    ["truthy", "item.profile_settings.video_share_videos"],
                ],
            ],
        ],
        'menu'       => 'photo.photo.headerItemActionOnGroupProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'photo.photo_album.headerItemActionOnGroupProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["truthy", "acl.photo.photo_album.create"],
            ["truthy", "item.profile_settings.photo_album_share_albums"],
            ["falsy", "item.is_muted"],
            ["falsy", "item.is_pending"],
        ],
        'menu'       => 'photo.photo_album.headerItemActionOnGroupProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'photo',
            'resource_name' => 'photo_album',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
];
