<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.livestreaming.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'livestreaming/permission',
    ],
    [
        'name'         => 'admin.livestreaming.setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'livestreaming/setting',
    ],
    [
        'name'         => 'admin.livestreaming.streaming_service',
        'phrase_title' => 'livestreaming::phrase.streaming_service',
        'url'          => 'livestreaming/streaming-service/browse',
    ],
    [
        'name'         => 'admin.livestreaming.browse_live_videos',
        'phrase_title' => 'livestreaming::phrase.manage_live_videos',
        'url'          => 'livestreaming/live-video/browse',
    ],
    [
        'name'               => 'livestreaming.live_video',
        'phrase_title'       => 'livestreaming::seo.live_video_search_title',
        'phrase_description' => 'livestreaming::seo.live_video_search_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_search_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_search_heading',
    ],
    [
        'name'                 => 'livestreaming.live_video.create',
        'phrase_title'         => 'livestreaming::seo.live_video_create_title',
        'phrase_description'   => 'livestreaming::seo.live_video_create_description',
        'phrase_keywords'      => 'livestreaming::seo.live_video_create_keywords',
        'phrase_heading'       => 'livestreaming::seo.live_video_create_heading',
        'url'                  => 'live-video/add',
        'item_type'            => 'live_video',
        'custom_sharing_route' => 1,
    ],
    [
        'name'                 => 'livestreaming.live_video.edit',
        'phrase_title'         => 'livestreaming::seo.live_video_edit_title',
        'phrase_description'   => 'livestreaming::seo.live_video_edit_description',
        'phrase_keywords'      => 'livestreaming::seo.live_video_edit_keywords',
        'phrase_heading'       => 'livestreaming::seo.live_video_edit_heading',
        'url'                  => 'live-video/edit/{id}',
        'item_type'            => 'live_video',
        'custom_sharing_route' => 1,
    ],
    [
        'name'               => 'livestreaming.live_video.dashboard',
        'phrase_title'       => 'livestreaming::seo.live_video_dashboard_title',
        'phrase_description' => 'livestreaming::seo.live_video_dashboard_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_dashboard_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_dashboard_heading',
        'url'                => 'live-video/dashboard/{id}',
        'item_type'          => 'live_video',
    ],
    [
        'name'               => 'livestreaming.live_video.landing',
        'phrase_title'       => 'livestreaming::seo.live_video_landing_title',
        'phrase_description' => 'livestreaming::seo.live_video_landing_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_landing_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_landing_heading',
        'url'                => 'live-video',
        'item_type'          => 'live_video',
    ],
    [
        'name'               => 'livestreaming.live_video.all_streaming',
        'phrase_title'       => 'livestreaming::seo.live_video_browse_all_streaming_title',
        'phrase_description' => 'livestreaming::seo.live_video_browse_all_streaming_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_browse_all_streaming_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_browse_all_streaming_heading',
        'url'                => 'live-video/all-streaming',
        'item_type'          => 'live_video',
    ],
    [
        'name'               => 'livestreaming.live_video.my_streaming',
        'phrase_title'       => 'livestreaming::seo.live_video_my_streaming_title',
        'phrase_description' => 'livestreaming::seo.live_video_my_streaming_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_my_streaming_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_my_streaming_heading',
        'url'                => 'live-video/my-streaming',
        'item_type'          => 'live_video',
    ],
    [
        'name'               => 'livestreaming.live_video.my',
        'phrase_title'       => 'livestreaming::seo.live_video_my_title',
        'phrase_description' => 'livestreaming::seo.live_video_my_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_my_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_my_heading',
        'url'                => 'live-video/my',
        'item_type'          => 'live_video',
    ],
    [
        'name'               => 'livestreaming.live_video.view_detail',
        'phrase_title'       => 'livestreaming::seo.live_video_view_detail_title',
        'phrase_description' => 'livestreaming::seo.live_video_view_detail_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_view_detail_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_view_detail_heading',
        'url'                => 'live-video/{id}',
        'item_type'          => 'live_video',
        'resource_name'      => 'live_video',
    ],
    [
        'name'               => 'livestreaming.live_video.browse_all_live_video',
        'phrase_title'       => 'livestreaming::seo.live_video_browse_all_title',
        'phrase_description' => 'livestreaming::seo.live_video_browse_all_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_browse_all_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_browse_all_heading',
        'url'                => 'live-video/all',
        'item_type'          => 'live_video',
    ],
    [
        'name'               => 'livestreaming.live_video.browse_friend_live_video',
        'phrase_title'       => 'livestreaming::seo.live_video_browse_friend_title',
        'phrase_description' => 'livestreaming::seo.live_video_browse_friend_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_browse_friend_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_browse_friend_heading',
        'url'                => 'live-video/friend',
        'item_type'          => 'live_video',
    ],
    [
        'name'               => 'user.profile.livestreaming',
        'phrase_title'       => 'livestreaming::seo.user_profile_live_video_title',
        'phrase_description' => 'livestreaming::seo.user_profile_live_video_description',
        'phrase_keywords'    => 'livestreaming::seo.user_profile_live_video_keywords',
        'phrase_heading'     => 'livestreaming::seo.user_profile_live_video_heading',
        'url'                => 'user/{id}/live-video',
        'item_type'          => 'user',
    ],
    [
        'name'               => 'livestreaming.live_video.search',
        'phrase_title'       => 'livestreaming::seo.live_video_search_title',
        'phrase_description' => 'livestreaming::seo.live_video_search_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_search_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_search_heading',
        'url'                => 'live-video/search',
        'item_type'          => 'live_video',
    ],
    [
        'name'               => 'livestreaming.live_video.browse_my_pending_video',
        'phrase_title'       => 'livestreaming::seo.live_video_browse_my_pending_title',
        'phrase_description' => 'livestreaming::seo.live_video_browse_my_pending_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_browse_my_pending_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_browse_my_pending_heading',
        'url'                => 'live-video/my-pending',
        'item_type'          => 'live_video',
    ],
    [
        'name'               => 'livestreaming.live_video.browse_pending_video',
        'phrase_title'       => 'livestreaming::seo.live_video_browse_pending_title',
        'phrase_description' => 'livestreaming::seo.live_video_browse_pending_description',
        'phrase_keywords'    => 'livestreaming::seo.live_video_browse_pending_keywords',
        'phrase_heading'     => 'livestreaming::seo.live_video_browse_pending_heading',
        'url'                => 'live-video/pending',
        'item_type'          => 'live_video',
    ],
];
