<?php
/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'blog',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'blog.category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'blog.category.category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Models\\Blog',
        'type'       => 'entity',
        'name'       => 'blog',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Blogs',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Models\\Category',
        'type'       => 'entity',
        'name'       => 'blog_category',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Blog Categories',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Models\\CategoryData',
        'type'       => 'entity',
        'name'       => 'blog_category_data',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Blog Category Data',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Models\\Blog',
        'type'       => 'entity-content',
        'name'       => 'blog',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Blogs',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\StoreBlogMobileForm',
        'type'       => 'form',
        'name'       => 'blog.blog.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\UpdateBlogMobileForm',
        'type'       => 'form',
        'name'       => 'blog.blog.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\Admin\\DestroyCategoryForm',
        'type'       => 'form',
        'name'       => 'blog.blog_category.destroy',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\Admin\\StoreCategoryForm',
        'type'       => 'form',
        'name'       => 'blog.blog_category.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\Admin\\UpdateCategoryForm',
        'type'       => 'form',
        'name'       => 'blog.blog_category.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\SearchBlogMobileForm',
        'type'       => 'form',
        'name'       => 'blog.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\SearchBlogForm',
        'type'       => 'form',
        'name'       => 'blog.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\SearchInOwnerMobileForm',
        'type'       => 'form',
        'name'       => 'blog.search_in_owner',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\StoreBlogForm',
        'type'       => 'form',
        'name'       => 'blog.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\StoreBlogMobileForm',
        'type'       => 'form',
        'name'       => 'blog.store_blog_mobile',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\UpdateBlogForm',
        'type'       => 'form',
        'name'       => 'blog.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'blog',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/blog/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Jobs\\DeleteCategoryJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Blog\\Jobs\\DeleteCategoryJob',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\BlogEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'blog.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\BlogItemCollection',
        'type'       => 'json-collection',
        'name'       => 'blog.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\CategoryEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'blog_category.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\CategoryItemCollection',
        'type'       => 'json-collection',
        'name'       => 'blog_category.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\BlogDetail',
        'type'       => 'json-resource',
        'name'       => 'blog.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\BlogEmbed',
        'type'       => 'json-resource',
        'name'       => 'blog.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\FeedEmbed',
        'type'       => 'json-resource',
        'name'       => 'blog.feed_embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\BlogItem',
        'type'       => 'json-resource',
        'name'       => 'blog.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\BlogPropertiesSchema',
        'type'       => 'json-resource',
        'name'       => 'blog.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\CategoryDetail',
        'type'       => 'json-resource',
        'name'       => 'blog_category.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\CategoryEmbed',
        'type'       => 'json-resource',
        'name'       => 'blog_category.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\CategoryItem',
        'type'       => 'json-resource',
        'name'       => 'blog_category.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Platform\\Http\\Resources\\v1\\Category\\CategoryPropertiesSEO',
        'type'       => 'json-resource',
        'name'       => 'blog_category.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'blog',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Policies\\BlogPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Blog\\Models\\Blog',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Policies\\CategoryPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Blog\\Models\\Category',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'blog',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'blog',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'blog',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Category\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'blog_category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Support\\SEO\\BlogSchema',
        'type'       => 'schema-structured',
        'name'       => 'blog',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Platform\\Support\\SEO\\CategorySchema',
        'type'       => 'schema-structured',
        'name'       => 'blog_category',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Blog\\Http\\Resources\\v1\\Blog\\Admin\\SearchBlogForm',
        'type'       => 'form',
        'name'       => 'blog.search_form',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
];
