<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_album_music',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'music::phrase.un_sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_album.itemActionMenu',
        'name'       => 'unsponsor',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 8,
        'value'      => 'unfeatureItem',
        'is_deleted' => true,
    ],

    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 7,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],

    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_playlist.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_playlist',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_album.create'],
        ],
        'params' => [
            'module_name'   => 'music',
            'resource_name' => 'music_album',
        ],
        'menu'     => 'music.addMusicMenu',
        'name'     => 'create_album',
        'label'    => 'music::phrase.add_new_album',
        'ordering' => 1,
        'value'    => 'addItem',
        'icon'     => 'plus',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_playlist.create'],
        ],
        'params' => [
            'module_name'   => 'music',
            'resource_name' => 'music_playlist',
        ],
        'menu'     => 'music.addMusicMenu',
        'name'     => 'create_playlist',
        'label'    => 'music::phrase.add_new_playlist',
        'ordering' => 1,
        'value'    => 'addItem',
        'icon'     => 'plus',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'       => 'music.music_playlist.itemActionMenu',
        'name'       => 'sponsor',
        'label'      => 'music::phrase.sponsor_this_item',
        'ordering'   => 4,
        'value'      => 'sponsorItem',
        'icon'       => 'ico-sponsor',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'       => 'music.music_playlist.itemActionMenu',
        'name'       => 'purchase_sponsor',
        'label'      => 'music::phrase.sponsor_this_item',
        'ordering'   => 4,
        'value'      => 'advertise/purchaseSponsorItem',
        'icon'       => 'ico-sponsor',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'       => 'music.music_playlist.itemActionMenu',
        'name'       => 'remove_sponsor',
        'label'      => 'music::phrase.unsponsor_this_item',
        'ordering'   => 4,
        'value'      => 'unsponsorItem',
        'icon'       => 'ico-sponsor',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'music.music_playlist.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_song',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'music::phrase.un_sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_album_music',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'tab'      => 'music_song',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'music_song',
        'label'    => 'music::phrase.music_songs',
        'ordering' => 5,
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_song',
        ],
        'value' => 'viewOnOwner',
    ],
    [
        'tab'      => 'music_song',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'music_song',
        'label'    => 'music::phrase.music_songs',
        'ordering' => 4,
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_song',
        ],
        'value' => 'viewOnOwner',
    ],
    [
        'tab'      => 'music_album',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'music_album',
        'label'    => 'music::phrase.music_albums',
        'ordering' => 5,
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_album',
        ],
        'value' => 'viewOnOwner',
    ],
    [
        'tab'      => 'music_album',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'music_album',
        'label'    => 'music::phrase.music_albums',
        'ordering' => 4,
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_album',
        ],
        'value' => 'viewOnOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'music::phrase.un_sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_album.detailActionMenu',
        'name'       => 'unsponsor',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 8,
        'value'      => 'unfeatureItem',
        'is_deleted' => true,
    ],

    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 7,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],

    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_playlist',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_song',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'music::phrase.un_sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_to_playlist'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'add_to_playlist',
        'label'    => 'music::phrase.add_to_playlist',
        'ordering' => 13,
        'value'    => 'music/addToPlaylist',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_to_playlist'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'add_to_playlist',
        'label'    => 'music::phrase.add_to_playlist',
        'ordering' => 13,
        'value'    => 'music/addToPlaylist',
    ],
    [
        'params' => [
            'module_name'   => 'music',
            'resource_name' => 'music_song',
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'all',
        'label'    => 'music::phrase.all_songs',
        'ordering' => 1,
        'value'    => 'viewAll',
    ],
    [
        'params' => [
            'module_name'   => 'music',
            'resource_name' => 'music_song',
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'my',
        'label'    => 'music::phrase.my_songs',
        'ordering' => 2,
        'value'    => 'viewMySongs',
    ],
    [
        'params' => [
            'module_name'   => 'music',
            'resource_name' => 'music_song',
        ],
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'music::phrase.my_pending_songs',
        'ordering' => 3,
        'value'    => 'viewMyPendingSongs',
    ],
    [
        'params' => [
            'module_name'   => 'music',
            'resource_name' => 'music_song',
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'music::phrase.friends_songs',
        'ordering' => 4,
        'value'    => 'viewFriendSongs',
    ],
    [
        'params' => [
            'module_name'   => 'music',
            'resource_name' => 'music_album',
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'all_albums',
        'label'    => 'music::phrase.all_albums',
        'ordering' => 5,
        'value'    => 'viewAll',
    ],
    [
        'params' => [
            'module_name'   => 'music',
            'resource_name' => 'music_album',
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'my_albums',
        'label'    => 'music::phrase.my_albums',
        'ordering' => 6,
        'value'    => 'viewMyAlbums',
    ],
    [
        'params' => [
            'module_name'   => 'music',
            'resource_name' => 'music_playlist',
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'all_playlist',
        'label'    => 'music::phrase.all_playlists',
        'ordering' => 7,
        'value'    => 'viewAll',
    ],
    [
        'params' => [
            'module_name'   => 'music',
            'resource_name' => 'music_playlist',
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'my_playlist',
        'label'    => 'music::phrase.my_playlists',
        'ordering' => 8,
        'value'    => 'viewMyPlaylists',
    ],
    [
        'params' => [
            'module_name'   => 'music',
            'resource_name' => 'music_song',
        ],
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_song.approve'],
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'music::phrase.pending_songs',
        'ordering' => 9,
        'value'    => 'viewPendingSongs',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'music::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'music::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'is_hashtag'],
            ['truthy', 'acl.music.music_song.view'],
        ],
        'module_name'   => 'music',
        'resource_name' => 'music_song',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'music_song',
        'label'         => 'music::phrase.music_song_global_search_label',
        'ordering'      => 7,
        'value'         => 'searchGlobalSong',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'is_hashtag'],
            ['truthy', 'acl.music.music_album.view'],
        ],
        'module_name'   => 'music',
        'resource_name' => 'music_album',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'music_album',
        'label'         => 'music::phrase.music_album_global_search_label',
        'ordering'      => 7,
        'value'         => 'searchGlobalAlbum',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'is_hashtag'],
            ['truthy', 'acl.music.music_playlist.view'],
        ],
        'module_name'   => 'music',
        'resource_name' => 'music_playlist',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'music_playlist',
        'label'         => 'music::phrase.music_playlist_global_search_label',
        'ordering'      => 7,
        'value'         => 'searchGlobalPlaylist',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_song',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'music::phrase.un_sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_to_playlist'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'add_to_playlist',
        'label'    => 'music::phrase.add_to_playlist',
        'ordering' => 13,
        'value'    => 'music/addToPlaylist',
    ],
    [
        'showWhen' => [
            'and',
            ['includes', 'item.playlist_ids', '$.subject.id'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'remove_from_this_playlist',
        'label'    => 'music::phrase.remove_from_this_playlist',
        'ordering' => 11,
        'value'    => 'music/removeFromPlaylist',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'       => 'music.music_song.itemActionMenuOnPlaylist',
        'name'       => 'delete',
        'label'      => 'music::phrase.delete',
        'ordering'   => 20,
        'value'      => 'deleteItem',
        'is_deleted' => true,
    ],
    [
        'tab'      => 'music_song',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.music'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'music_song',
        'label'    => 'music::phrase.music_songs',
        'ordering' => 9,
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_song',
        ],
        'value' => 'viewOnOwner',
    ],
    [
        'tab'      => 'music_album',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.music'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'music_album',
        'label'    => 'music::phrase.music_album',
        'ordering' => 9,
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_album',
        ],
        'value' => 'viewOnOwner',
    ],
    [
        'tab'      => 'music',
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_song.create'],
            ['truthy', 'item.profile_settings.music_share_musics'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'music.music_song.headerItemActionOnGroupProfileMenu',
        'name'     => 'music',
        'label'    => 'music::phrase.add_new_music',
        'ordering' => 1,
        'to'       => '/song/add?owner_id=:id',
    ],
    [
        'tab'      => 'music',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.music.music_song.create'],
            ['truthy', 'item.profile_settings.music_share_musics'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'music.music_song.headerItemActionOnPageProfileMenu',
        'name'     => 'music',
        'label'    => 'music::phrase.add_new_music',
        'ordering' => 1,
        'to'       => '/music/add?owner_id=:id',
    ],
    [
        'menu'     => 'music.music_song.sort_menu',
        'name'     => 'recent',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'music.music_song.sort_menu',
        'name'     => 'most_played',
        'label'    => 'music::phrase.most_played',
        'ordering' => 2,
        'value'    => 'most_played',
    ],
    [
        'menu'     => 'music.music_song.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 3,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'music.music_song.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 4,
        'value'    => 'most_discussed',
    ],
    [
        'menu'     => 'music.music_album.sort_menu',
        'name'     => 'recent',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'music.music_album.sort_menu',
        'name'     => 'most_viewed',
        'label'    => 'core::phrase.sort.most_viewed',
        'ordering' => 2,
        'value'    => 'most_viewed',
    ],
    [
        'menu'     => 'music.music_album.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 3,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'music.music_album.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 4,
        'value'    => 'most_discussed',
    ],
    [
        'menu'     => 'music.music_playlist.sort_menu',
        'name'     => 'recent',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'music.music_playlist.sort_menu',
        'name'     => 'most_viewed',
        'label'    => 'core::phrase.sort.most_viewed',
        'ordering' => 2,
        'value'    => 'most_viewed',
    ],
    [
        'menu'     => 'music.music_playlist.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 3,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'music.music_playlist.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 4,
        'value'    => 'most_discussed',
    ],
    [
        'menu'     => 'music.music_song.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'music.music_song.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'music.music_song.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'music.music_song.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'menu'     => 'music.music_album.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'music.music_album.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'music.music_album.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'music.music_album.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'menu'     => 'music.music_playlist.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'music.music_playlist.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'music.music_playlist.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'music.music_playlist.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'music',
        'label'     => 'music::phrase.music',
        'ordering'  => 9,
        'value'     => '',
        'to'        => '/music-song',
        'as'        => 'item',
        'icon'      => 'music-album',
        'iconColor' => '#ff4986',
    ],
    [
        'showWhen' => [
            'and',
            ['exists', 'setting.saved'],
            ['eq', 'item.is_saved', 0],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'save',
        'label'    => 'music::phrase.save',
        'ordering' => 14,
        'value'    => 'saveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['exists', 'setting.saved'],
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'un-save',
        'label'    => 'music::phrase.remove_from_saved_list',
        'ordering' => 15,
        'value'    => 'undoSaveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_report'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'report',
        'label'    => 'music::phrase.report',
        'ordering' => 19,
        'value'    => 'reportItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'is_hashtag'],
            ['truthy', 'acl.music.music_song.view'],
        ],
        'module_name'   => 'music',
        'resource_name' => 'music_song',
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'music_song',
        'label'         => 'music::phrase.music_song_global_search_label',
        'ordering'      => 7,
        'value'         => 'searchGlobalSong',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'is_hashtag'],
            ['truthy', 'acl.music.music_album.view'],
        ],
        'module_name'   => 'music',
        'resource_name' => 'music_album',
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'music_album',
        'label'         => 'music::phrase.music_album_global_search_label',
        'ordering'      => 7,
        'value'         => 'searchGlobalAlbum',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'is_hashtag'],
            ['truthy', 'acl.music.music_song.view'],
        ],
        'module_name'   => 'music',
        'resource_name' => 'music_song',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'music_song',
        'label'         => 'music::phrase.music_song_global_search_label',
        'ordering'      => 7,
        'value'         => 'searchGlobalSong',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'is_hashtag'],
            ['truthy', 'acl.music.music_album.view'],
        ],
        'module_name'   => 'music',
        'resource_name' => 'music_album',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'music_album',
        'label'         => 'music::phrase.music_album_global_search_label',
        'ordering'      => 7,
        'value'         => 'searchGlobalAlbum',
    ],
    [
        'showWhen' => [],
        'label'    => '',
        'ordering' => 1,
        'menu'     => 'music.music_song.headerItemActionOnUserProfileMenu',
        'name'     => 'search',
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_song',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen' => [],
        'label'    => '',
        'ordering' => 1,
        'menu'     => 'music.music_song.headerItemActionOnPageProfileMenu',
        'name'     => 'search',
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_song',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen' => [],
        'label'    => '',
        'ordering' => 1,
        'menu'     => 'music.music_song.headerItemActionOnGroupProfileMenu',
        'name'     => 'search',
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_song',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen' => [],
        'label'    => '',
        'ordering' => 1,
        'menu'     => 'music.music_album.headerItemActionOnUserProfileMenu',
        'name'     => 'search',
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_album',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen' => [],
        'label'    => '',
        'ordering' => 1,
        'menu'     => 'music.music_album.headerItemActionOnPageProfileMenu',
        'name'     => 'search',
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_album',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen' => [],
        'label'    => '',
        'ordering' => 1,
        'menu'     => 'music.music_album.headerItemActionOnGroupProfileMenu',
        'name'     => 'search',
        'params'   => [
            'module_name'   => 'music',
            'resource_name' => 'music_album',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 9,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
];
