<?php

/* this is auto generated file */
return [
    [
        'subInfo'  => 'music::phrase.browse_songs_albums_or_playlists_you_may_like',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'music',
        'label'    => 'music::phrase.music',
        'ordering' => 10,
        'icon'     => 'ico-music-album',
        'to'       => '/music',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.music.music_song.create'],
        ],
        'menu'     => 'core.quickCreateMenu',
        'name'     => 'music',
        'label'    => 'music::phrase.music',
        'ordering' => 9,
        'icon'     => 'ico-music-album',
        'to'       => '/music/add',
    ],
    [
        'subInfo'  => 'music::phrase.browse_songs_albums_or_playlists_you_may_like',
        'menu'     => 'core.primaryMenu',
        'name'     => 'music',
        'label'    => 'music::phrase.music',
        'ordering' => 10,
        'icon'     => 'ico-music-album',
        'to'       => '/music',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_album_music',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'music::phrase.un_sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_album.itemActionMenu',
        'name'       => 'feature',
        'label'      => 'core::phrase.feature',
        'ordering'   => 7,
        'value'      => 'featureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'       => 'music.music_album.itemActionMenu',
        'name'       => 'unsponsor',
        'label'      => 'music::phrase.unsponsor_this_item',
        'ordering'   => 8,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => true,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_album.itemActionMenu',
        'name'       => 'unfeature',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 8,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_playlist.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_playlist',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'       => 'music.music_playlist.itemActionMenu',
        'name'       => 'sponsor',
        'label'      => 'music::phrase.sponsor_this_item',
        'ordering'   => 4,
        'value'      => 'sponsorItem',
        'icon'       => 'ico-sponsor',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'       => 'music.music_playlist.itemActionMenu',
        'name'       => 'purchase_sponsor',
        'label'      => 'music::phrase.sponsor_this_item',
        'ordering'   => 4,
        'value'      => 'advertise/purchaseSponsorItem',
        'icon'       => 'ico-sponsor',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'       => 'music.music_playlist.itemActionMenu',
        'name'       => 'remove_sponsor',
        'label'      => 'music::phrase.unsponsor_this_item',
        'ordering'   => 4,
        'value'      => 'unsponsorItem',
        'icon'       => 'ico-sponsor',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'music.music_playlist.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_song',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'tab'      => 'music',
        'showWhen' => [],
        'menu'     => 'page.page.profileMenu',
        'name'     => 'music',
        'label'    => 'music::phrase.music',
        'ordering' => 9,
        'to'       => '/music',
    ],
    [
        'tab'      => 'music',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'music',
        'label'    => 'music::phrase.music',
        'ordering' => 9,
        'to'       => '/music',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'music::phrase.un_sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_song.itemActionMenu',
        'name'       => 'feature',
        'label'      => 'core::phrase.feature',
        'ordering'   => 7,
        'value'      => 'featureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_song.itemActionMenu',
        'name'       => 'unfeature',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 8,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_album_music',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'music::phrase.un_sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_album.detailActionMenu',
        'name'       => 'feature',
        'label'      => 'core::phrase.feature',
        'ordering'   => 7,
        'value'      => 'featureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_album.detailActionMenu',
        'name'       => 'unfeature',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 8,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_album.detailActionMenu',
        'name'       => 'unsponsor',
        'label'      => 'music::phrase.unsponsor_this_item',
        'ordering'   => 8,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => true,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_playlist',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'music.music_playlist.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_song',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'music::phrase.un_sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_song.detailActionMenu',
        'name'       => 'feature',
        'label'      => 'core::phrase.feature',
        'ordering'   => 7,
        'value'      => 'featureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_song.detailActionMenu',
        'name'       => 'unfeature',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 8,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'music::phrase.delete',
        'ordering' => 20,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash-o',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'music.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'music::phrase.home',
        'ordering' => 1,
        'icon'     => 'ico-music-note-o',
        'to'       => '/music',
    ],
    [
        'tab'      => 'all_song',
        'menu'     => 'music.sidebarMenu',
        'name'     => 'all_song',
        'label'    => 'music::phrase.all_songs',
        'ordering' => 2,
        'icon'     => 'ico-music-allsongs',
        'to'       => '/music/song',
    ],
    [
        'tab'      => 'all_album',
        'menu'     => 'music.sidebarMenu',
        'name'     => 'all_album',
        'label'    => 'music::phrase.all_albums',
        'ordering' => 3,
        'icon'     => 'ico-music-album',
        'to'       => '/music/albums',
    ],
    [
        'tab'      => 'all_playlist',
        'menu'     => 'music.sidebarMenu',
        'name'     => 'all_playlist',
        'label'    => 'music::phrase.all_playlists',
        'ordering' => 4,
        'icon'     => 'ico-music-list-o',
        'to'       => '/music/playlists',
    ],
    [
        'tab'      => 'my_library',
        'menu'     => 'music.sidebarMenu',
        'name'     => 'my_library',
        'label'    => 'music::phrase.my_library',
        'ordering' => 5,
        'icon'     => 'ico-user-man-o',
        'to'       => '/music/my-library',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
    ],
    [
        'tab'      => 'friend_song',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'music::phrase.friends_songs',
        'ordering' => 6,
        'icon'     => 'ico-user1-two-o',
        'to'       => '/music/friend',
    ],
    [
        'tab'      => 'my_pending_song',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'my_pending_song',
        'label'    => 'music::phrase.my_pending_songs',
        'ordering' => 7,
        'icon'     => 'ico-user1-clock-o',
        'to'       => '/music/my-pending',
    ],
    [
        'tab'      => 'pending_song',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.music.music_song.approve'],
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'music::phrase.pending_songs',
        'ordering' => 8,
        'icon'     => 'ico-clock-o',
        'to'       => '/music/pending',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.music.music_song.create'],
        ],
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'menu'     => 'music.sidebarMenu',
        'name'     => 'add_song',
        'label'    => 'music::phrase.add_new_music',
        'ordering' => 9,
        'as'       => 'sidebarButton',
        'icon'     => 'ico-plus',
        'to'       => '/music/add',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_download'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'download_song',
        'label'    => 'music::phrase.download',
        'ordering' => 16,
        'value'    => 'music/downloadItem',
        'icon'     => 'ico-download',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_download'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'download_song',
        'label'    => 'music::phrase.download',
        'ordering' => 16,
        'value'    => 'music/downloadItem',
        'icon'     => 'ico-download',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_to_playlist'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'add_to_playlist',
        'label'    => 'music::phrase.add_to_playlist',
        'ordering' => 13,
        'value'    => 'music/addToPlaylist',
        'icon'     => 'ico-plus',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_to_playlist'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'add_to_playlist',
        'label'    => 'music::phrase.add_to_playlist',
        'ordering' => 13,
        'value'    => 'music/addToPlaylist',
        'icon'     => 'ico-plus',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_song.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'music_song',
        'label'    => 'music::phrase.music_song_global_search_label',
        'ordering' => 7,
        'to'       => '/search/music_song',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_song.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'music_song',
        'label'    => 'music::phrase.music_song_global_search_label',
        'ordering' => 6,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_album.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'music_album',
        'label'    => 'music::phrase.music_album_global_search_label',
        'ordering' => 7,
        'to'       => '/search/music_album',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_album.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'music_album',
        'label'    => 'music::phrase.music_album_global_search_label',
        'ordering' => 6,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_playlist.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'music_playlist',
        'label'    => 'music::phrase.music_playlist_global_search_label',
        'ordering' => 7,
        'to'       => '/search/music_playlist',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_playlist.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'music_playlist',
        'label'    => 'music::phrase.music_playlist_global_search_label',
        'ordering' => 6,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'edit',
        'label'    => 'music::phrase.edit_song',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'music::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'music::phrase.un_sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'purchase_sponsor',
        'label'    => 'music::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'remove_sponsor',
        'label'    => 'music::phrase.unsponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_song.itemActionMenuOnPlaylist',
        'name'       => 'feature',
        'label'      => 'core::phrase.feature',
        'ordering'   => 7,
        'value'      => 'featureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'music.music_song.itemActionMenuOnPlaylist',
        'name'       => 'unfeature',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 8,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_download'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'download_song',
        'label'    => 'music::phrase.download',
        'ordering' => 16,
        'value'    => 'music/downloadItem',
        'icon'     => 'ico-download',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'       => 'music.music_song.detailActionMenu',
        'name'       => 'approve',
        'label'      => 'music::phrase.approve',
        'ordering'   => 4,
        'value'      => 'approveItem',
        'icon'       => 'ico-check-circle-o',
        'is_active'  => 0,
        'is_deleted' => 1,

    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'music::phrase.approve',
        'ordering' => 4,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_to_playlist'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'add_to_playlist',
        'label'    => 'music::phrase.add_to_playlist',
        'ordering' => 13,
        'value'    => 'music/addToPlaylist',
        'icon'     => 'ico-plus',
    ],
    [
        'showWhen' => [
            'and',
            ['includes', 'item.playlist_ids', '$.subject.id'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'remove_from_this_playlist',
        'label'    => 'music::phrase.remove_from_this_playlist',
        'ordering' => 11,
        'value'    => 'music/removeFromPlaylist',
        'icon'     => 'ico-close',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'       => 'music.music_song.itemActionMenuOnPlaylist',
        'name'       => 'delete',
        'label'      => 'music::phrase.delete',
        'ordering'   => 20,
        'value'      => 'deleteItem',
        'icon'       => 'ico-trash',
        'is_deleted' => true,
    ],
    [
        'tab'      => 'music',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.music'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'music',
        'label'    => 'music::phrase.music',
        'ordering' => 9,
        'to'       => '/music',
    ],
    [
        'tab'      => 'music',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.music.music_song.create'],
            ['truthy', 'item.profile_settings.music_share_musics'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
            ['falsy', 'isMobile'],
        ],
        'menu'     => 'music.music_song.headerItemActionOnGroupProfileMenu',
        'name'     => 'music',
        'label'    => 'music::phrase.add_new_music',
        'ordering' => 1,
        'to'       => '/music/add?owner_id=:id',
    ],
    [
        'tab'      => 'music',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.music.music_song.create'],
            ['truthy', 'item.profile_settings.music_share_musics'],
            ['falsy', 'item.is_pending'],
            ['falsy', 'isMobile'],
        ],
        'menu'     => 'music.music_song.headerItemActionOnPageProfileMenu',
        'name'     => 'music',
        'label'    => 'music::phrase.add_new_music',
        'ordering' => 1,
        'to'       => '/music/add?owner_id=:id',
    ],
    [
        'tab'      => 'music',
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_song.create'],
            ['truthy', 'item.is_owner'],
            ['falsy', 'isMobile'],
        ],
        'menu'     => 'music.music_song.headerItemActionOnUserProfileMenu',
        'name'     => 'music',
        'label'    => 'music::phrase.add_new_music',
        'ordering' => 1,
        'to'       => '/music/add?owner_id=:id',
    ],
    [
        'showWhen' => [
            'and',
            ['exists', 'setting.saved'],
            ['eq', 'item.is_saved', 0],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'save',
        'label'    => 'music::phrase.save_music_song',
        'ordering' => 14,
        'value'    => 'saveItem',
        'icon'     => 'ico-bookmark-o',
    ],
    [
        'showWhen' => [
            'and',
            ['exists', 'setting.saved'],
            ['eq', 'item.is_saved', 1],
            ['truthy', 'item.extra.can_save_item'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'un-save',
        'label'    => 'music::phrase.remove_from_saved_list',
        'ordering' => 15,
        'value'    => 'undoSaveItem',
        'icon'     => 'ico-list-del',
    ],
    [
        'showWhen' => [
            'and',
            ['exists', 'setting.report'],
            ['truthy', 'item.extra.can_report'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'report',
        'label'    => 'music::phrase.report',
        'ordering' => 19,
        'value'    => 'reportItem',
        'icon'     => 'ico-warning-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_song.view'],
        ],
        'menu'     => 'group.searchWebCategoryMenu',
        'name'     => 'music_song',
        'label'    => 'music::phrase.music_song_global_search_label',
        'ordering' => 6,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_album.view'],
        ],
        'menu'     => 'group.searchWebCategoryMenu',
        'name'     => 'music_album',
        'label'    => 'music::phrase.music_album_global_search_label',
        'ordering' => 6,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_playlist.view'],
        ],
        'menu'       => 'group.searchWebCategoryMenu',
        'name'       => 'music_playlist',
        'label'      => 'music::phrase.music_playlist_global_search_label',
        'ordering'   => 6,
        'is_deleted' => true,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_song.view'],
        ],
        'menu'     => 'page.searchWebCategoryMenu',
        'name'     => 'music_song',
        'label'    => 'music::phrase.music_song_global_search_label',
        'ordering' => 6,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_album.view'],
        ],
        'menu'     => 'page.searchWebCategoryMenu',
        'name'     => 'music_album',
        'label'    => 'music::phrase.music_album_global_search_label',
        'ordering' => 6,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_playlist.view'],
        ],
        'menu'     => 'page.searchWebCategoryMenu',
        'name'     => 'music_playlist',
        'label'    => 'music::phrase.music_playlist_global_search_label',
        'ordering' => 6,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_playlist.view'],
        ],
        'menu'     => 'search.webHashtagCategoryMenu',
        'name'     => 'music_album',
        'label'    => 'music::phrase.music_album_global_search_label',
        'ordering' => 6,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.music.music_song.view'],
        ],
        'menu'     => 'search.webHashtagCategoryMenu',
        'name'     => 'music_song',
        'label'    => 'music::phrase.music_song_global_search_label',
        'ordering' => 6,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 9,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 9,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
        ],
        'menu'     => 'music.music_song.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
        ],
        'menu'     => 'music.music_song.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 9,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
        ],
        'menu'     => 'music.music_song.itemActionMenuOnPlaylist',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 9,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 9,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
        ],
        'menu'     => 'music.music_album.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
        ],
        'menu'     => 'music.music_album.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
];
