<?php

return [
    [
        'name'         => 'admin.advertise.advertise_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'advertise/setting',
    ],
    [
        'name'         => 'admin.advertise.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'advertise/permission',
    ],
    [
        'name'               => 'admin.advertise.browse_placement',
        'phrase_title'       => 'advertise::seo.advertise_browse_placement_title',
        'phrase_description' => 'advertise::seo.advertise_browse_placement_description',
        'phrase_keywords'    => 'advertise::seo.advertise_browse_placement_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_browse_placement_heading',
        'url'                => 'advertise/placement/browse',
        'item_type'          => 'advertise_placement',
    ],
    [
        'name'               => 'admin.advertise.create_placement',
        'phrase_title'       => 'advertise::seo.advertise_create_placement_title',
        'phrase_description' => 'advertise::seo.advertise_create_placement_description',
        'phrase_keywords'    => 'advertise::seo.advertise_create_placement_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_create_placement_heading',
        'url'                => 'advertise/placement/create',
        'item_type'          => 'advertise_placement',
    ],
    [
        'name'               => 'admin.advertise.browse_advertise',
        'phrase_title'       => 'advertise::seo.advertise_browse_advertise_title',
        'phrase_description' => 'advertise::seo.advertise_browse_advertise_description',
        'phrase_keywords'    => 'advertise::seo.advertise_browse_advertise_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_browse_advertise_heading',
        'url'                => 'advertise/advertise/browse',
        'item_type'          => 'advertise',
    ],
    [
        'name'               => 'admin.advertise.create_advertise',
        'phrase_title'       => 'advertise::seo.advertise_create_advertise_title',
        'phrase_description' => 'advertise::seo.advertise_create_advertise_description',
        'phrase_keywords'    => 'advertise::seo.advertise_create_advertise_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_create_advertise_heading',
        'url'                => 'advertise/advertise/create',
        'item_type'          => 'advertise',
    ],
    [
        'name'               => 'admin.advertise.browse_invoice',
        'phrase_title'       => 'advertise::seo.advertise_browse_invoice_title',
        'phrase_description' => 'advertise::seo.advertise_browse_invoice_description',
        'phrase_keywords'    => 'advertise::seo.advertise_browse_invoice_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_browse_invoice_heading',
        'url'                => 'advertise/invoice/browse',
        'item_type'          => 'advertise_invoice',
    ],
    [
        'name'               => 'advertise.advertise.landing',
        'phrase_title'       => 'advertise::seo.advertise_landing_title',
        'phrase_description' => 'advertise::seo.advertise_landing_description',
        'phrase_keywords'    => 'advertise::seo.advertise_landing_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_landing_heading',
        'url'                => 'advertise',
        'item_type'          => 'advertise',
    ],
    [
        'name'               => 'advertise.advertise_invoice.invoice',
        'phrase_title'       => 'advertise::seo.advertise_invoice_title',
        'phrase_description' => 'advertise::seo.advertise_invoice_description',
        'phrase_keywords'    => 'advertise::seo.advertise_invoice_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_invoice_heading',
        'url'                => 'advertise/invoice',
        'item_type'          => 'advertise_invoice',
    ],
    [
        'name'               => 'advertise.advertise.sponsorship',
        'phrase_title'       => 'advertise::seo.advertise_sponsorship_title',
        'phrase_description' => 'advertise::seo.advertise_sponsorship_description',
        'phrase_keywords'    => 'advertise::seo.advertise_sponsorship_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_sponsorship_heading',
        'url'                => 'advertise/sponsor',
        'item_type'          => 'advertise_sponsor',
    ],
    [
        'name'               => 'advertise.advertise.create',
        'phrase_title'       => 'advertise::seo.advertise_create_title',
        'phrase_description' => 'advertise::seo.advertise_create_description',
        'phrase_keywords'    => 'advertise::seo.advertise_create_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_create_heading',
        'url'                => 'advertise/add',
        'item_type'          => 'advertise',
    ],
    [
        'name'               => 'advertise.advertise.view_detail',
        'phrase_title'       => 'advertise::seo.advertise_detail_title',
        'phrase_description' => 'advertise::seo.advertise_detail_description',
        'phrase_keywords'    => 'advertise::seo.advertise_detail_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_detail_heading',
        'url'                => 'advertise/{id}',
        'item_type'          => 'advertise',
    ],
    [
        'name'               => 'advertise.advertise.edit',
        'phrase_title'       => 'advertise::seo.advertise_edit_title',
        'phrase_description' => 'advertise::seo.advertise_edit_description',
        'phrase_keywords'    => 'advertise::seo.advertise_edit_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_edit_heading',
        'url'                => 'advertise/edit/{id}',
        'item_type'          => 'advertise',
    ],
    [
        'name'               => 'admin.advertise.sponsor_settings',
        'phrase_title'       => 'advertise::seo.advertise_sponsor_settings_title',
        'phrase_description' => 'advertise::seo.advertise_sponsor_settings_description',
        'phrase_keywords'    => 'advertise::seo.advertise_sponsor_settings_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_sponsor_settings_heading',
        'url'                => 'advertise/sponsor/setting',
    ],
    [
        'name'               => 'admin.advertise.browse_sponsor',
        'phrase_title'       => 'advertise::seo.advertise_browse_sponsor_title',
        'phrase_description' => 'advertise::seo.advertise_browse_sponsor_description',
        'phrase_keywords'    => 'advertise::seo.advertise_browse_sponsor_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_browse_sponsor_heading',
        'url'                => 'advertise/sponsor/browse',
    ],
    [
        'name'               => 'advertise.sponsor.create_sponsor_feed',
        'phrase_title'       => 'advertise::seo.advertise_create_sponsor_feed_title',
        'phrase_description' => 'advertise::seo.advertise_create_sponsor_feed_description',
        'phrase_keywords'    => 'advertise::seo.advertise_create_sponsor_feed_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_create_sponsor_feed_heading',
        'url'                => 'advertise/sponsor/feed/add',
    ],
    [
        'name'               => 'advertise.sponsor.create_sponsor_item',
        'phrase_title'       => 'advertise::seo.advertise_create_sponsor_item_title',
        'phrase_description' => 'advertise::seo.advertise_create_sponsor_item_description',
        'phrase_keywords'    => 'advertise::seo.advertise_create_sponsor_item_keywords',
        'phrase_heading'     => 'advertise::seo.advertise_create_sponsor_item_heading',
        'url'                => 'advertise/sponsor/add',
    ],
    [
        'name'                 => 'admin.advertise.advertise_invoice_detail',
        'phrase_title'         => 'advertise::phrase.advertise_invoice_detail',
        'url'                  => 'advertise/invoice/detail/{id}',
        'item_type'            => 'advertise',
        'custom_sharing_route' => 1,
    ],
];
