<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\InAppPurchase\\Http\\Resources\\v1\\Product\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'in_app_purchase.product',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'      => 'MetaFox\\InAppPurchase\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'        => 'form-settings',
        'name'        => 'in_app_purchase',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'title'       => 'core::phrase.settings',
        'url'         => '/in-app-purchase/setting',
        'description' => 'in-app-purchase::phrase.edit_in-app-purchase_setting_desc',
        'type_label'  => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\InAppPurchase\\Http\\Resources\\v1\\Admin\\GoogleServiceAccountForm',
        'type'       => 'form-settings',
        'name'       => 'in_app_purchase.google_service_account',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'in-app-purchase::phrase.google_service_account',
        'url'        => '/in-app-purchase/setting/google-service-account',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'  => 'MetaFox\\InAppPurchase\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'in_app_purchase',
        'version' => 'v1',
    ],
    [
        'driver' => 'MetaFox\\InAppPurchase\\Models\\Product',
        'type'   => 'entity',
        'name'   => 'iap_product',
        'title'  => 'In-App Purchase Product',
    ],
    [
        'driver'     => 'MetaFox\\InAppPurchase\\Http\\Resources\\v1\\Product\\Admin\\UpdateProductForm',
        'type'       => 'form',
        'name'       => 'in_app_purchase.iap_product.update',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\InAppPurchase\\Http\\Resources\\v1\\Gateway\\Admin\\GatewayForm',
        'type'       => 'form',
        'name'       => 'in_app_purchase.gateway.form',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\InAppPurchase\\Http\\Resources\\v1\\Product\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'iap_product',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\InAppPurchase\\Http\\Resources\\v1\\Product\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'iap_product',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
];
