<?php

/* this is auto generated file */

use MetaFox\Event\Support\Browse\Scopes\Event\SortScope;
use MetaFox\Platform\Support\Browse\Browse;

return [
    [
        'menu'     => 'event.event.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'event.event.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'event.event.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'event.event.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'menu'     => 'event.event.filter_menu',
        'name'     => 'upcoming',
        'label'    => 'event::phrase.when.upcoming',
        'ordering' => 5,
        'value'    => 'upcoming',
    ],
    [
        'menu'     => 'event.event.filter_menu',
        'name'     => 'ongoing',
        'label'    => 'event::phrase.when.ongoing',
        'ordering' => 6,
        'value'    => 'ongoing',
    ],
    [
        'menu'     => 'event.view_map.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'event.view_map.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'event.view_map.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'event.view_map.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'menu'     => 'event.view_map.filter_menu',
        'name'     => 'upcoming',
        'label'    => 'event::phrase.when.upcoming',
        'ordering' => 5,
        'value'    => 'upcoming',
    ],
    [
        'menu'     => 'event.view_map.filter_menu',
        'name'     => 'ongoing',
        'label'    => 'event::phrase.when.ongoing',
        'ordering' => 6,
        'value'    => 'ongoing',
    ],
    [
        'params'   => [
            'interestedEvent' => [
                'removeEntity' => true,
            ],
        ],
        'menu'     => 'event.event.interestedMenu',
        'name'     => 'interested',
        'label'    => 'event::phrase.interested',
        'ordering' => 0,
        'value'    => 'interestedEvent',
    ],
    [
        'params'   => [
            'notInterestedEvent' => [
                'removeEntity' => true,
            ],
        ],
        'menu'     => 'event.event.interestedMenu',
        'name'     => 'not_interested',
        'label'    => 'event::phrase.not_interested',
        'ordering' => 2,
        'value'    => 'notInterestedEvent',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_invite'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'invite_link',
        'label'    => 'event::phrase.generate_invite_link',
        'ordering' => 1,
        'value'    => 'event/generateInviteLink',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_invite'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'invites',
        'label'    => 'event::phrase.invite_people_to_come',
        'ordering' => 2,
        'value'    => 'event-invite/addItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mass_invite'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'invite_all',
        'label'    => 'event::phrase.invite_all_group_members',
        'ordering' => 2,
        'value'    => 'event/inviteAllGroupMembers',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'event::phrase.edit_event',
        'ordering' => 3,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
            ['truthy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'event::phrase.approve',
        'ordering' => 4,
        'value'    => 'event/approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_duplicate_event'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'duplicate_event',
        'label'    => 'event::phrase.duplicate_event',
        'ordering' => 4,
        'value'    => 'event/duplicateEvent',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'manage_guest',
        'label'    => 'event::phrase.manage_guest_list',
        'ordering' => 5,
        'value'    => 'event/viewAllGuest',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_view_hosts'],
            ['falsy', 'item.is_ended'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'manage_host',
        'label'    => 'event::phrase.manage_host_list',
        'ordering' => 6,
        'value'    => 'event-host-invite/viewAll',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'manage_privacy_setting',
        'label'    => 'event::phrase.manage_privacy_setting',
        'ordering' => 7,
        'value'    => 'event/updatePrivacySettings',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_host'],
            ['truthy', 'item.extra.can_view_discussion'],
            ['truthy', 'item.extra.can_create_discussion'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'manage_my_pending_post',
        'label'    => 'event::phrase.manage_my_pending_post',
        'ordering' => 8,
        'value'    => 'event/viewMyPendingPost',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'event::phrase.sponsor_in_feed',
        'ordering' => 9,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'event::phrase.sponsor_in_feed',
        'ordering' => 9,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'event::phrase.un_sponsor_in_feed',
        'ordering' => 9,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'event::phrase.sponsor_this_item',
        'ordering' => 10,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'event::phrase.sponsor_this_item',
        'ordering' => 10,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'event::phrase.unsponsor_this_item',
        'ordering' => 10,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_export'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'export',
        'label'    => 'event::phrase.add_to_calendar',
        'ordering' => 12,
        'value'    => 'event/addToCalendar',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 13,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'remove_feature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 14,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'event::phrase.delete',
        'ordering' => 17,
        'value'    => 'deleteItem',
    ],
    [
        'menu'     => 'event.event.manageItemMenu',
        'name'     => 'manage_event',
        'label'    => 'event::phrase.manage_event',
        'ordering' => 1,
        'as'       => 'sidebarHeading',
    ],
    [
        'tab'      => 'general',
        'menu'     => 'event.event.manageItemMenu',
        'name'     => 'general',
        'label'    => 'event::phrase.event_detail',
        'ordering' => 2,
        'to'       => '/event/manage/:id',
    ],
    [
        'tab'      => 'invite_guest',
        'menu'     => 'event.event.manageItemMenu',
        'name'     => 'invite_guest',
        'label'    => 'event::phrase.invite_guests',
        'ordering' => 3,
        'to'       => '/event/manage/:id/invite',
    ],
    [
        'tab'      => 'guest_list',
        'menu'     => 'event.event.manageItemMenu',
        'name'     => 'guest_list',
        'label'    => 'event::phrase.guest_list',
        'ordering' => 4,
        'to'       => '/event/manage/:id/guests',
    ],
    [
        'tab'      => 'mass_email',
        'menu'     => 'event.event.manageItemMenu',
        'name'     => 'mass_email',
        'label'    => 'event::phrase.mass_email',
        'ordering' => 5,
        'to'       => '/event/manage/:id/mass-email',
    ],
    [
        'menu'     => 'event.event.sort_menu',
        'name'     => 'latest',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'event.event.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 2,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'event.event.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 3,
        'value'    => 'most_discussed',
    ],
    [
        'menu'     => 'event.event.sort_menu',
        'name'     => 'most_interested',
        'label'    => 'event::phrase.sort.most_interested',
        'ordering' => 4,
        'value'    => 'most_interested',
    ],
    [
        'menu'     => 'event.event.sort_menu',
        'name'     => 'most_member',
        'label'    => 'event::phrase.sort.most_going',
        'ordering' => 5,
        'value'    => 'most_member',
    ],
    [
        'menu'       => 'event.view_map.sort_menu',
        'name'       => 'new',
        'label'      => 'core::phrase.new',
        'ordering'   => 1,
        'value'      => 'desc',
        'is_deleted' => 1,
    ],
    [
        'menu'     => 'event.view_map.sort_menu',
        'name'     => 'latest',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => Browse::SORT_RECENT,
    ],
    [
        'menu'     => 'event.view_map.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 2,
        'value'    => Browse::SORT_MOST_LIKED,
    ],
    [
        'menu'     => 'event.view_map.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 3,
        'value'    => Browse::SORT_MOST_DISCUSSED,
    ],
    [
        'menu'     => 'event.view_map.sort_menu',
        'name'     => 'most_interested',
        'label'    => 'event::phrase.sort.most_interested',
        'ordering' => 4,
        'value'    => SortScope::SORT_MOST_INTERESTED,
    ],
    [
        'menu'     => 'event.view_map.sort_menu',
        'name'     => 'most_going',
        'label'    => 'event::phrase.sort.most_going',
        'ordering' => 5,
        'value'    => SortScope::SORT_MOST_MEMBER,
    ],
    [
        'menu'     => 'event.view_map.nearest',
        'name'     => 'view_5_nearest',
        'label'    => 'event::phrase.nearest.view_5_nearest_events',
        'ordering' => 1,
        'value'    => 5,
    ],
    [
        'menu'     => 'event.view_map.nearest',
        'name'     => 'view_10_nearest',
        'label'    => 'event::phrase.nearest.view_10_nearest_events',
        'ordering' => 2,
        'value'    => 10,
    ],
    [
        'menu'     => 'event.view_map.nearest',
        'name'     => 'view_15_nearest',
        'label'    => 'event::phrase.nearest.view_15_nearest_events',
        'ordering' => 3,
        'value'    => 15,
    ],
    [
        'menu'     => 'event.view_map.nearest',
        'name'     => 'view_20_nearest',
        'label'    => 'event::phrase.nearest.view_20_nearest_events',
        'ordering' => 4,
        'value'    => 20,
    ],
    [
        'tab'      => 'all',
        'params'   => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'all_events',
        'label'    => 'event::phrase.all_events',
        'ordering' => 1,
        'value'    => 'viewAll',
        'to'       => '/event/all',
    ],
    [
        'tab'      => 'hosted',
        'params'   => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'hosted_events',
        'label'    => 'event::phrase.hosted_events',
        'ordering' => 2,
        'value'    => 'viewHosting',
        'to'       => '/event/hosted',
    ],
    [
        'params'   => [
            'module_name'   => 'event',
            'resource_name' => 'event',
            'useActionName' => false,
        ],
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'my_attending_events',
        'label'    => 'event::phrase.my_attending_events',
        'ordering' => 3,
        'value'    => 'viewInterested',
    ],
    [
        'params'   => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'event::phrase.my_pending_events',
        'ordering' => 3,
        'value'    => 'viewMyPendingEvents',
    ],
    [
        'tab'      => 'friend',
        'params'   => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'event::phrase.friends_events',
        'ordering' => 4,
        'value'    => 'viewFriendEvents',
        'to'       => '/event/friend',
    ],
    [
        'tab'      => 'past',
        'params'   => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'past',
        'label'    => 'event::phrase.my_past_events',
        'ordering' => 5,
        'value'    => 'viewPast',
        'to'       => '/event/past',
    ],
    [
        'tab'      => 'invites',
        'params'   => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'invites',
        'label'    => 'event::phrase.event_invites',
        'ordering' => 6,
        'value'    => 'viewInvites',
        'to'       => '/event/invites',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'and',
            ['truthy', 'acl.event.event.approve'],
        ],
        'params'   => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'menu'     => 'event.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'event::phrase.pending_events',
        'ordering' => 7,
        'value'    => 'viewPendingEvents',
        'to'       => '/event/pending',
    ],
    [
        'tab'      => 'event',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.events',
        'ordering' => 10,
        'to'       => '/event',
        'params'   => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'tab'      => 'event',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.events',
        'ordering' => 10,
        'to'       => '/event',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.event.event.view'],
        ],
        'module_name'   => 'event',
        'resource_name' => 'event',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'event',
        'label'         => 'event::phrase.event_global_search_label',
        'ordering'      => 4,
        'value'         => 'searchGlobalEvent',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.event.event.view'],
        ],
        'module_name'   => 'event',
        'resource_name' => 'event',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'event',
        'label'         => 'event::phrase.event_global_search_label',
        'ordering'      => 4,
        'value'         => 'searchGlobalEvent',
    ],
    [
        'tab'      => 'event',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.event'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'event',
        'label'    => 'event::phrase.events',
        'ordering' => 10,
        'to'       => '/event',
        'params'   => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.event.event.view'],
        ],
        'module_name'   => 'event',
        'resource_name' => 'event',
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'event',
        'label'         => 'event::phrase.event_global_search_label',
        'ordering'      => 4,
        'value'         => 'searchGlobalEvent',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
            ['truthy', 'item.extra.can_invite'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'invite_link',
        'label'    => 'event::phrase.generate_invite_link',
        'ordering' => 1,
        'value'    => 'event/generateInviteLink',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_invite'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'invites',
        'label'    => 'event::phrase.invite_people_to_come',
        'ordering' => 2,
        'value'    => 'event-invite/addItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mass_invite'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'invite_all',
        'label'    => 'event::phrase.invite_all_group_members',
        'ordering' => 2,
        'value'    => 'event/inviteAllGroupMembers',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'event::phrase.edit_event',
        'ordering' => 3,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_approve'],
            ['truthy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'event::phrase.approve',
        'ordering' => 4,
        'value'    => 'event/approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_duplicate_event'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'duplicate_event',
        'label'    => 'event::phrase.duplicate_event',
        'ordering' => 4,
        'value'    => 'event/duplicateEvent',
        'icon'     => 'ico-copy-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mass_email'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'manage_guest',
        'label'    => 'event::phrase.manage_guest_list',
        'ordering' => 5,
        'value'    => 'event/viewAllGuest',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_mass_email'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'mass_email_guest',
        'label'    => 'event::phrase.mass_email_guest',
        'ordering' => 6,
        'value'    => 'event/massEmailEvent',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_view_hosts'],
            ['falsy', 'item.is_ended'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'manage_host',
        'label'    => 'event::phrase.manage_host_list',
        'ordering' => 7,
        'value'    => 'event-host-invite/viewAll',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'manage_privacy_setting',
        'label'    => 'event::phrase.manage_privacy_setting',
        'ordering' => 8,
        'value'    => 'event/updatePrivacySettings',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_host'],
            ['truthy', 'item.extra.can_view_discussion'],
            ['truthy', 'item.extra.can_create_discussion'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'manage_my_pending_post',
        'label'    => 'event::phrase.manage_my_pending_post',
        'ordering' => 10,
        'value'    => 'event/viewMyPendingPost',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'event::phrase.sponsor_in_feed',
        'ordering' => 11,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'event::phrase.sponsor_in_feed',
        'ordering' => 11,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'event::phrase.un_sponsor_in_feed',
        'ordering' => 11,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'event::phrase.sponsor_this_item',
        'ordering' => 12,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'event::phrase.sponsor_this_item',
        'ordering' => 12,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'event::phrase.unsponsor_this_item',
        'ordering' => 12,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'export',
        'label'    => 'event::phrase.add_to_calendar',
        'ordering' => 12,
        'value'    => 'event/addToCalendar',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 13,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'remove_feature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 14,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'style'    => 'danger',
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'event::phrase.delete',
        'ordering' => 16,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'event',
        'label'     => 'event::phrase.events',
        'ordering'  => 12,
        'value'     => '',
        'to'        => '/event',
        'as'        => 'item',
        'icon'      => 'calendar',
        'iconColor' => '#ff5319',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'event.event.headerItemActionOnUserProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'acl.event.event.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'       => 'event.event.headerItemActionOnUserProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'event.event.headerItemActionOnPageProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'acl.event.event.create'],
            ['truthy', 'item.profile_settings.event_share_events'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'       => 'event.event.headerItemActionOnPageProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'event.event.headerItemActionOnGroupProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'acl.event.event.create'],
            ['truthy', 'item.profile_settings.event_share_events'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'       => 'event.event.headerItemActionOnGroupProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'event',
            'resource_name' => 'event',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'event.event.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'event.event.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 9,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'params'   => [
            'interestedEvent' => [
                'removeEntity' => true,
            ],
        ],
        'menu'     => 'event.event.rsvpMenu',
        'name'     => 'interested',
        'label'    => 'event::phrase.interested',
        'ordering' => 0,
        'value'    => 'interestedEvent',
    ],
    [
        'color'    => 'primary',
        'params'   => [
            'joinEvent' => [
                'removeEntity' => true,
            ],
        ],
        'menu'     => 'event.event.rsvpMenu',
        'name'     => 'going',
        'label'    => 'event::phrase.going',
        'ordering' => 1,
        'value'    => 'joinEvent',
    ],
    [
        'params'   => [
            'notInterestedEvent' => [
                'removeEntity' => true,
            ],
        ],
        'menu'     => 'event.event.rsvpMenu',
        'name'     => 'not_interested',
        'label'    => 'event::phrase.not_interested',
        'ordering' => 2,
        'value'    => 'notInterestedEvent',
    ],
];
