<?php

namespace MetaFox\Video\Support\Browse\Scopes\Video;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use MetaFox\Platform\Support\Browse\Browse;
use MetaFox\Platform\Support\Browse\Contracts\HasAlphabetSort;
use MetaFox\Platform\Support\Browse\Scopes\SortScope as BaseScope;
use MetaFox\Platform\Support\Browse\Traits\AlphabetSortTrait;

/**
 * Class SortScope.
 */
class SortScope extends BaseScope implements HasAlphabetSort
{
    use AlphabetSortTrait;

    public const SORT_ALPHABETICAL_COLUMN = 'title';
    public const SORT_VERIFIED_COLUMN     = 'verified_at';

    /**
     * @return array<int, string>
     */
    public static function getAllowSort(): array
    {
        return [
            Browse::SORT_RECENT,
            self::SORT_VERIFIED_COLUMN,
            Browse::SORT_LATEST,
            Browse::SORT_MOST_LIKED,
            Browse::SORT_MOST_VIEWED,
            Browse::SORT_MOST_DISCUSSED,
            Browse::SORT_A_TO_Z,
            Browse::SORT_Z_TO_A,
        ];
    }

    public function getAlphabetSortColumn(): string
    {
        return self::SORT_ALPHABETICAL_COLUMN;
    }

    public function apply(Builder $builder, Model $model)
    {
        parent::apply($builder, $model); // TODO: Change the autogenerated stub
        $table = $model->getTable();

        switch ($this->getSort()) {
            case self::SORT_VERIFIED_COLUMN:
                $builder->orderBy("$table.verified_at", $this->getSortType());
        }
    }
}
