<?php

return [
    [
        'tab'      => 'items',
        'menu'     => 'featured.sidebarMenu',
        'name'     => 'items',
        'label'    => 'core::web.items',
        'ordering' => 1,
        'to'       => '/featured',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'featured',
            'resource_name' => 'featured_item',
        ],
        'value' => 'viewAll',
    ],
    [
        'tab'      => 'invoices',
        'menu'     => 'featured.sidebarMenu',
        'name'     => 'invoices',
        'label'    => 'core::web.invoices',
        'ordering' => 2,
        'to'       => '/featured/invoice',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'featured',
            'resource_name' => 'featured_invoice',
        ],
        'value' => 'viewAll',
    ],

    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_payment'],
        ],
        'menu'     => 'featured.featured_item.itemActionMenu',
        'name'     => 'payment',
        'label'    => 'featured::phrase.pay_price',
        'ordering' => 1,
        'value'    => 'featured/paymentItem',
        'icon'     => 'credit-card',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_cancel'],
        ],
        'menu'     => 'featured.featured_item.itemActionMenu',
        'name'     => 'cancel',
        'label'    => 'core::phrase.cancel',
        'ordering' => 2,
        'value'    => 'featured/cancelItem',
        'icon'     => 'close-circle',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'featured.featured_item.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'core::phrase.delete',
        'ordering' => 3,
        'value'    => 'deleteItem',
        'icon'     => 'trash',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_payment'],
        ],
        'menu'     => 'featured.featured_item.detailActionMenu',
        'name'     => 'payment',
        'label'    => 'featured::phrase.pay_price',
        'ordering' => 1,
        'value'    => 'featured/paymentItem',
        'icon'     => 'credit-card',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_cancel'],
        ],
        'menu'     => 'featured.featured_item.detailActionMenu',
        'name'     => 'cancel',
        'label'    => 'core::phrase.cancel',
        'ordering' => 2,
        'value'    => 'featured/cancelItem',
        'icon'     => 'close-circle',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'featured.featured_item.detailActionMenu',
        'name'     => 'delete',
        'label'    => 'core::phrase.delete',
        'ordering' => 3,
        'value'    => 'deleteItem',
        'icon'     => 'trash',
    ],

    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_payment'],
        ],
        'menu'     => 'featured.featured_invoice.itemActionMenu',
        'name'     => 'payment',
        'label'    => 'featured::phrase.pay_now',
        'ordering' => 1,
        'value'    => 'featured/paymentItem',
        'icon'     => 'credit-card',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_cancel'],
        ],
        'menu'     => 'featured.featured_invoice.itemActionMenu',
        'name'     => 'cancel',
        'label'    => 'core::phrase.cancel',
        'ordering' => 2,
        'value'    => 'featured/cancelItem',
        'icon'     => 'close-circle',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_payment'],
        ],
        'menu'     => 'featured.featured_invoice.detailActionMenu',
        'name'     => 'payment',
        'label'    => 'featured::phrase.pay_now',
        'ordering' => 1,
        'value'    => 'featured/paymentItem',
        'icon'     => 'credit-card',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_cancel'],
        ],
        'menu'     => 'featured.featured_invoice.detailActionMenu',
        'name'     => 'cancel',
        'label'    => 'core::phrase.cancel',
        'ordering' => 2,
        'value'    => 'featured/cancelItem',
        'icon'     => 'close-circle',
    ],
    [
        'showWhen' => [
            'and',
            ['gte', 'apiVersion', 'v1.10'],
        ],
        'menu'      => 'core.helperMenu',
        'name'      => 'featured',
        'label'     => 'featured::phrase.app_name',
        'ordering'  => 2,
        'to'        => '/featured',
        'iconColor' => '#686868',
        'as'        => 'helper',
        'icon'      => 'diamond',
    ],
];
