<?php

/* this is auto generated file */
return [
    [
        'type'       => 'form-settings',
        'name'       => 'mux.video',
        'title'      => 'mux::phrase.mux_video_config',
        'driver'     => 'MetaFox\Mux\\Http\\Resources\\v1\\Admin\\VideoSettingForm',
        'url'        => '/mux/setting/video',
        'resolution' => 'admin',
        'version'    => 'v1',
    ],
    [
        'type'       => 'form-settings',
        'name'       => 'mux.story',
        'title'      => 'mux::phrase.mux_story_config',
        'driver'     => 'MetaFox\Mux\\Http\\Resources\\v1\\Admin\\StorySettingForm',
        'url'        => '/mux/setting/story',
        'resolution' => 'admin',
        'version'    => 'v1',
    ],
    [
        'type'       => 'form-settings',
        'name'       => 'mux.livestreaming',
        'title'      => 'mux::phrase.mux_live_streams_config',
        'driver'     => 'MetaFox\Mux\\Http\\Resources\\v1\\Admin\\LiveStreamsSettingForm',
        'url'        => '/mux/setting/livestreaming',
        'resolution' => 'admin',
        'version'    => 'v1',
    ],
    [
        'type'    => 'package-setting',
        'name'    => 'mux',
        'driver'  => 'MetaFox\Mux\\Http\\Resources\\v1\\PackageSetting',
        'version' => 'v1',
    ],
    [
        'driver'     => 'MetaFox\\Mux\\Form\\Html\\MuxPlayer',
        'type'       => 'form-field',
        'name'       => 'muxPlayer',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'version'    => 'v1',
    ],
    [
        'type'       => 'video-service',
        'name'       => 'mux',
        'driver'     => 'MetaFox\\Mux\\Support\\Providers\\Mux',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'mux::phrase.mux_app',
        'url'        => '/mux/setting/video',
    ],
    [
        'type'       => 'story-service',
        'name'       => 'mux',
        'driver'     => 'MetaFox\\Mux\\Support\\Providers\\Mux',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'mux::phrase.mux_app',
        'url'        => '/mux/setting/story',
    ],
    [
        'type'       => 'livestreaming-service',
        'name'       => 'mux',
        'driver'     => 'MetaFox\\Mux\\Support\\Providers\\Mux',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'mux::phrase.mux_app',
        'url'        => '/mux/setting/livestreaming',
    ],
];
