<?php
/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'page',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'page.category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'page.category.category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => '',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageClaim\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'page.claim',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\CustomField\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'page.field',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\CustomSection\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'page.section',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Models\\Page',
        'type'       => 'entity',
        'name'       => 'page',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Pages',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Models\\Category',
        'type'       => 'entity',
        'name'       => 'page_category',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Page Categories',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Models\\PageClaim',
        'type'       => 'entity',
        'name'       => 'page_claim',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Models\\PageHistory',
        'type'       => 'entity',
        'name'       => 'page_history',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Models\\PageInvite',
        'type'       => 'entity',
        'name'       => 'page_invite',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Models\\PageMember',
        'type'       => 'entity',
        'name'       => 'page_member',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Models\\Page',
        'type'       => 'entity-content',
        'name'       => 'page',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Pages',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Models\\Page',
        'type'       => 'entity-user',
        'name'       => 'page',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Content Type',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageClaim\\StorePageClaimMobileForm',
        'type'       => 'form',
        'name'       => 'page.claim.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageClaim\\StorePageClaimForm',
        'type'       => 'form',
        'name'       => 'page.claim.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageClaim\\UpdatePageClaimMobileForm',
        'type'       => 'form',
        'name'       => 'page.claim.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageClaim\\UpdatePageClaimForm',
        'type'       => 'form',
        'name'       => 'page.claim.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\CustomField\\Admin\\CreateFieldForm',
        'type'       => 'form',
        'name'       => 'page.field.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\CustomField\\Admin\\EditFieldForm',
        'type'       => 'form',
        'name'       => 'page.field.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\AdditionalInformationMobileForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.additional_information',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\AdditionalInformationForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.additional_information',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateCategoryForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.category_id',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateCategoryMobileForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.category_id',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateExternalLinkMobileForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.external_link',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateExternalLinkForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.external_link',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateLandingPageMobileForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.landing_page',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateLandingPageForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.landing_page',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateLocationForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.location',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateLocationMobileForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.location',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateNameForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.name',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateNameMobileForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.name',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateProfileNameForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.profile_name',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateProfileNameMobileForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.profile_name',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateDescriptionMobileForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.text',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Setting\\UpdateDescriptionForm',
        'type'       => 'form',
        'name'       => 'page.info_setting.text',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\IntegratedModule\\IntegratedModuleForm',
        'type'       => 'form',
        'name'       => 'page.integrated_module',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\IntegratedModule\\IntegratedModuleMobileForm',
        'type'       => 'form',
        'name'       => 'page.integrated_module',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageInvite\\StoreInviteMobileForm',
        'type'       => 'form',
        'name'       => 'page.invite.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\AboutMobileForm',
        'type'       => 'form',
        'name'       => 'page.page.about',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\InfoMobileForm',
        'type'       => 'form',
        'name'       => 'page.page.info',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PermissionPageMobileForm',
        'type'       => 'form',
        'name'       => 'page.page.permission',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\CreateMobileForm',
        'type'       => 'form',
        'name'       => 'page.page.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Block\\BlockMemberMobileForm',
        'type'       => 'form',
        'name'       => 'page.page_block.block_member',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Block\\BlockMemberForm',
        'type'       => 'form',
        'name'       => 'page.page_block.block_member',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\Admin\\DestroyCategoryForm',
        'type'       => 'form',
        'name'       => 'page.page_category.destroy',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\Admin\\StoreCategoryForm',
        'type'       => 'form',
        'name'       => 'page.page_category.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\Admin\\UpdateCategoryForm',
        'type'       => 'form',
        'name'       => 'page.page_category.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageMember\\ReassignOwnerMobileForm',
        'type'       => 'form',
        'name'       => 'page.page_member.reassign_owner',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageMember\\RemoveMemberForm',
        'type'       => 'form',
        'name'       => 'page.page_member.remove_member',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageMember\\RemoveMemberMobileForm',
        'type'       => 'form',
        'name'       => 'page.page_member.remove_member',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\SearchPageMobileForm',
        'type'       => 'form',
        'name'       => 'page.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\SearchPageForm',
        'type'       => 'form',
        'name'       => 'page.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Admin\\SearchPageForm',
        'type'       => 'form',
        'name'       => 'page.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\SearchMemberMobileForm',
        'type'       => 'form',
        'name'       => 'page.searchMember',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\SearchInPageMobileForm',
        'type'       => 'form',
        'name'       => 'page.search_in',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\SearchInPageForm',
        'type'       => 'form',
        'name'       => 'page.search_in',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\SearchInOwnerMobileForm',
        'type'       => 'form',
        'name'       => 'page.search_in_owner',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\CustomSection\\Admin\\CreateSectionForm',
        'type'       => 'form',
        'name'       => 'page.section.store',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\CustomSection\\Admin\\EditSectionForm',
        'type'       => 'form',
        'name'       => 'page.section.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\CreatePageForm',
        'type'       => 'form',
        'name'       => 'page.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\EditPageForm',
        'type'       => 'form',
        'name'       => 'page.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageClaim\\SearchPageClaimMobileForm',
        'type'       => 'form',
        'name'       => 'page_claim.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageClaim\\SearchPageClaimForm',
        'type'       => 'form',
        'name'       => 'page_claim.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'page',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/page/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Jobs\\DeletePageCategoryJob',
        'type'       => 'job',
        'name'       => 'MetaFox\\Page\\Jobs\\DeletePageCategoryJob',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Job',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PageEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'page.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PageItemCollection',
        'type'       => 'json-collection',
        'name'       => 'page.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PageSimpleCollection',
        'type'       => 'json-collection',
        'name'       => 'page.simple',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PageSuggestionCollection',
        'type'       => 'json-collection',
        'name'       => 'page.suggestion',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\PageCategoryEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'page_category.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\PageCategoryItemCollection',
        'type'       => 'json-collection',
        'name'       => 'page_category.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageInvite\\PageInviteEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'page_invite.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageInvite\\PageInviteItemCollection',
        'type'       => 'json-collection',
        'name'       => 'page_invite.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageMember\\PageMemberEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'page_member.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageMember\\PageMemberItemCollection',
        'type'       => 'json-collection',
        'name'       => 'page_member.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PageDetail',
        'type'       => 'json-resource',
        'name'       => 'page.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PageEmbed',
        'type'       => 'json-resource',
        'name'       => 'page.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PageInfo',
        'type'       => 'json-resource',
        'name'       => 'page.info',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PageItem',
        'type'       => 'json-resource',
        'name'       => 'page.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PagePreview',
        'type'       => 'json-resource',
        'name'       => 'page.preview',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PagePropertiesSchema',
        'type'       => 'json-resource',
        'name'       => 'page.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PageSimple',
        'type'       => 'json-resource',
        'name'       => 'page.simple',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\PageSuggestion',
        'type'       => 'json-resource',
        'name'       => 'page.suggestion',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\PageCategoryDetail',
        'type'       => 'json-resource',
        'name'       => 'page_category.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\PageCategoryEmbed',
        'type'       => 'json-resource',
        'name'       => 'page_category.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\PageCategoryItem',
        'type'       => 'json-resource',
        'name'       => 'page_category.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageInvite\\PageInviteDetail',
        'type'       => 'json-resource',
        'name'       => 'page_invite.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageInvite\\PageInviteEmbed',
        'type'       => 'json-resource',
        'name'       => 'page_invite.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageInvite\\PageInviteItem',
        'type'       => 'json-resource',
        'name'       => 'page_invite.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageMember\\PageMemberDetail',
        'type'       => 'json-resource',
        'name'       => 'page_member.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageMember\\PageMemberEmbed',
        'type'       => 'json-resource',
        'name'       => 'page_member.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageMember\\PageMemberItem',
        'type'       => 'json-resource',
        'name'       => 'page_member.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Notifications\\ClaimNotification',
        'type'       => 'notification',
        'name'       => 'claim_page',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Notification',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Notifications\\PageInvite',
        'type'       => 'notification',
        'name'       => 'page_invite',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Notification',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'page',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Page\\Policies\\CategoryPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Page\\Models\\Category',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Policies\\PagePolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Page\\Models\\Page',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Policies\\PageMemberPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\Page\\Models\\PageMember',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'page',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Block\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'page_block',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Mobile Action',
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageClaim\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'page_claim',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\IntegratedModule\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'page_integrated',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageInvite\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'page_invite',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageMember\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'page_member',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Mobile Action',
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'page',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Page\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'page',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\Block\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'page_block',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'page_category',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageCategory\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'page_category',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageClaim\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'page_claim',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\IntegratedModule\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'page_integrated',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageInvite\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'page_invite',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Http\\Resources\\v1\\PageMember\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'page_member',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Page\\Support\\SEO\\PageSchema',
        'type'       => 'schema-structured',
        'name'       => 'page',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
