<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'livestreaming.live_video',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\StreamingService\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'livestreaming.streaming_service',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Models\\LiveVideo',
        'type'       => 'entity',
        'name'       => 'live_video',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Live Videos',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Models\\NotificationSetting',
        'type'       => 'entity',
        'name'       => 'livestreaming_notification_setting',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Live Videos Notification Setting',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Models\\PlaybackData',
        'type'       => 'entity',
        'name'       => 'livestreaming_playback_data',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Live Videos Playback Data',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Models\\UserStreamKey',
        'type'       => 'entity',
        'name'       => 'livestreaming_user_stream_key',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Live Videos Stream Key',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\ManageLiveVideoForm',
        'type'       => 'form',
        'name'       => 'live_video.edit_livestream',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\SearchLiveVideoForm',
        'type'       => 'form',
        'name'       => 'live_video.search',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\Admin\\SearchLiveVideoForm',
        'type'       => 'form',
        'name'       => 'live_video.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\Admin\\SearchLiveVideoForm',
        'type'       => 'form',
        'name'       => 'live_video.search',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\SearchLiveVideoMobileForm',
        'type'       => 'form',
        'name'       => 'live_video.search',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\SearchInOwnerMobileForm',
        'type'       => 'form',
        'name'       => 'live_video.search_in_owner',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => true,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\StoreLiveVideoForm',
        'type'       => 'form',
        'name'       => 'live_video.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\StoreLiveVideoWebcamForm',
        'type'       => 'form',
        'name'       => 'live_video.store_webcam',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\UpdateLiveVideoForm',
        'type'       => 'form',
        'name'       => 'live_video.update',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\StoreLiveVideoMobileForm',
        'type'       => 'form',
        'name'       => 'livestreaming.live_video.store',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\UpdateLiveVideoMobileForm',
        'type'       => 'form',
        'name'       => 'livestreaming.live_video.update',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'      => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'        => 'form-settings',
        'name'        => '',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'is_active'   => true,
        'is_preload'  => false,
        'title'       => 'core::phrase.settings',
        'url'         => '/livestreaming/setting',
        'description' => '::phrase.edit__setting_desc',
        'type_label'  => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'livestreaming',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/livestreaming/setting',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\Admin\\ServiceAccountForm',
        'type'       => 'form-settings',
        'name'       => 'livestreaming.service_account',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'livestreaming::phrase.firebase_service_account',
        'url'        => '/livestreaming/setting/service-account',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\LiveVideoEmbedCollection',
        'type'       => 'json-collection',
        'name'       => 'live_video.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\LiveVideoItemCollection',
        'type'       => 'json-collection',
        'name'       => 'live_video.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\LiveVideoDetail',
        'type'       => 'json-resource',
        'name'       => 'live_video.detail',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\LiveVideoEmbed',
        'type'       => 'json-resource',
        'name'       => 'live_video.embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\FeedEmbed',
        'type'       => 'json-resource',
        'name'       => 'live_video.feed_embed',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\LiveVideoItem',
        'type'       => 'json-resource',
        'name'       => 'live_video.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\LiveVideoPropertiesSchema',
        'type'       => 'json-resource',
        'name'       => 'live_video.properties_schema',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => '',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Policies\\LiveVideoPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\LiveStreaming\\Models\\LiveVideo',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'live_video',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'live_video',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Http\\Resources\\v1\\LiveVideo\\Admin\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'live_video',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\LiveStreaming\\Support\\SEO\\LiveVideoSchema',
        'type'       => 'schema-structured',
        'name'       => 'live_video',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
