<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.friend.friend_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'friend/setting',
    ],
    [
        'name'         => 'admin.friend.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'friend/permission',
    ],
    [
        'name'               => 'friend.friend',
        'phrase_title'       => 'friend::seo.friend_search_title',
        'phrase_description' => 'friend::seo.friend_search_description',
        'phrase_keywords'    => 'friend::seo.friend_search_keywords',
        'phrase_heading'     => 'friend::seo.friend_search_heading',
        'url'                => 'friend/search',
        'item_type'          => 'friend',
    ],
    [
        'name'               => 'friend.friend.landing',
        'phrase_title'       => 'friend::seo.friend_landing_title',
        'phrase_description' => 'friend::seo.friend_landing_description',
        'phrase_keywords'    => 'friend::seo.friend_landing_keywords',
        'phrase_heading'     => 'friend::seo.friend_landing_heading',
        'url'                => 'friend',
        'item_type'          => 'friend',
    ],
    [
        'name'               => 'friend.friend_list.store',
        'phrase_title'       => 'friend::seo.friend_store_list_title_title',
        'phrase_description' => 'friend::seo.friend_store_list_title_description',
        'phrase_keywords'    => 'friend::seo.friend_store_list_title_keywords',
        'phrase_heading'     => 'friend::seo.friend_store_list_title_heading',
        'url'                => 'friend/list/add',
        'item_type'          => 'friend',
    ],
    [
        'name'               => 'friend.friend_request.send_request',
        'phrase_title'       => 'friend::seo.friend_friend_send_request_title',
        'phrase_description' => 'friend::seo.friend_friend_send_request_description',
        'phrase_keywords'    => 'friend::seo.friend_friend_send_request_keywords',
        'phrase_heading'     => 'friend::seo.friend_friend_send_request_heading',
        'url'                => 'friend/send-requests',
        'item_type'          => 'friend',
    ],
    [
        'name'               => 'friend.friend.birthday',
        'phrase_title'       => 'friend::seo.friend_birthday_title',
        'phrase_description' => 'friend::seo.friend_birthday_description',
        'phrase_keywords'    => 'friend::seo.friend_birthday_keywords',
        'phrase_heading'     => 'friend::seo.friend_birthday_heading',
        'url'                => 'friend/birthday',
        'item_type'          => 'friend',
    ],
    [
        'name'               => 'friend.master_detail',
        'phrase_title'       => 'friend::seo.friend_master_detail_title',
        'phrase_description' => 'friend::seo.friend_master_detail_description',
        'phrase_keywords'    => 'friend::seo.friend_master_detail_keywords',
        'phrase_heading'     => 'friend::seo.friend_master_detail_heading',
        'url'                => 'friend/requests',
        'item_type'          => 'friend',
    ],
    [
        'name'               => 'friend.friend_list.detail',
        'phrase_title'       => 'friend::seo.friend_list_detail_title',
        'phrase_description' => 'friend::seo.friend_list_detail_description',
        'phrase_keywords'    => 'friend::seo.friend_list_detail_keywords',
        'phrase_heading'     => 'friend::seo.friend_list_detail_heading',
        'url'                => 'friend/list/{id}',
        'item_type'          => 'friend_list',
    ],
];
