<?php

/* this is auto generated file */
return [
    [
        'placement' => 'bottom',
        'content'   => [
            'component' => 'messages.ui.MessagesPopper',
        ],
        'menu'      => 'core.headerSubMenu',
        'name'      => 'chat_message',
        'label'     => 'chat::phrase.messages',
        'ordering'  => 3,
        'as'        => 'popover',
        'icon'      => 'ico-comments-o',
        'to'        => '/messages',
        'showWhen'  => [
            'and',
            ['truthy', 'setting.chat.is_active'],
            ['falsy', 'setting.chatplus.server'],
            ['neq', 'params.appName', 'chat'],
        ],
    ],
    [
        'menu'                 => 'core.primaryMenu',
        'name'                 => 'chat',
        'label'                => 'chat::phrase.messages',
        'ordering'             => 4,
        'icon'                 => 'ico-comments',
        'to'                   => '/messages',
        'is_active'            => 1,
        'exclude_from_sitemap' => 1,
        'showWhen'             => [
            'and',
            ['truthy', 'setting.chat.is_active'],
            ['falsy', 'setting.chatplus.server'],
        ],
    ],
    [
        'showWhen' => [],
        'menu'     => 'chat.message.itemActionMenu',
        'name'     => 'reply',
        'label'    => 'chat::web.reply',
        'ordering' => 1,
        'value'    => 'closeMenu, chat/replyMessage',
        'icon'     => 'ico-reply-o',
        'testid'   => 'replyMessage',
    ],
    [
        'showWhen' => [
            'truthy', 'item.message',
        ],
        'menu'     => 'chat.message.itemActionMenu',
        'name'     => 'copy',
        'label'    => 'chat::web.copy',
        'ordering' => 2,
        'value'    => 'closeMenu, chat/copyMessage',
        'icon'     => 'ico-copy-o',
        'testid'   => 'copyMessage',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.permissions.can_edit'],
            ['falsy', 'isSearch'],
        ],
        'menu'     => 'chat.message.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'chat::web.edit',
        'ordering' => 3,
        'value'    => 'closeMenu, chat/editMessage',
        'icon'     => 'ico-pencilline-o',
        'testid'   => 'editMessage',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.permissions.can_delete'],
            ['falsy', 'isSearch'],
        ],
        'menu'      => 'chat.message.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'core::phrase.delete',
        'ordering'  => 4,
        'value'     => 'closeMenu, chat/deleteMessage',
        'icon'      => 'ico-trash-o',
        'className' => 'item-delete',
        'testid'    => 'deleteMessage',
    ],
    [
        'showWhen' => [],
        'menu'     => 'chat.message.buddyMiniChatMenu',
        'icon'     => 'ico-search-o',
        'value'    => 'chat/room/toggleSearching',
        'testid'   => 'toggleSearching',
        'label'    => 'chat::phrase.toggle_search',
        'name'     => 'toggle_search',
    ],
    [
        'showWhen' => [],
        'menu'     => 'chat.message.buddyMiniChatMenu',
        'label'    => 'chat::phrase.open_in_messenger',
        'icon'     => 'ico-comment-square-dots-o',
        'value'    => 'chat/room/openInMessenger',
        'testid'   => 'openInMessenger',
        'name'     => 'open_in_messenger',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'menu'     => 'chat.message.buddyMiniChatMenu',
        'label'    => 'chat::phrase.delete',
        'icon'     => 'ico-trash-o',
        'value'    => 'closeMenu, chat/room/deleteRoom',
        'testid'   => 'deleteRoom',
        'name'     => 'delete',
    ],
    [
        'showWhen' => [],
        'menu'     => 'chat.message.buddyMiniChatMenu',
        'label'    => 'chat::phrase.more',
        'icon'     => 'ico-dottedmore-vertical-o',
        'testid'   => 'more',
        'behavior' => 'more',
        'name'     => 'more',
    ],
    [
        'showWhen' => [],
        'menu'     => 'chat.message.buddyMiniChatMenu',
        'label'    => 'chat::phrase.minimize',
        'icon'     => 'ico-minus',
        'value'    => 'closeMenu, chat/room/toggle',
        'testid'   => 'minimize',
        'behavior' => 'close',
        'name'     => 'minimize',
    ],
    [
        'showWhen' => [],
        'menu'     => 'chat.message.buddyMiniChatMenu',
        'label'    => 'chat::phrase.close',
        'icon'     => 'ico-close',
        'value'    => 'closeMenu, chat/closePanel',
        'testid'   => 'closePanel',
        'behavior' => 'close',
        'name'     => 'close',
    ],
];
