<?php

/* this is auto generated file */
return [
    [
        'name'         => 'admin.quiz.permissions',
        'phrase_title' => 'core::phrase.permissions',
        'url'          => 'quiz/permission',
    ],
    [
        'name'         => 'admin.quiz.quiz_setting',
        'phrase_title' => 'core::phrase.settings',
        'url'          => 'quiz/setting',
    ],
    [
        'name'         => 'admin.quiz.browse',
        'phrase_title' => 'quiz::phrase.manage_quizzes',
        'url'          => 'quiz/quiz/browse',
    ],
    [
        'name'               => 'group.profile.quiz',
        'phrase_title'       => 'quiz::seo.group_profile_quiz_title',
        'phrase_description' => 'quiz::seo.group_profile_quiz_description',
        'phrase_keywords'    => 'quiz::seo.group_profile_quiz_keywords',
        'phrase_heading'     => 'quiz::seo.group_profile_quiz_heading',
        'url'                => 'group/{id}/quiz',
        'item_type'          => 'group',
        'resource_name'      => 'group',
    ],
    [
        'name'               => 'page.profile.quiz',
        'phrase_title'       => 'quiz::seo.page_profile_quiz_title',
        'phrase_description' => 'quiz::seo.page_profile_quiz_description',
        'phrase_keywords'    => 'quiz::seo.page_profile_quiz_keywords',
        'phrase_heading'     => 'quiz::seo.page_profile_quiz_heading',
        'url'                => 'page/{id}/quiz',
        'item_type'          => 'page',
        'resource_name'      => 'page',
    ],
    [
        'name'               => 'quiz.browse_all_quiz',
        'phrase_title'       => 'quiz::seo.quiz_browse_all_title',
        'phrase_description' => 'quiz::seo.quiz_browse_all_description',
        'phrase_keywords'    => 'quiz::seo.quiz_browse_all_keywords',
        'phrase_heading'     => 'quiz::seo.quiz_browse_all_heading',
        'url'                => 'quiz/all',
        'item_type'          => 'quiz',
    ],
    [
        'name'               => 'quiz.browse_friend_quiz',
        'phrase_title'       => 'quiz::seo.quiz_browse_friend_title',
        'phrase_description' => 'quiz::seo.quiz_browse_friend_description',
        'phrase_keywords'    => 'quiz::seo.quiz_browse_friend_keywords',
        'phrase_heading'     => 'quiz::seo.quiz_browse_friend_heading',
        'url'                => 'quiz/friend',
        'item_type'          => 'quiz',
    ],
    [
        'name'               => 'quiz.browse_my_pending_quiz',
        'phrase_title'       => 'quiz::seo.quiz_browse_my_pending_title',
        'phrase_description' => 'quiz::seo.quiz_browse_my_pending_description',
        'phrase_keywords'    => 'quiz::seo.quiz_browse_my_pending_keywords',
        'phrase_heading'     => 'quiz::seo.quiz_browse_my_pending_heading',
        'url'                => 'quiz/my-pending',
        'item_type'          => 'quiz',
    ],
    [
        'name'               => 'quiz.browse_pending_quiz',
        'phrase_title'       => 'quiz::seo.quiz_browse_pending_title',
        'phrase_description' => 'quiz::seo.quiz_browse_pending_description',
        'phrase_keywords'    => 'quiz::seo.quiz_browse_pending_keywords',
        'phrase_heading'     => 'quiz::seo.quiz_browse_pending_heading',
        'url'                => 'quiz/pending',
        'item_type'          => 'quiz',
    ],
    [
        'name'                 => 'quiz.quiz.create',
        'phrase_title'         => 'quiz::seo.quiz_create_title',
        'phrase_description'   => 'quiz::seo.quiz_create_description',
        'phrase_keywords'      => 'quiz::seo.quiz_create_keywords',
        'phrase_heading'       => 'quiz::seo.quiz_create_heading',
        'url'                  => 'quiz/add',
        'item_type'            => 'quiz',
        'custom_sharing_route' => 1,
    ],
    [
        'name'                 => 'quiz.quiz.edit',
        'phrase_title'         => 'quiz::seo.quiz_edit_title',
        'phrase_description'   => 'quiz::seo.quiz_edit_description',
        'phrase_keywords'      => 'quiz::seo.quiz_edit_keywords',
        'phrase_heading'       => 'quiz::seo.quiz_edit_heading',
        'url'                  => 'quiz/edit/{id}',
        'item_type'            => 'quiz',
        'custom_sharing_route' => 1,
    ],
    [
        'name'               => 'quiz.quiz.landing',
        'phrase_title'       => 'quiz::seo.quiz_landing_title',
        'phrase_description' => 'quiz::seo.quiz_landing_description',
        'phrase_keywords'    => 'quiz::seo.quiz_landing_keywords',
        'phrase_heading'     => 'quiz::seo.quiz_landing_heading',
        'url'                => 'quiz',
        'item_type'          => 'quiz',
    ],
    [
        'name'               => 'quiz.quiz.my',
        'phrase_title'       => 'quiz::seo.quiz_browse_my_title',
        'phrase_description' => 'quiz::seo.quiz_browse_my_description',
        'phrase_keywords'    => 'quiz::seo.quiz_browse_my_keywords',
        'phrase_heading'     => 'quiz::seo.quiz_browse_my_heading',
        'url'                => 'quiz/my',
        'item_type'          => 'quiz',
    ],
    [
        'name'               => 'quiz.quiz.view_detail',
        'phrase_title'       => 'quiz::seo.quiz_view_detail_title',
        'phrase_description' => 'quiz::seo.quiz_view_detail_description',
        'phrase_keywords'    => 'quiz::seo.quiz_view_detail_keywords',
        'phrase_heading'     => 'quiz::seo.quiz_view_detail_heading',
        'url'                => 'quiz/{id}/{slug?}',
        'item_type'          => 'quiz',
        'resource_name'      => 'quiz',
    ],
    [
        'name'               => 'user.profile.quiz',
        'phrase_title'       => 'quiz::seo.user_profile_quiz_title',
        'phrase_description' => 'quiz::seo.user_profile_quiz_desription',
        'phrase_keywords'    => 'quiz::seo.user_profile_quiz_keywords',
        'phrase_heading'     => 'quiz::seo.user_profile_quiz_heading',
        'url'                => 'user/{id}/quiz',
        'item_type'          => 'user',
        'resource_name'      => 'user',
    ],
    [
        'name'               => 'quiz.search',
        'phrase_title'       => 'quiz::seo.quiz_search_title',
        'phrase_description' => 'quiz::seo.quiz_search_description',
        'phrase_keywords'    => 'quiz::seo.quiz_search_keywords',
        'phrase_heading'     => 'quiz::seo.quiz_search_heading',
        'url'                => 'quiz/search',
    ],
];
