<?php

/* this is auto generated file */
return [
    [
        'description' => 'Write something...',
        'post_type'   => 'activity_post',
        'icon_color'  => '#0f81d8',
        'showWhen'    => ['and', ['truthy', 'isHomeScreen']],
        'menu'        => 'event.event.feedComposerMenu',
        'name'        => 'compose_status',
        'label'       => 'activity::phrase.status',
        'ordering'    => 1,
        'as'          => 'post.status',
        'value'       => 'activity_post',
        'icon'        => 'quotes-right',
    ],
    [
        'description' => '',
        'icon_color'  => '#2681d5',
        'showWhen'    => [
            'and',
            ['neq', 'attachmentType', 'photo'],
            ['neq', 'attachmentType', 'photo_set'],
            ['truthy', 'isPreviewLinkHidden'],
            ['falsy', 'hasShareValue'],
            ['falsy', 'isHomeScreen'],
            ['falsy', 'hasPoll'],
            ['falsy', 'hasVideoUrl'],
            ['falsy', 'exceedTextLimit'],
            ['truthy', 'setting.backgroundstatus.total_active'],
        ],
        'menu'        => 'event.event.feedComposerMenu',
        'name'        => 'compose_status_background',
        'label'       => 'activity::phrase.status_background',
        'ordering'    => 2,
        'as'          => 'status_background',
        'value'       => 'status_background',
        'icon'        => 'color-palette',
    ],
    [
        'description' => '',
        'icon_color'  => '#4D7C9C',
        'showWhen'    => [
            'and',
            ['falsy', 'isHomeScreen'],
            ['truthy', 'setting.activity.feed.enable_tag_friends'],
            [
                'or',
                ['truthy', 'isEdit'],
                ['falsy', 'hasVideoUrl'],
            ],
        ],
        'menu'        => 'event.event.feedComposerMenu',
        'name'        => 'compose_tag_friends',
        'label'       => 'activity::phrase.tag_friends',
        'ordering'    => 3,
        'as'          => 'add_friends',
        'value'       => 'add_friends',
        'icon'        => 'user3-plus',
    ],
    [
        'post_type'  => 'activity_post',
        'icon_color' => '#f05d28',
        'showWhen'   => [
            'and',
            ['truthy', 'setting.activity.feed.enable_check_in'],
            [
                'or',
                ['truthy', 'isEdit'],
                ['falsy', 'hasVideoUrl'],
            ],
        ],
        'menu'       => 'event.event.feedComposerMenu',
        'name'       => 'compose_checkin',
        'label'      => 'activity::phrase.check_in',
        'ordering'   => 6,
        'as'         => 'post.checkin',
        'value'      => 'location',
        'icon'       => 'checkin',
        'to'         => '4',
    ],
    [
        'post_type'  => 'poll',
        'icon_color' => '#f05d28',
        'showWhen'   => [
            'and',
            [
                'and',
                ['truthy', 'acl.poll.poll.create'],
                ['truthy', 'setting.feed.types.poll.can_create_feed'],
            ],
            [
                'or',
                ['truthy', 'isHomeScreen'],
                [
                    'and',
                    ['eq', 'attachmentType', 'poll'],
                    ['falsy', 'isEdit'],
                    ['falsy', 'hasPoll'],
                ],
                [
                    'and',
                    ['falsy', 'hasShareValue'],
                    ['falsy', 'pstatusbg_enable'],
                    ['falsy', 'hasMediaFile'],
                    ['truthy', 'isPreviewLinkHidden'],
                    ['falsy', 'hasVideoUrl'],
                    ['falsy', 'hasPoll'],
                    ['falsy', 'isEdit'],
                    ['neq', 'module_name', 'event'],
                ],
            ],
        ],
        'menu'       => 'event.event.feedComposerMenu',
        'name'       => 'compose_poll',
        'label'      => 'activity::phrase.poll',
        'ordering'   => 7,
        'as'         => 'post.poll',
        'value'      => 'poll',
        'icon'       => 'barchart',
        'is_active'  => 0,
        'is_delete'  => 1,
    ],
    [
        'description' => 'Write something...',
        'post_type'   => 'activity_post',
        'icon_color'  => '#0f81d8',
        'menu'        => 'feed.feed.feedComposerMenu',
        'name'        => 'compose_status',
        'label'       => 'activity::phrase.status',
        'ordering'    => 1,
        'as'          => 'post.status',
        'value'       => 'activity_post',
        'icon'        => 'quotes-right',
        'showWhen'    => ['and', ['truthy', 'isHomeScreen']],
    ],
    [
        'description' => '',
        'icon_color'  => '#2681d5',
        'menu'        => 'feed.feed.feedComposerMenu',
        'name'        => 'compose_status_background',
        'label'       => 'activity::phrase.status_background',
        'ordering'    => 2,
        'as'          => 'status_background',
        'value'       => 'status_background',
        'icon'        => 'color-palette',
        'showWhen'    => [
            'and',
            ['neq', 'attachmentType', 'photo'],
            ['neq', 'attachmentType', 'photo_set'],
            ['truthy', 'isPreviewLinkHidden'],
            ['falsy', 'hasShareValue'],
            ['falsy', 'isHomeScreen'],
            ['falsy', 'hasPoll'],
            ['falsy', 'hasVideoUrl'],
            ['falsy', 'exceedTextLimit'],
            ['truthy', 'setting.backgroundstatus.total_active'],
        ],
    ],
    [
        'description' => '',
        'icon_color'  => '#4D7C9C',
        'showWhen'    => [
            'and',
            ['falsy', 'isHomeScreen'],
            ['truthy', 'setting.activity.feed.enable_tag_friends'],
            [
                'or',
                ['truthy', 'isEdit'],
                ['falsy', 'hasVideoUrl'],
            ],
        ],
        'menu'        => 'feed.feed.feedComposerMenu',
        'name'        => 'compose_tag_friends',
        'label'       => 'activity::phrase.tag_friends',
        'ordering'    => 3,
        'as'          => 'add_friends',
        'value'       => 'add_friends',
        'icon'        => 'user3-plus',
    ],
    [
        'post_type'  => 'activity_post',
        'icon_color' => '#f05d28',
        'showWhen'   => [
            'and',
            ['truthy', 'setting.activity.feed.enable_check_in'],
            [
                'or',
                ['truthy', 'isEdit'],
                ['falsy', 'hasVideoUrl'],
            ],
        ],
        'menu'       => 'feed.feed.feedComposerMenu',
        'name'       => 'compose_checkin',
        'label'      => 'activity::phrase.check_in',
        'ordering'   => 6,
        'as'         => 'post.checkin',
        'value'      => 'location',
        'icon'       => 'checkin',
        'to'         => '4',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_view_histories'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'view_edit_history',
        'label'    => 'activity::phrase.view_edit_history',
        'ordering' => 16,
        'value'    => 'feed_history/viewHistories',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'activity::phrase.edit_post',
        'ordering' => 1,
        'value'    => 'updateFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_pin_item'],
            ['falsy', 'item.extra.can_review_feed'],
            ['truthy', 'profile_id'],
            ['or', ['eqeqeq', 'params._identity', '$.item.user'], ['eqeqeq', 'params._identity', '$.item.parent_user']],
            ['eq', 'profile_type', 'user'],
            ['noneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'pinItem',
        'label'    => 'activity::phrase.pin_post',
        'ordering' => 2,
        'value'    => 'pinItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_pin_item'],
            ['truthy', 'profile_id'],
            ['or', ['eqeqeq', 'params._identity', '$.item.user'], ['eqeqeq', 'params._identity', '$.item.parent_user']],
            ['eq', 'profile_type', 'user'],
            ['oneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'unpinItem',
        'label'    => 'activity::phrase.unpin_post',
        'ordering' => 3, 'value' => 'unpinItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'profile_id'],
            ['truthy', 'item.extra.can_pin_home'],
            ['noneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'pinHome',
        'label'    => 'activity::phrase.pin_post_on_homepage',
        'ordering' => 2,
        'value'    => 'pinHome',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'profile_id'],
            ['truthy', 'item.extra.can_pin_home'],
            ['oneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'unpinHome',
        'label'    => 'activity::phrase.unpin_post_on_homepage',
        'ordering' => 3,
        'value'    => 'unpinHome',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity.feed.enable_hide_feed'],
            ['truthy', 'item.extra.can_hide_item'],
            ['eq', 'item.is_pending', 0],
            ['falsy', 'item.extra.can_review_feed'],
            ['noneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'hide',
        'label'    => 'activity::phrase.hide_this_post',
        'ordering' => 4,
        'value'    => 'hideItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity.feed.enable_hide_feed'],
            ['truthy', 'item.extra.can_hide_all_user'],
            ['falsy', 'item.extra.can_review_feed'],
            ['falsy', 'profile_id'],
            ['noneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'item.is_sponsor'],
            ['gte', 'apiVersion', 'v1.17'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'hide_all_user',
        'label'    => 'activity::phrase.hide_all_from_user_full_name',
        'ordering' => 5,
        'value'    => 'unfollowPoster',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_snooze_user'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'snooze_user',
        'label'    => 'activity::phrase.snooze_user_full_name_for_30_days',
        'ordering' => 6,
        'value'    => 'snoozePoster',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity.feed.enable_hide_feed'],
            ['truthy', 'item.extra.can_hide_all_owner'],
            ['falsy', 'profile_id'],
            ['noneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'item.is_sponsor'],
            ['gte', 'apiVersion', 'v1.17'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'hide_all_owner',
        'label'    => 'activity::phrase.hide_all_from_owner_full_name',
        'ordering' => 7,
        'value'    => 'unfollowOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_snooze_owner'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'snooze_owner',
        'label'    => 'activity::phrase.snooze_owner_full_name_for_30_days',
        'ordering' => 8,
        'value'    => 'snoozeOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity.feed.enable_hide_feed'],
            ['truthy', 'item.extra.can_hide_all_shared_user'],
            ['falsy', 'profile_id'],
            ['noneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'item.is_sponsor'],
            ['gte', 'apiVersion', 'v1.17'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'hide_all_shared_user',
        'label'    => 'activity::phrase.hide_all_from_shared_user_full_name',
        'ordering' => 9,
        'value'    => 'unfollowSharedPoster',
    ],
    [
        'showWhen' => ['truthy', 'item.extra.can_snooze_shared_user'],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'snooze_shared_user',
        'label'    => 'activity::phrase.snooze_shared_user_full_name_for_30_days',
        'ordering' => 10,
        'value'    => 'snoozeSharedPoster',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity.feed.enable_hide_feed'],
            ['truthy', 'item.extra.can_hide_all_shared_owner'],
            ['falsy', 'profile_id'],
            ['noneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'item.is_sponsor'],
            ['gte', 'apiVersion', 'v1.17'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'hide_all_shared_owner',
        'label'    => 'activity::phrase.hide_all_from_shared_owner_full_name',
        'ordering' => 11,
        'value'    => 'unfollowSharedOwner',
    ],
    [
        'showWhen' => ['truthy', 'item.extra.can_snooze_shared_owner'],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'snooze_shared_owner',
        'label'    => 'activity::phrase.snooze_shared_owner_full_name_for_30_days',
        'ordering' => 12,
        'value'    => 'snoozeSharedOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'activity::phrase.sponsor_in_feed',
        'ordering' => 15,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'activity::phrase.unsponsor_in_feed',
        'ordering' => 16,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_remove_tag_friend'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'remove_tag',
        'label'    => 'activity::phrase.remove_tag',
        'ordering' => 19,
        'value'    => 'removeTaggedFriend',
    ],
    [
        'showWhen' => [
            'and',
            ['false', 'item.is_pending'],
            ['truthy', 'item.extra.can_block'],
            ['truthy', 'profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'decline',
        'label'    => 'activity::phrase.remove_post_and_block_author',
        'ordering' => 19,
        'value'    => 'feed/declinePendingAndBlockAuthor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_remove'],
            ['eq', 'item.is_pending', 0],
            ['truthy', 'profile_id'],
        ],
        'style'    => 'danger',
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'remove',
        'label'    => 'activity::phrase.remove_post',
        'ordering' => 20,
        'value'    => 'feed/removeItem',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'feed.feed.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'activity::phrase.delete_post',
        'ordering'  => 21,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete_with_items'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'feed.feed.itemActionMenu',
        'name'      => 'delete_with_items',
        'label'     => 'activity::phrase.delete_post_with_items',
        'ordering'  => 22,
        'value'     => 'feed/deleteWithItems',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_block'],
            ['truthy', 'item.is_pending'],
        ],
        'menu'     => 'feed.feed.itemPendingActionMenu',
        'name'     => 'decline',
        'label'    => 'activity::phrase.decline_post_and_block_author',
        'ordering' => 1,
        'value'    => 'feed/declinePendingAndBlockAuthor',
    ],
    [
        'showWhen' => ['truthy', 'item.extra.can_delete'],
        'menu'     => 'feed.feed.itemPendingActionMenu',
        'name'     => 'delete',
        'label'    => 'activity::phrase.delete_post',
        'ordering' => 3,
        'value'    => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_now',
        'label'    => 'activity::phrase.share_now',
        'ordering' => 1,
        'value'    => 'shareNow',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_to_news_feed',
        'label'    => 'activity::phrase.share_to_news_feed',
        'ordering' => 2,
        'value'    => 'shareToNewsFeed',
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'item.extra.can_share'],
            ['gte', 'session.user.statistic.total_friend', 1],
        ],
        'menu'       => 'feed.itemShareActionsMenu',
        'name'       => 'share_on_friends',
        'label'      => 'activity::phrase.share_on_friends',
        'ordering'   => 3,
        'value'      => 'shareOnFriendProfile',
        'is_deleted' => true,
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'       => 'feed.itemShareActionsMenu',
        'name'       => 'share_on_page',
        'label'      => 'activity::phrase.share_on_page',
        'ordering'   => 4,
        'value'      => 'shareOnPageProfile',
        'is_deleted' => true,
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'       => 'feed.itemShareActionsMenu',
        'name'       => 'share_on_group',
        'label'      => 'activity::phrase.share_on_group',
        'ordering'   => 5,
        'value'      => 'shareOnGroupProfile',
        'is_deleted' => true,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'copy_link',
        'label'    => 'activity::phrase.copy_link',
        'ordering' => 6,
        'value'    => 'copyLink',
    ],
    [
        'description' => 'Write something...',
        'post_type'   => 'activity_post',
        'icon_color'  => '#0f81d8',
        'showWhen'    => ['and', ['truthy', 'isHomeScreen']],
        'menu'        => 'group.group.feedComposerMenu',
        'name'        => 'compose_status',
        'label'       => 'activity::phrase.status',
        'ordering'    => 1,
        'as'          => 'post.status',
        'value'       => 'activity_post',
        'icon'        => 'quotes-right',
    ],
    [
        'description' => '',
        'icon_color'  => '#2681d5',
        'showWhen'    => [
            'and',
            ['neq', 'attachmentType', 'photo'],
            ['neq', 'attachmentType', 'photo_set'],
            ['truthy', 'isPreviewLinkHidden'],
            ['falsy', 'hasShareValue'],
            ['falsy', 'isHomeScreen'],
            ['falsy', 'hasPoll'],
            ['falsy', 'hasVideoUrl'],
            ['falsy', 'exceedTextLimit'],
            ['truthy', 'setting.backgroundstatus.total_active'],
        ],
        'menu'        => 'group.group.feedComposerMenu',
        'name'        => 'compose_status_background',
        'label'       => 'activity::phrase.status_background',
        'ordering'    => 2,
        'as'          => 'status_background',
        'value'       => 'status_background',
        'icon'        => 'color-palette',
    ],
    [
        'description' => '',
        'icon_color'  => '#4D7C9C',
        'showWhen'    => [
            'and',
            ['falsy', 'isHomeScreen'],
            ['truthy', 'setting.activity.feed.enable_tag_friends'],
            [
                'or',
                ['truthy', 'isEdit'],
                ['falsy', 'hasVideoUrl'],
            ],
        ],
        'menu'        => 'group.group.feedComposerMenu',
        'name'        => 'compose_tag_friends',
        'label'       => 'activity::phrase.tag_friends',
        'ordering'    => 3,
        'as'          => 'add_friends',
        'value'       => 'add_friends',
        'icon'        => 'user3-plus',
    ],
    [
        'post_type'  => 'activity_post',
        'icon_color' => '#f05d28',
        'showWhen'   => [
            'and',
            ['truthy', 'setting.activity.feed.enable_check_in'],
            [
                'or',
                ['truthy', 'isEdit'],
                ['falsy', 'hasVideoUrl'],
            ],
        ],
        'menu'       => 'group.group.feedComposerMenu',
        'name'       => 'compose_checkin',
        'label'      => 'activity::phrase.check_in',
        'ordering'   => 6,
        'as'         => 'post.checkin',
        'value'      => 'location',
        'icon'       => 'checkin',
        'to'         => '4',
    ],
    [
        'post_type'  => 'poll',
        'icon_color' => '#f05d28',
        'showWhen'   => [
            'and',
            [
                'and',
                ['truthy', 'acl.poll.poll.create'],
                ['truthy', 'setting.feed.types.poll.can_create_feed'],
                ['truthy', 'item.profile_settings.poll_share_polls'],
            ],
            [
                'or',
                ['truthy', 'isHomeScreen'],
                [
                    'and',
                    ['eq', 'attachmentType', 'poll'],
                    ['falsy', 'isEdit'],
                    ['falsy', 'hasPoll'],
                ],
                [
                    'and',
                    ['falsy', 'hasShareValue'],
                    ['falsy', 'pstatusbg_enable'],
                    ['falsy', 'hasMediaFile'],
                    ['truthy', 'isPreviewLinkHidden'],
                    ['falsy', 'hasVideoUrl'],
                    ['falsy', 'hasPoll'],
                    ['falsy', 'isEdit'],
                    ['neq', 'module_name', 'event'],
                ],
            ],
        ],
        'menu'       => 'group.group.feedComposerMenu',
        'name'       => 'compose_poll',
        'label'      => 'activity::phrase.poll',
        'ordering'   => 7,
        'as'         => 'post.poll',
        'value'      => 'poll',
        'icon'       => 'barchart',
    ],
    [
        'description' => 'Write something...',
        'post_type'   => 'activity_post',
        'icon_color'  => '#0f81d8',
        'showWhen'    => ['and', ['truthy', 'isHomeScreen']],
        'menu'        => 'page.page.feedComposerMenu',
        'name'        => 'compose_status',
        'label'       => 'activity::phrase.status',
        'ordering'    => 1,
        'as'          => 'post.status',
        'value'       => 'activity_post',
        'icon'        => 'quotes-right',
    ],
    [
        'description' => '',
        'icon_color'  => '#2681d5',
        'showWhen'    => [
            'and',
            ['neq', 'attachmentType', 'photo'],
            ['neq', 'attachmentType', 'photo_set'],
            ['truthy', 'isPreviewLinkHidden'],
            ['falsy', 'hasShareValue'],
            ['falsy', 'isHomeScreen'],
            ['falsy', 'hasPoll'],
            ['falsy', 'hasVideoUrl'],
            ['falsy', 'exceedTextLimit'],
            ['truthy', 'setting.backgroundstatus.total_active'],
        ],
        'menu'        => 'page.page.feedComposerMenu',
        'name'        => 'compose_status_background',
        'label'       => 'activity::phrase.status_background',
        'ordering'    => 2,
        'as'          => 'status_background',
        'value'       => 'status_background',
        'icon'        => 'color-palette',
    ],
    [
        'description' => '',
        'icon_color'  => '#4D7C9C',
        'showWhen'    => [
            'and',
            ['falsy', 'isHomeScreen'],
            ['truthy', 'setting.activity.feed.enable_tag_friends'],
            [
                'or',
                ['truthy', 'isEdit'],
                ['falsy', 'hasVideoUrl'],
            ],
        ],
        'menu'        => 'page.page.feedComposerMenu',
        'name'        => 'compose_tag_friends',
        'label'       => 'activity::phrase.tag_friends',
        'ordering'    => 3,
        'as'          => 'add_friends',
        'value'       => 'add_friends',
        'icon'        => 'user3-plus',
    ],
    [
        'post_type'  => 'activity_post',
        'icon_color' => '#f05d28',
        'showWhen'   => [
            'and',
            ['truthy', 'setting.activity.feed.enable_check_in'],
            [
                'or',
                ['truthy', 'isEdit'],
                ['falsy', 'hasVideoUrl'],
            ],
        ],
        'menu'       => 'page.page.feedComposerMenu',
        'name'       => 'compose_checkin',
        'label'      => 'activity::phrase.check_in',
        'ordering'   => 6,
        'as'         => 'post.checkin',
        'value'      => 'location',
        'icon'       => 'checkin',
        'to'         => '4',
    ],
    [
        'post_type'  => 'poll',
        'icon_color' => '#f05d28',
        'showWhen'   => [
            'and',
            [
                'and',
                ['truthy', 'acl.poll.poll.create'],
                ['truthy', 'setting.feed.types.poll.can_create_feed'],
                ['truthy', 'item.profile_settings.poll_share_polls'],
            ],
            [
                'or',
                ['truthy', 'isHomeScreen'],
                [
                    'and',
                    ['eq', 'attachmentType', 'poll'],
                    ['falsy', 'isEdit'],
                    ['falsy', 'hasPoll'],
                ],
                [
                    'and',
                    ['falsy', 'hasShareValue'],
                    ['falsy', 'pstatusbg_enable'],
                    ['falsy', 'hasMediaFile'],
                    ['truthy', 'isPreviewLinkHidden'],
                    ['falsy', 'hasVideoUrl'],
                    ['falsy', 'hasPoll'],
                    ['falsy', 'isEdit'],
                    ['neq', 'module_name', 'event'],
                ],
            ],
        ],
        'menu'       => 'page.page.feedComposerMenu',
        'name'       => 'compose_poll',
        'label'      => 'activity::phrase.poll',
        'ordering'   => 7,
        'as'         => 'post.poll',
        'value'      => 'poll',
        'icon'       => 'barchart',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'share',
        'label'    => 'page::phrase.share',
        'ordering' => 13,
        'value'    => 'shareToNewsFeed',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.activity.feed.view'],
        ],
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'feed',
        'label'         => 'activity::phrase.feed_global_search_label',
        'ordering'      => 2,
        'value'         => 'searchGlobalPost',
        'module_name'   => 'feed',
        'resource_name' => 'feed',
    ],
    [
        'description' => 'Write something...',
        'post_type'   => 'activity_post',
        'icon_color'  => '#0f81d8',
        'showWhen'    => ['and', ['truthy', 'isHomeScreen']],
        'menu'        => 'user.user.feedComposerMenu',
        'name'        => 'compose_status',
        'label'       => 'activity::phrase.status',
        'ordering'    => 1,
        'as'          => 'post.status',
        'value'       => 'activity_post',
        'icon'        => 'quotes-right',
    ],
    [
        'description' => '',
        'icon_color'  => '#2681d5',
        'showWhen'    => [
            'and',
            ['neq', 'attachmentType', 'photo'],
            ['neq', 'attachmentType', 'photo_set'],
            ['truthy', 'isPreviewLinkHidden'],
            ['falsy', 'hasShareValue'],
            ['falsy', 'isHomeScreen'],
            ['falsy', 'hasPoll'],
            ['falsy', 'hasVideoUrl'],
            ['falsy', 'exceedTextLimit'],
            ['truthy', 'setting.backgroundstatus.total_active'],
        ],
        'menu'        => 'user.user.feedComposerMenu',
        'name'        => 'compose_status_background',
        'label'       => 'activity::phrase.status_background',
        'ordering'    => 2,
        'as'          => 'status_background',
        'value'       => 'status_background',
        'icon'        => 'color-palette',
    ],
    [
        'description' => '',
        'icon_color'  => '#4D7C9C',
        'showWhen'    => [
            'and',
            ['falsy', 'isHomeScreen'],
            ['truthy', 'setting.activity.feed.enable_tag_friends'],
            [
                'or',
                ['truthy', 'isEdit'],
                ['falsy', 'hasVideoUrl'],
            ],
        ],
        'menu'        => 'user.user.feedComposerMenu',
        'name'        => 'compose_tag_friends',
        'label'       => 'activity::phrase.tag_friends',
        'ordering'    => 3,
        'as'          => 'add_friends',
        'value'       => 'add_friends',
        'icon'        => 'user3-plus',
    ],
    [
        'post_type'  => 'activity_post',
        'icon_color' => '#f05d28',
        'showWhen'   => [
            'and',
            ['truthy', 'setting.activity.feed.enable_check_in'],
            [
                'or',
                ['truthy', 'isEdit'],
                ['falsy', 'hasVideoUrl'],
            ],
        ],
        'menu'       => 'user.user.feedComposerMenu',
        'name'       => 'compose_checkin',
        'label'      => 'activity::phrase.check_in',
        'ordering'   => 6,
        'as'         => 'post.checkin',
        'value'      => 'location',
        'icon'       => 'checkin',
        'to'         => '4',
    ],
    [
        'post_type'  => 'poll',
        'icon_color' => '#f05d28',
        'showWhen'   => [
            'and',
            [
                'and',
                ['truthy', 'acl.poll.poll.create'],
                ['truthy', 'setting.feed.types.poll.can_create_feed'],
                ['falsy', 'isUserProfileOther'],
            ],
            [
                'or',
                ['truthy', 'isHomeScreen'],
                [
                    'and',
                    ['eq', 'attachmentType', 'poll'],
                    ['falsy', 'isEdit'],
                    ['falsy', 'hasPoll'],
                ],
                [
                    'and',
                    ['falsy', 'hasShareValue'],
                    ['falsy', 'pstatusbg_enable'],
                    ['falsy', 'hasMediaFile'],
                    ['truthy', 'isPreviewLinkHidden'],
                    ['falsy', 'hasVideoUrl'],
                    ['falsy', 'hasPoll'],
                    ['falsy', 'isEdit'],
                    ['neq', 'module_name', 'event'],
                    ['truthy', 'item.is_owner'],
                ],
            ],
        ],
        'menu'       => 'user.user.feedComposerMenu',
        'name'       => 'compose_poll',
        'label'      => 'activity::phrase.poll',
        'ordering'   => 7,
        'as'         => 'post.poll',
        'value'      => 'poll',
        'icon'       => 'barchart',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.activity.feed.view'],
        ],
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'feed',
        'label'         => 'activity::phrase.feed_global_search_label',
        'ordering'      => 2,
        'value'         => 'searchGlobalPost',
        'module_name'   => 'feed',
        'resource_name' => 'feed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_remove_tag_friend'],
        ],
        'menu'     => 'feed.feed.itemActionMenuForProfile',
        'name'     => 'remove_tag',
        'label'    => 'activity::phrase.remove_tag',
        'ordering' => 3,
        'value'    => 'removeTaggedFriend',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.activity.feed.view'],
        ],
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'feed',
        'label'         => 'activity::phrase.feed_global_search_label',
        'ordering'      => 2,
        'value'         => 'searchGlobalPost',
        'module_name'   => 'feed',
        'resource_name' => 'feed',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.activity.feed.view'],
        ],
        'menu'          => 'search.mobileHashtagCategoryMenu',
        'name'          => 'feed',
        'label'         => 'activity::phrase.feed_global_search_label',
        'ordering'      => 1,
        'module_name'   => 'feed',
        'resource_name' => 'feed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'     => 'page.page.profileShareActionMenu',
        'name'     => 'share_to_news_feed',
        'label'    => 'activity::phrase.share_to_news_feed',
        'ordering' => 1,
        'value'    => 'shareToNewsFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'     => 'page.page.profileShareActionMenu',
        'name'     => 'copy_link',
        'label'    => 'activity::phrase.copy_link',
        'ordering' => 2,
        'value'    => 'copyLink',
    ],
    [
        'tab'            => 'home',
        'showWhen'       => [
            'and',
            ['truthy', 'setting.activity'],
        ],
        'menu'           => 'user.user.profileMenu',
        'name'           => 'home',
        'label'          => 'user::phrase.overview',
        'ordering'       => 1,
        'to'             => '/',
        'params'         => [
            'module_name'   => 'feed',
            'resource_name' => 'feed',
        ],
        'value'          => 'overview',
        'useScrollToTop' => true,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
            ['falsy', 'item.is_pending'],
        ],
        'params'   => [
            'module_name'   => 'group',
            'resource_name' => 'group',
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'your_content',
        'label'    => 'group::phrase.your_content',
        'ordering' => 9,
        'as'       => '',
        'value'    => 'yourContent',
        'to'       => '/group/:id/review_my_content',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_pending_posts'],
        ],
        'menu'     => 'group.manageMenu',
        'name'     => 'pending_posts',
        'label'    => 'group::phrase.pending_posts',
        'ordering' => 6,
        'icon'     => 'clock-o',
        'value'    => 'group/pendingPostGroup',
    ],
    //    [
    //        'description' => '',
    //        'icon_color'  => '#FFBA27',
    //        'showWhen'    => [
    //            'and',
    //            ['falsy', 'hasShareValue'],
    //            ['falsy', 'isHomeScreen'],
    //            ['truthy', 'acl.activity.feed.schedule_post'],
    //        ],
    //        'menu'     => 'feed.feed.feedComposerMenu',
    //        'name'     => 'schedule_post',
    //        'label'    => 'activity::phrase.schedule',
    //        'ordering' => 7,
    //        'as'       => 'post.schedule',
    //        'value'    => 'schedule_post',
    //        'icon'     => 'clock',
    //    ],
    //    [
    //        'description' => '',
    //        'icon_color'  => '#FFBA27',
    //        'showWhen'    => [
    //            'and',
    //            ['falsy', 'hasShareValue'],
    //            ['falsy', 'isHomeScreen'],
    //            ['truthy', 'acl.activity.feed.schedule_post'],
    //        ],
    //        'menu'     => 'user.user.feedComposerMenu',
    //        'name'     => 'schedule_post',
    //        'label'    => 'activity::phrase.schedule',
    //        'ordering' => 8,
    //        'as'       => 'post.schedule',
    //        'value'    => 'schedule_post',
    //        'icon'     => 'clock',
    //    ],
    [
        'menu'     => 'feed.activity_schedule.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'activity::phrase.edit_post',
        'ordering' => 1,
        'value'    => 'updateScheduled',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.activity.feed.create'],
            ['truthy', 'item.extra.can_send_now'],
        ],
        'menu'     => 'feed.activity_schedule.itemActionMenu',
        'name'     => 'send_now',
        'label'    => 'activity::phrase.send_now',
        'ordering' => 2,
        'value'    => 'sendNowScheduled',
    ],
    [
        'menu'     => 'feed.activity_schedule.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'activity::phrase.delete_post',
        'ordering' => 3,
        'value'    => 'deleteItem',
    ],
    [
        'enabledWhen' => [
            'and',
            ['truthy', 'acl.activity.feed.create'],
            ['truthy', 'item.extra.can_send_now'],
        ],
        'menu'        => 'feed.activity_schedule.scheduledItemMenu',
        'name'        => 'send_now',
        'label'       => 'activity::phrase.send_now',
        'ordering'    => 1,
        'value'       => 'sendNowScheduled',
        'buttonProps' => [
            'color'   => 'primary',
            'variant' => 'contained',
        ],
    ],
    [

        'menu'        => 'feed.activity_schedule.scheduledItemMenu',
        'name'        => 'delete',
        'label'       => 'core::phrase.delete',
        'ordering'    => 2,
        'value'       => 'deleteItem',
        'buttonProps' => [
            'color'   => 'error',
            'variant' => 'outlined',
        ],
    ],
    [
        'menu'      => 'user.settingMenu',
        'name'      => 'review',
        'label'     => 'user::phrase.review_posts',
        'ordering'  => 9,
        'to'        => '/settings/reviewPosts',
        'icon'      => 'user-circle-o',
        'iconColor' => '#17A2B8',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'acl.activity.feed.schedule_post'],
        ],
        'menu'      => 'user.settingMenu',
        'name'      => 'scheduled_posts',
        'label'     => 'activity::phrase.scheduled_posts',
        'ordering'  => 10,
        'to'        => '/settings/scheduledPosts',
        'icon'      => 'clock-o',
        'iconColor' => '#17A2B8',
    ],
    [
        'showWhen' => [
            'and',
            ['gte', 'apiVersion', 'v1.17'],
        ],
        'menu'      => 'user.settingMenu',
        'name'      => 'manage_hidden',
        'label'     => 'core::phrase.manage_hidden',
        'ordering'  => 17,
        'to'        => '/settings/manageHidden',
        'icon'      => 'eye-alt-blocked',
        'iconColor' => '#17A2B8',
    ],
    [
        'menu'        => 'feed.feed.sort_menu',
        'name'        => 'recent',
        'label'       => 'activity::phrase.newest_posts',
        'ordering'    => 1,
        'value'       => 'recent',
        'description' => 'sort_newest_posts_description',
    ],
    [
        'menu'        => 'feed.feed.sort_menu',
        'name'        => 'newest_activity',
        'label'       => 'activity::phrase.newest_activity',
        'ordering'    => 2,
        'value'       => 'newest_activity',
        'description' => 'sort_newest_activity_description',
    ],
];
