<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'activity::phrase.edit_post',
        'ordering' => 1,
        'value'    => 'updateFeed',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_pin_item'],
            ['falsy', 'item.extra.can_review_feed'],
            ['truthy', 'profile_id'],
            ['eq', 'profile_type', 'user'],
            ['noneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'pinItem',
        'label'    => 'activity::phrase.pin_post',
        'ordering' => 2,
        'value'    => 'pinItem',
        'icon'     => 'ico-thumb-tack',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'profile_id'],
            ['truthy', 'item.extra.can_pin_home'],
            ['noneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'subject.id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'pinHome',
        'label'    => 'activity::phrase.pin_post_on_homepage',
        'ordering' => 2,
        'value'    => 'pinHome',
        'icon'     => 'ico-thumb-tack',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_pin_item'],
            ['truthy', 'profile_id'],
            ['eq', 'profile_type', 'user'],
            ['oneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'unpinItem',
        'label'    => 'activity::phrase.unpin_post',
        'ordering' => 3,
        'value'    => 'unpinItem',
        'icon'     => 'ico-thumb-tack-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'profile_id'],
            ['truthy', 'item.extra.can_pin_home'],
            ['oneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'subject.id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'unpinHome',
        'label'    => 'activity::phrase.unpin_post_on_homepage',
        'ordering' => 3,
        'value'    => 'unpinHome',
        'icon'     => 'ico-thumb-tack-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity.feed.enable_hide_feed'],
            ['truthy', 'item.extra.can_hide_item'],
            ['eq', 'item.is_pending', 0],
            ['falsy', 'item.extra.can_review_feed'],
            ['noneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'hide',
        'label'    => 'activity::phrase.hide_this_post',
        'ordering' => 4,
        'value'    => 'hideItem',
        'icon'     => 'ico-eye-off-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity.feed.enable_hide_feed'],
            ['truthy', 'item.extra.can_hide_all_user'],
            ['falsy', 'item.extra.can_review_feed'],
            ['falsy', 'profile_id'],
            ['noneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'hide_all_user',
        'label'    => 'activity::phrase.hide_all_from_user_full_name',
        'ordering' => 5,
        'value'    => 'unfollowPoster',
        'icon'     => 'ico-eye-off-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_snooze_user'],
            ['falsy', 'item.extra.can_review_feed'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'snooze_user',
        'label'    => 'activity::phrase.snooze_user_full_name_for_30_days',
        'ordering' => 6,
        'value'    => 'snoozePoster',
        'icon'     => 'ico-clock-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity.feed.enable_hide_feed'],
            ['truthy', 'item.extra.can_hide_all_owner'],
            ['falsy', 'profile_id'],
            ['noneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'hide_all_owner',
        'label'    => 'activity::phrase.hide_all_from_owner_full_name',
        'ordering' => 7,
        'value'    => 'unfollowOwner',
        'icon'     => 'ico-eye-off-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_snooze_owner'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'snooze_owner',
        'label'    => 'activity::phrase.snooze_owner_full_name_for_30_days',
        'ordering' => 8,
        'value'    => 'snoozeOwner',
        'icon'     => 'ico-clock-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity.feed.enable_hide_feed'],
            ['truthy', 'item.extra.can_hide_all_shared_user'],
            ['falsy', 'profile_id'],
            ['noneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'hide_all_shared_user',
        'label'    => 'activity::phrase.hide_all_from_shared_user_full_name',
        'ordering' => 9,
        'value'    => 'unfollowSharedPoster',
        'icon'     => 'ico-eye-off-o',
    ],
    [
        'showWhen' => ['truthy', 'item.extra.can_snooze_shared_user'],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'snooze_shared_user',
        'label'    => 'activity::phrase.snooze_shared_user_full_name_for_30_days',
        'ordering' => 10,
        'value'    => 'snoozeSharedPoster',
        'icon'     => 'ico-clock-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity.feed.enable_hide_feed'],
            ['truthy', 'item.extra.can_hide_all_shared_owner'],
            ['falsy', 'profile_id'],
            ['noneOf', 'item.pins', '$.profile_id'],
            ['falsy', 'item.is_sponsor'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'hide_all_shared_owner',
        'label'    => 'activity::phrase.hide_all_from_shared_owner_full_name',
        'ordering' => 11,
        'value'    => 'unfollowSharedOwner',
        'icon'     => 'ico-eye-off-o',
    ],
    [
        'showWhen' => ['truthy', 'item.extra.can_snooze_shared_owner'],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'snooze_shared_owner',
        'label'    => 'activity::phrase.snooze_shared_owner_full_name_for_30_days',
        'ordering' => 12,
        'value'    => 'snoozeSharedOwner',
        'icon'     => 'ico-clock-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['falsy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'activity::phrase.sponsor_in_feed',
        'ordering' => 15,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
            ['truthy', 'item.is_sponsored_feed'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'activity::phrase.unsponsor_in_feed',
        'ordering' => 16,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_view_histories'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'view_edit_history',
        'label'    => 'activity::phrase.view_edit_history',
        'ordering' => 16,
        'value'    => 'feed_history/viewHistories',
        'icon'     => 'ico-eye-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_remove_tag_friend'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'remove_tag',
        'label'    => 'activity::phrase.remove_tag',
        'ordering' => 19,
        'value'    => 'removeTaggedFriend',
        'icon'     => 'ico-price-tag-o',
    ],
    [
        'showWhen' => [
            'and',
            ['false', 'item.is_pending'],
            ['truthy', 'item.extra.can_block'],
            ['truthy', 'profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'decline',
        'label'    => 'activity::phrase.remove_post_and_block_author',
        'ordering' => 19,
        'value'    => 'feed/declinePendingAndBlockAuthor',
        'icon'     => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_remove'],
            ['truthy', 'profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'remove',
        'label'    => 'activity::phrase.remove_post',
        'ordering' => 20,
        'value'    => 'feed/removeItem',
        'icon'     => 'ico-trash-o',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'feed.feed.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'activity::phrase.delete_post',
        'ordering'  => 21,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash-o',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete_with_items'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'feed.feed.itemActionMenu',
        'name'      => 'delete_with_items',
        'label'     => 'activity::phrase.delete_post_with_items',
        'ordering'  => 22,
        'value'     => 'feed/deleteWithItems',
        'icon'      => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_block'],
        ],
        'menu'     => 'feed.feed.itemPendingActionMenu',
        'name'     => 'decline',
        'label'    => 'activity::phrase.decline_post_and_block_author',
        'ordering' => 1,
        'value'    => 'feed/declinePendingAndBlockAuthor',
        'icon'     => 'ico-close',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.activity.feed.view'],
        ],
        'menu'     => 'group.searchWebCategoryMenu',
        'name'     => 'feed',
        'label'    => 'activity::phrase.feed_global_search_label',
        'ordering' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'share',
        'label'    => 'page::phrase.share',
        'ordering' => 12,
        'value'    => 'feed/shareToNewsFeed',
        'icon'     => 'ico-share-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.activity.feed.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'feed',
        'label'    => 'activity::phrase.feed_global_search_label',
        'ordering' => 2,
        'to'       => '/search/feed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.activity.feed.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'feed',
        'label'    => 'activity::phrase.feed_global_search_label',
        'ordering' => 100,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.activity.feed.view'],
        ],
        'menu'     => 'search.webHashtagCategoryMenu',
        'name'     => 'feed',
        'label'    => 'activity::phrase.feed_global_search_label',
        'ordering' => 1,
    ],
    [
        'tab'      => 'review',
        'menu'     => 'user.settingMenu',
        'name'     => 'review',
        'label'    => 'user::phrase.review_posts',
        'ordering' => 7,
        'to'       => '/settings/review',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_now',
        'label'    => 'activity::phrase.share_now',
        'ordering' => 1,
        'value'    => 'feed/shareNow',
        'icon'     => 'ico-share-alt-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_to_news_feed',
        'label'    => 'activity::phrase.share_to_news_feed',
        'ordering' => 2,
        'value'    => 'feed/shareToNewsFeed',
        'icon'     => 'ico-compose',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'copy_link',
        'label'    => 'activity::phrase.copy_link',
        'ordering' => 6,
        'value'    => 'copyLink',
        'icon'     => 'ico-link',
    ],
    [
        'tab'      => 'home',
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'home',
        'label'    => 'user::phrase.overview',
        'ordering' => 1,
        'to'       => '/',
    ],
    [
        'tab'      => 'home',
        'showWhen' => [
            'and',
            ['truthy', 'setting.activity'],
        ],
        'menu'     => 'page.page.profileMenu',
        'name'     => 'home',
        'label'    => 'page::phrase.overview',
        'ordering' => 1,
        'to'       => '/',
    ],
    [
        'tab'      => 'home',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_view_tab_discussion'],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'home',
        'label'    => 'group::phrase.discussions',
        'ordering' => 1,
        'to'       => '/',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_remove_tag_friend'],
        ],
        'menu'     => 'feed.feed.itemActionMenuForProfile',
        'name'     => 'remove_tag',
        'label'    => 'activity::phrase.remove_tag',
        'ordering' => 3,
        'value'    => 'removeTaggedFriendForProfile',
        'icon'     => 'ico-price-tag-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.group.profileActionMenu',
        'name'     => 'your_content',
        'label'    => 'group::phrase.your_content',
        'ordering' => 7,
        'as'       => '',
        'value'    => 'group/yourContent',
        'icon'     => 'ico-user-man-o',
        'to'       => '/group/:id/review_my_content',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
            ['truthy', 'item.extra.can_view_my_content'],
        ],
        'menu'     => 'group.creatorContentMenu',
        'name'     => 'pending',
        'label'    => 'group::phrase.pending',
        'ordering' => 1,
        'as'       => '',
        'icon'     => 'ico-clock-o',
        'to'       => '/group/:id/review_my_content/pending',
    ],
    [
        'tab'      => 'published',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.creatorContentMenu',
        'name'     => 'published',
        'label'    => 'group::phrase.published',
        'ordering' => 1,
        'as'       => '',
        'icon'     => 'ico-newspaper-o',
        'to'       => '/group/:id/review_my_content/published',
    ],
    [
        'tab'      => 'declined',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
            ['truthy', 'item.extra.can_view_my_content'],
        ],
        'menu'     => 'group.creatorContentMenu',
        'name'     => 'declined',
        'label'    => 'group::phrase.declined',
        'ordering' => 1,
        'as'       => '',
        'icon'     => 'ico-flag-triangle-o',
        'to'       => '/group/:id/review_my_content/declined',
    ],
    [
        'tab'      => 'removed',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.creatorContentMenu',
        'name'     => 'removed',
        'label'    => 'group::phrase.removed',
        'ordering' => 1,
        'as'       => '',
        'icon'     => 'ico-trash-o',
        'to'       => '/group/:id/review_my_content/removed',
    ],
    [
        'tab'      => 'pending_posts',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_manage_pending_posts'],
        ],
        'menu'     => 'group.groupManagerMenu',
        'name'     => 'pending_posts',
        'label'    => 'group::phrase.pending_posts',
        'ordering' => 2,
        'icon'     => 'ico-clock-o',
        'to'       => '/group/manage/:id/pending_posts',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.activity.feed.schedule_post'],
        ],
        'menu'     => 'core.accountMenu',
        'name'     => 'scheduled_posts',
        'label'    => 'activity::phrase.scheduled_posts',
        'ordering' => 4,
        'icon'     => 'ico-clock',
        'to'       => '/settings/scheduled-posts',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.activity.feed.schedule_post'],
        ],
        'tab'      => 'scheduled_posts',
        'menu'     => 'user.settingMenu',
        'name'     => 'scheduled_posts',
        'label'    => 'activity::phrase.scheduled_posts',
        'ordering' => 8,
        'to'       => '/settings/scheduled-posts',
    ],
    [
        'tab'      => 'manage_hidden',
        'menu'     => 'user.settingMenu',
        'name'     => 'manage_hidden',
        'label'    => 'core::phrase.manage_hidden',
        'ordering' => 19,
        'to'       => '/settings/manage-hidden',
    ],
    [
        'menu'     => 'feed.activity_schedule.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'activity::phrase.edit_post',
        'ordering' => 1,
        'value'    => 'updateScheduled',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.activity.feed.create'],
            ['truthy', 'item.extra.can_send_now'],
        ],
        'menu'     => 'feed.activity_schedule.itemActionMenu',
        'name'     => 'send_now',
        'label'    => 'activity::phrase.send_now',
        'ordering' => 2,
        'value'    => 'sendNowScheduled',
        'icon'     => 'ico-paperplane-alt-o',
    ],
    [
        'menu'     => 'feed.activity_schedule.itemActionMenu',
        'name'     => 'delete',
        'label'    => 'activity::phrase.delete_post',
        'ordering' => 3,
        'value'    => 'deleteItem',
        'icon'     => 'ico-trash-o',
    ],
    [
        'enabledWhen' => [
            'and',
            ['truthy', 'acl.activity.feed.create'],
            ['truthy', 'item.extra.can_send_now'],
        ],
        'menu'        => 'feed.activity_schedule.scheduledItemMenu',
        'name'        => 'send_now',
        'label'       => 'activity::phrase.send_now',
        'ordering'    => 1,
        'value'       => 'sendNowScheduled',
        'icon'        => 'ico-paperplane-alt-o',
        'buttonProps' => [
            'color'   => 'primary',
            'variant' => 'contained',
        ],
    ],
    [
        'menu'        => 'feed.activity_schedule.scheduledItemMenu',
        'name'        => 'delete',
        'label'       => 'core::phrase.delete',
        'ordering'    => 2,
        'value'       => 'deleteItem',
        'icon'        => 'ico-trash-o',
        'buttonProps' => [
            'color'   => 'error',
            'variant' => 'outlined',
        ],
    ],
];
