<?php

/* this is auto generated file */
return [
    [
        'type'        => 'form-settings',
        'name'        => 'getting_started',
        'title'       => 'core::phrase.settings',
        'description' => 'getting-started::phrase.edit_getting_started_setting_desc',
        'driver'      => 'MetaFox\\GettingStarted\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'url'         => '/getting-started/setting',
        'resolution'  => 'admin',
        'version'     => 'v1',
    ],
    [
        'type'    => 'package-setting',
        'name'    => 'getting-started',
        'driver'  => 'MetaFox\\GettingStarted\\Http\\Resources\\v1\\PackageSetting',
        'version' => 'v1',
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Http\\Resources\\v1\\TodoList\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'getting_started.todo_list',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Http\\Resources\\v1\\TodoList\\Admin\\UpdateTodoListForm',
        'type'       => 'form',
        'name'       => 'getting_started.todo_list.update',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Http\\Resources\\v1\\TodoListImage\\TodoListImageItem',
        'type'       => 'json-resource',
        'name'       => 'todo_list_image.item',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Http\\Resources\\v1\\TodoList\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'todo_list',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Http\\Resources\\v1\\TodoList\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'todo_list',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Http\\Resources\\v1\\TodoList\\TodoListItemCollection',
        'type'       => 'json-collection',
        'name'       => 'todo_list.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Http\\Resources\\v1\\TodoList\\Admin\\SearchTodoListForm',
        'type'       => 'form',
        'name'       => 'gettingstarted_todolist.search.admin',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Policies\\TodoListPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\GettingStarted\\Models\\TodoList',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Policies\\TodoListViewPolicy',
        'type'       => 'policy-resource',
        'name'       => 'MetaFox\\GettingStarted\\Models\\TodoListView',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Models\\TodoList',
        'type'       => 'entity',
        'name'       => 'todo_list',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Todo List',
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Models\\TodoListText',
        'type'       => 'entity',
        'name'       => 'todo_list_text',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Todo List Text',
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Models\\TodoListImage',
        'type'       => 'entity',
        'name'       => 'todo_list_image',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Todo List Image',
    ],
    [
        'driver'     => 'MetaFox\\GettingStarted\\Models\\TodoList',
        'type'       => 'entity-content',
        'name'       => 'todo_list',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Todo List',
    ],
];
