<?php

/* this is auto generated file */
return [
    [
        'menu'     => 'page.page.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'page.page.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'page.page.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'page.page.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'invite',
        'label'    => 'page::phrase.invite_friends',
        'ordering' => 2,
        'value'    => 'page/inviteFriends',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'core::phrase.approve',
        'ordering' => 3,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'page::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'page::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'page::phrase.un_sponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'or',
            ['truthy', 'item.extra.can_edit'],
        ],
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'manage',
        'label'    => 'page::phrase.manage',
        'ordering' => 6,
        'value'    => 'pages/manage',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'page.page.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'page::phrase.delete',
        'ordering'  => 10,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit_cover'],
            ['truthy', 'item.cover_photo_id'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'remove_cover',
        'label'    => 'page::phrase.remove_cover_photo',
        'ordering' => 3,
        'value'    => 'page/remove_cover',
        'icon'     => '',
    ],
    [
        'showWhen' => ['truthy', 'item.extra.can_message'],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'message',
        'label'    => 'page::phrase.message',
        'ordering' => 5,
        'value'    => 'comingSoon',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_claim'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'claim',
        'label'    => 'page::phrase.claim_page',
        'ordering' => 6,
        'value'    => 'page_claim/addItem',
    ],
    [
        'showWhen' => ['truthy', 'item.extra.can_edit'],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'manage',
        'label'    => 'page::phrase.manage',
        'ordering' => 7,
        'value'    => 'pages/manage',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'invite',
        'label'    => 'page::phrase.invite_friends',
        'ordering' => 8,
        'value'    => 'page/inviteFriends',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 9,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'sponsor',
        'label'    => 'page::phrase.sponsor_this_item',
        'ordering' => 10,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'page::phrase.sponsor_this_item',
        'ordering' => 10,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'page::phrase.un_sponsor_this_item',
        'ordering' => 10,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            [
                'or',
                ['truthy', 'item.is_owner'],
                ['truthy', 'item.extra.can_moderate'],
            ],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'reassign_owner',
        'label'    => 'page::phrase.reassign_owner',
        'ordering' => 12,
        'value'    => 'page/reassignOwnerDialog',
    ],
    [
        'showWhen'  => [
            'or',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'page.page.profileActionMenu',
        'name'      => 'delete',
        'label'     => 'page::phrase.delete',
        'ordering'  => 15,
        'value'     => 'deleteItem',
    ],
    [
        'tab'            => 'home',
        'showWhen'       => [
            'and',
            ['truthy', 'setting.activity'],
        ],
        'menu'           => 'page.page.profileMenu',
        'name'           => 'home',
        'label'          => 'page::phrase.overview',
        'ordering'       => 1,
        'to'             => '/',
        'params'         => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'value'          => 'overview',
        'useScrollToTop' => true,
    ],
    [
        'tab'      => 'about',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'about',
        'label'    => 'page::phrase.about',
        'ordering' => 2,
        'to'       => '/about',
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'value'    => 'pageInfo',
    ],
    [
        'menu'     => 'page.page.profilePopoverMenu',
        'name'     => 'message',
        'label'    => 'page::phrase.message',
        'ordering' => 1,
        'value'    => 'comingSoon',
    ],
    [
        'showWhen' => [],
        'menu'     => 'page.page.profilePopoverMenu',
        'name'     => 'invite',
        'label'    => 'page::phrase.invite_friends',
        'ordering' => 2,
        'value'    => 'page/inviteFriends',
    ],
    [
        'menu'     => 'page.page.sort_menu',
        'name'     => 'recent',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'page.page.sort_menu',
        'name'     => 'most_member',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 2,
        'value'    => 'most_member',
    ],
    [
        'showWhen' => [
            'and',
            [
                'includes',
                'item.friendship',
                [0, 7],
            ],
            ['truthy', 'item.extra.can_add_friend'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'add_as_friend',
        'label'    => 'page::phrase.add_as_friend',
        'ordering' => 1,
        'value'    => 'user/addFriend',
        'icon'     => '',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 3],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'page::phrase.cancel_request',
        'ordering' => 2,
        'value'    => 'user/cancelRequest',
        'icon'     => '',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 1],
        'style'    => 'danger',
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'unfriend',
        'label'    => 'page::phrase.unfriend',
        'ordering' => 3,
        'value'    => 'user/unFriend',
        'icon'     => '',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_remove_as_admin'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'remove_as_admin',
        'label'    => 'page::phrase.remove_as_admin',
        'ordering' => 4,
        'value'    => 'page/removeAsAdmin',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_admin'],
            ['falsy', 'item.extra.can_cancel_admin_invite'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'set_as_admin',
        'label'    => 'page::phrase.set_as_admin',
        'ordering' => 5,
        'value'    => 'page/setAsAdmin',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_set_as_admin'],
            ['truthy', 'item.extra.can_cancel_admin_invite'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'remove_admin_invite',
        'label'    => 'page::phrase.remove_admin_invite',
        'ordering' => 6,
        'value'    => 'page/removeAdminInvite',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 1],
            ['truthy', 'item.extra.can_reassign_owner'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'reassign_owner',
        'label'    => 'page::phrase.reassign_owner',
        'ordering' => 7,
        'value'    => 'page/reassignOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_block'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'block_from_page',
        'label'    => 'page::phrase.block_from_page',
        'ordering' => 8,
        'value'    => 'page/blockFromPage',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.member_type', 0],
            ['truthy', 'item.extra.can_remove_member'],
        ],
        'menu'     => 'page.page_member.itemActionMenu',
        'name'     => 'remove_member',
        'label'    => 'page::phrase.remove_member',
        'ordering' => 9,
        'value'    => 'page/removeMember',
    ],
    [
        'tab'      => 'all',
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'all',
        'label'    => 'page::phrase.all_pages',
        'ordering' => 1,
        'value'    => 'viewAll',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'my',
        'label'    => 'page::phrase.my_pages',
        'ordering' => 2,
        'value'    => 'viewMyPages',
    ],
    [
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'page::phrase.my_pending_pages',
        'ordering' => 3,
        'value'    => 'viewMyPendingPages',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'page::phrase.friends_pages',
        'ordering' => 4,
        'value'    => 'viewFriendPages',
    ],
    [
        'tab'      => 'liked',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'like',
        'label'    => 'page::phrase.liked_pages',
        'ordering' => 5,
        'value'    => 'viewLikedPages',
    ],
    [
        'tab'      => 'invited',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'invited',
        'label'    => 'page::phrase.page_invites',
        'ordering' => 6,
        'value'    => 'viewInvitedPages',
    ],
    [
        'tab'      => 'page_claims',
        'showWhen' => [
            'and',
            ['truthy', 'acl.page.page.claim'],
        ],
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page_claim',
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'page_claims',
        'label'    => 'page::phrase.my_claim_requests',
        'ordering' => 7,
        'value'    => 'viewAll',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'or',
            ['truthy', 'acl.page.page.approve'],
        ],
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'menu'     => 'page.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'page::phrase.pending_pages',
        'ordering' => 8,
        'value'    => 'viewPendingPages',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.page.page.view'],
            ['falsy', 'is_hashtag'],
        ],
        'module_name'   => 'page',
        'resource_name' => 'page',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'page',
        'label'         => 'page::phrase.page_global_search_label',
        'ordering'      => 8,
        'value'         => 'searchGlobalPage',
    ],
    [
        'tab'      => 'page',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.page'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'page',
        'label'    => 'page::phrase.pages',
        'ordering' => 7,
        'to'       => '/page',
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'module_name'   => 'page',
        'resource_name' => 'page',
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'all',
        'label'         => 'core::phrase.all',
        'ordering'      => 0,
        'value'         => 'searchGlobalInPage',
    ],
    [
        'showWhen' => [],
        'menu'     => 'page.page.detailActionMenu',
        'name'     => 'invite',
        'label'    => 'page::phrase.invite_friends',
        'ordering' => 2,
        'value'    => 'page/inviteFriends',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_claim'],
        ],
        'menu'     => 'page.page.detailActionMenu',
        'name'     => 'claim',
        'label'    => 'page::phrase.claim_page',
        'ordering' => 3,
        'value'    => 'page/claim',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'page.page.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'page::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'page.page.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'page::phrase.sponsor_this_item',
        'ordering' => 4,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'page.page.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'page::phrase.un_sponsor_this_item',
        'ordering' => 4,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'page.page.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'apiVersion'],
        ],
        'menu'     => 'page.page.detailActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'page.page.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'page::phrase.delete',
        'ordering'  => 10,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'page',
        'label'     => 'page::phrase.pages',
        'ordering'  => 5,
        'value'     => '',
        'to'        => '/page',
        'as'        => 'item',
        'icon'      => 'flag-waving',
        'iconColor' => '#ff891f',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_share'],
        ],
        'params'   => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'menu'     => 'feed.itemShareActionsMenu',
        'name'     => 'share_on_page',
        'label'    => 'activity::phrase.share_on_page',
        'ordering' => 4,
        'value'    => 'shareOnPageProfile',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_pending', 0],
            ['truthy', 'item.extra.can_pin_item'],
            ['falsy', 'item.extra.can_review_feed'],
            ['truthy', 'profile_id'],
            ['or', ['eqeqeq', 'params._identity', '$.item.user'], ['eqeqeq', 'params._identity', '$.item.parent_user']],
            ['eq', 'profile_type', 'page'],
            ['noneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'pinItemOnPage',
        'label'    => 'page::phrase.pin_post_on_page',
        'ordering' => 2,
        'value'    => 'pinItem',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.is_pending', 0],
            ['truthy', 'item.extra.can_pin_item'],
            ['truthy', 'profile_id'],
            ['or', ['eqeqeq', 'params._identity', '$.item.user'], ['eqeqeq', 'params._identity', '$.item.parent_user']],
            ['eq', 'profile_type', 'page'],
            ['oneOf', 'item.pins', '$.profile_id'],
        ],
        'menu'     => 'feed.feed.itemActionMenu',
        'name'     => 'unpinItemOnPage',
        'label'    => 'activity::phrase.unpin_post',
        'ordering' => 3, 'value' => 'unpinItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
        ],
        'menu'     => 'page.page_claim.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'page::phrase.edit_request',
        'ordering' => 2,
        'value'    => 'page_claim/editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_denied'],
        ],
        'menu'     => 'page.page_claim.itemActionMenu',
        'name'     => 'resubmit',
        'label'    => 'page::phrase.resubmit',
        'ordering' => 3,
        'value'    => 'page_claim/resubmit',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
        ],
        'menu'     => 'page.page_claim.itemActionMenu',
        'name'     => 'cancel',
        'label'    => 'page::phrase.cancel_request',
        'ordering' => 4,
        'value'    => 'page_claim/cancelRequest',
    ],
    [
        'menu'     => 'page.page_claim.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'page.page_claim.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'page.page_claim.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'page.page_claim.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'menu'     => 'page.page_claim.sort_menu',
        'name'     => 'recent',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'page.page_claim.sort_menu',
        'name'     => 'most_member',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 2,
        'value'    => 'most_member',
    ],
    [
        'showWhen' => [
            'and',
            ['gte', 'apiVersion', 'v1.11'],
        ],
        'menu'     => 'page.manageMenu',
        'name'     => 'page_settings',
        'label'    => 'page::phrase.page_settings_uppercase_label',
        'ordering' => 0,
        'as'       => 'section',
    ],
    [
        'showWhen' => [],
        'menu'     => 'page.manageMenu',
        'name'     => 'page_info',
        'label'    => 'core::web.edit_page_info',
        'ordering' => 1,
        'value'    => 'page/editInfoPageItem',
        'icon'     => 'pencilline-o',
    ],
    [
        'showWhen' => [],
        'menu'     => 'page.manageMenu',
        'name'     => 'about_page',
        'label'    => 'page::web.edit_page_about',
        'ordering' => 2,
        'value'    => 'page/editAboutPageItem',
        'icon'     => 'info-circle-alt-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'page.manageMenu',
        'name'     => 'invite_friends',
        'label'    => 'core::web.invite',
        'ordering' => 3,
        'icon'     => 'user1-plus',
        'value'    => 'page/inviteFriends',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_new_admin'],
        ],
        'menu'     => 'page.manageMenu',
        'name'     => 'add_new_admin',
        'label'    => 'page::phrase.admins',
        'ordering' => 4,
        'icon'     => 'bell2-o',
        'value'    => 'page/manage-admin',
    ],
    [
        'showWhen' => [
            'and',
            ['gte', 'apiVersion', 'v1.9'],
            [
                'or',
                ['eq', 'session.user.role.id', 1],
                [
                    'and',
                    ['neq', 'item.module_name', 'page'],
                    ['truthy', 'acl.activity.feed.schedule_post'],
                ],
                [
                    'and',
                    ['eq', 'item.module_name', 'page'],
                    ['truthy', 'item.is_owner'],
                ],
            ],
        ],
        'menu'     => 'page.manageMenu',
        'name'     => 'schedule_post',
        'label'    => 'page::phrase.schedule_posts',
        'ordering' => 5,
        'icon'     => 'clock',
        'value'    => 'page/schedule-post',
    ],
    [
        'showWhen' => [
            'and',
            ['gte', 'apiVersion', 'v1.11'],
        ],
        'menu'     => 'page.manageMenu',
        'name'     => 'privacy_settings',
        'label'    => 'page::phrase.privacy_settings_uppercase_label',
        'ordering' => 7,
        'as'       => 'section',
    ],
    [
        'showWhen' => [],
        'menu'     => 'page.manageMenu',
        'name'     => 'permissions',
        'label'    => 'core::web.edit_permissions',
        'ordering' => 8,
        'icon'     => 'shield',
        'value'    => 'page/editPermissionPageItem',
    ],
    [
        'showWhen'  => [
            'and',
            ['gte', 'apiVersion', 'v1.11'],
        ],
        'menu'      => 'page.manageMenu',
        'name'      => 'page_menu_settings',
        'label'     => 'page::phrase.page_menu_settings_uppercase_label',
        'ordering'  => 10,
        'is_active' => 1,
        'as'        => 'section',
    ],
    [
        'showWhen' => [],
        'menu'     => 'page.manageMenu',
        'name'     => 'menu',
        'label'    => 'page::phrase.menus',
        'ordering' => 11,
        'icon'     => 'layers',
        'value'    => 'page/menuSetting',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'page.page.headerItemActionOnUserProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'acl.page.page.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'       => 'page.page.headerItemActionOnUserProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'page',
            'resource_name' => 'page',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'page.page.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'page.page.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'page.page.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'page.page.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 9,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'page.page.profileActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
];
