<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Attachment\\Http\\Resources\\v1\\FileType\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'attachment.type',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Data Grid',
    ],
    [
        'driver'      => 'MetaFox\\Attachment\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'        => 'form-settings',
        'name'        => 'attachment',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'is_active'   => true,
        'is_preload'  => false,
        'title'       => 'core::phrase.settings',
        'url'         => '/attachment/setting',
        'description' => 'attachments::phrase.edit_attachments_setting_desc',
        'type_label'  => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\Attachment\\Http\\Resources\\v1\\Attachment\\AttachmentItem',
        'type'       => 'json-resource',
        'name'       => 'core_attachment.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\Attachment\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'attachment',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
    [
        'driver'     => 'MetaFox\\Attachment\\Http\\Resources\\v1\\Attachment\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'core_attachment',
        'version'    => 'v1',
        'resolution' => 'mobile',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Mobile',
    ],
    [
        'driver'     => 'MetaFox\\Attachment\\Http\\Resources\\v1\\Attachment\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'core_attachment',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\Attachment\\Policies\\Handlers\\CanDownloadAttachment',
        'type'       => 'policy-rule',
        'name'       => 'downloadAttachment',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Policy Rule',
    ],
];
