<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\TourGuide\\Http\\Resources\\v1\\TourGuide\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'tourguide.tour_guide',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Http\\Resources\\v1\\Step\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'tourguide.tour_guide.step',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Data Grid Settings',
        'type_label' => 'Data Grid',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Models\\Step',
        'type'       => 'entity',
        'name'       => 'tour_guide_step',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Steps',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Models\\TourGuide',
        'type'       => 'entity',
        'name'       => 'tour_guide',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'Guides',
        'type_label' => 'Entity',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Http\\Resources\\v1\\Step\\StoreStepForm',
        'type'       => 'form',
        'name'       => 'tourguide.tour_guide_step.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Http\\Resources\\v1\\TourGuide\\StoreTourGuideForm',
        'type'       => 'form',
        'name'       => 'tourguide.tour_guide.store',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Http\\Resources\\v1\\Admin\\PositionSettingForm',
        'type'       => 'form-settings',
        'name'       => 'tourguide.position',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'url'        => '/tourguide/setting/position',
        'type_label' => 'Form Settings',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Http\\Resources\\v1\\Step\\StepItem',
        'type'       => 'json-resource',
        'name'       => 'tour_guide_step.item',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Json Resource',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Http\\Resources\\v1\\TourGuide\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'tour_guide',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Http\\Resources\\v1\\Completion\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'tour_guide_completion',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Http\\Resources\\v1\\Hidden\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'tour_guide_hidden',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Http\\Resources\\v1\\Step\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'tour_guide_step',
        'version'    => 'v1',
        'resolution' => 'web',
        'is_active'  => true,
        'is_preload' => false,
        'type_label' => 'Resource Web',
    ],
    [
        'driver'     => 'MetaFox\\TourGuide\\Http\\Resources\\v1\\PackageSetting',
        'type'       => 'package-setting',
        'name'       => 'tourguide',
        'version'    => 'v1',
        'is_active'  => true,
        'is_preload' => false,
    ],
];
