<?php

/* this is auto generated file */
return [
    [
        'showWhen'    => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'localization_settings',
        'label'       => 'core::phrase.settings',
        'ordering'    => 1,
        'to'          => '/localize/setting',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'countries',
        'label'       => 'core::phrase.countries',
        'ordering'    => 2,
        'to'          => '/localize/country/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'currencies',
        'label'       => 'core::phrase.currencies',
        'ordering'    => 3,
        'to'          => '/localize/currency/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'languages',
        'label'       => 'core::phrase.languages',
        'ordering'    => 4,
        'to'          => '/localize/language/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'phrases',
        'label'       => 'localize::phrase.phrases',
        'ordering'    => 5,
        'to'          => '/localize/phrase/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'missing_phrases',
        'label'       => 'localize::phrase.missing_phrases',
        'ordering'    => 6,
        'to'          => '/localize/phrase/browse/missing',
        'showWhen'    => ['eq', 'setting.app.env', 'local'],
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'localization',
        'name'        => 'time_zones',
        'label'       => 'core::phrase.time_zones',
        'ordering'    => 7,
        'to'          => '/localize/timezone/browse',
        'is_deleted'  => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'localize.admin',
        'name'     => 'settings',
        'label'    => 'core::phrase.settings',
        'ordering' => 1,
        'to'       => '/localize/setting',
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'country',
        'label'    => 'localize::phrase.countries',
        'ordering' => 2,
        'to'       => '/localize/country/browse',
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'currency',
        'label'    => 'localize::phrase.currencies',
        'ordering' => 4,
        'to'       => '/localize/currency/browse',
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'language',
        'label'    => 'localize::phrase.languages',
        'ordering' => 6,
        'to'       => '/localize/language/browse',
    ],
    [
        'menu'     => 'localize.admin',
        'name'     => 'phrases',
        'label'    => 'localize::phrase.phrases',
        'ordering' => 8,
        'to'       => '/localize/phrase/browse',
    ],
    [
        'menu'       => 'localize.admin',
        'name'       => 'timezone',
        'label'      => 'core::phrase.time_zones',
        'ordering'   => 11,
        'to'         => '/localize/timezone/browse',
        'is_deleted' => 1,
    ],
    [
        'menu'       => 'localize.admin',
        'name'       => 'import_translation',
        'label'      => 'localize::phrase.import_phrases',
        'ordering'   => 12,
        'to'         => '/localize/phrase/form-import',
        'is_deleted' => 1,
        'is_active'  => 0,
    ],
];
