<?php

/* this is auto generated file */
return [
    [
        'tab'      => 'quiz',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quizzes',
        'ordering' => 7,
        'to'       => '/quiz',
        'params'   => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'tab'      => 'quiz',
        'menu'     => 'page.page.profileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quizzes',
        'ordering' => 7,
        'to'       => '/quiz',
        'params'   => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'menu'     => 'quiz.quiz.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'quiz.quiz.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'quiz.quiz.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'quiz.quiz.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'quiz::phrase.edit',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'quiz::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'quiz::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'quiz::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'quiz::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'quiz::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'advertise/purchaseSponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'quiz::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'quiz.quiz.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'quiz::phrase.approve',
        'ordering' => 11,
        'value'    => 'approveItem',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'quiz.quiz.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'quiz::phrase.delete',
        'ordering'  => 12,
        'value'     => 'deleteItem',
    ],
    [
        'menu'     => 'quiz.quiz.sort_menu',
        'name'     => 'latest',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'latest',
    ],
    [
        'menu'     => 'quiz.quiz.sort_menu',
        'name'     => 'most_viewed',
        'label'    => 'core::phrase.sort.most_viewed',
        'ordering' => 2,
        'value'    => 'most_viewed',
    ],
    [
        'menu'     => 'quiz.quiz.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 3,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'quiz.quiz.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 4,
        'value'    => 'most_discussed',
    ],
    [
        'tab'      => 'all',
        'params'   => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'all_quiz',
        'label'    => 'quiz::phrase.all_quizzes',
        'ordering' => 1,
        'value'    => 'viewAll',
        'to'       => '/quiz/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'my_quiz',
        'label'    => 'quiz::phrase.my_quizzes',
        'ordering' => 2,
        'value'    => 'viewMyQuizzes',
        'to'       => '/quiz/my',
    ],
    [
        'tab'      => 'my_pending',
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'params'   => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'quiz::phrase.my_pending_quizzes',
        'ordering' => 3,
        'value'    => 'viewMyPendingQuizzes',
        'to'       => '/quiz/pending',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'friend_quiz',
        'label'    => 'quiz::phrase.friends_quizzes',
        'ordering' => 4,
        'value'    => 'viewFriendQuizzes',
        'to'       => '/quiz/friend',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'or',
            ['truthy', 'acl.quiz.quiz.approve'],
        ],
        'params'   => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'menu'     => 'quiz.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'quiz::phrase.pending_quizzes',
        'ordering' => 5,
        'value'    => 'viewPendingQuizzes',
        'to'       => '/quiz/pending',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
            ['falsy', 'is_hashtag'],
        ],
        'module_name'   => 'quiz',
        'resource_name' => 'quiz',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'quiz',
        'label'         => 'quiz::phrase.quiz_global_search_label',
        'ordering'      => 12,
        'value'         => 'searchGlobalQuiz',
    ],
    [
        'tab'      => 'quiz',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.quiz'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'quiz',
        'label'    => 'quiz::phrase.quizzes',
        'ordering' => 11,
        'to'       => '/quiz',
        'params'   => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'value'    => 'viewOnOwner',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
        ],
        'module_name'   => 'quiz',
        'resource_name' => 'quiz',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'quiz',
        'label'         => 'quiz::phrase.quiz_global_search_label',
        'ordering'      => 12,
        'value'         => 'searchGlobalQuiz',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
        ],
        'module_name'   => 'quiz',
        'resource_name' => 'quiz',
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'quiz',
        'label'         => 'quiz::phrase.quiz_global_search_label',
        'ordering'      => 12,
        'value'         => 'searchGlobalQuiz',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'quiz::phrase.edit',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'quiz::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'quiz::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'quiz::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'quiz::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'quiz::phrase.sponsor_this_item',
        'ordering' => 12,
        'value'    => 'advertise/purchaseSponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'quiz::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'unfeature',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 9,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'quiz.quiz.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'quiz::phrase.approve',
        'ordering' => 11,
        'value'    => 'approveItem',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'quiz.quiz.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'quiz::phrase.delete',
        'ordering'  => 12,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'quizzes',
        'label'     => 'quiz::phrase.quizzes',
        'ordering'  => 7,
        'value'     => '',
        'to'        => '/quiz',
        'as'        => 'item',
        'icon'      => 'question-mark',
        'iconColor' => '#6a50eb',
    ],
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.quiz.quiz.view'],
        ],
        'menu'          => 'search.mobileHashtagCategoryMenu',
        'name'          => 'quiz',
        'label'         => 'quiz::phrase.quiz_global_search_label',
        'ordering'      => 5,
        'resource_name' => 'quiz',
        'module_name'   => 'quiz',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'quiz.quiz.headerItemActionOnUserProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["truthy", "acl.quiz.quiz.create"],
            ["truthy", "item.is_owner"],
        ],
        'menu'       => 'quiz.quiz.headerItemActionOnUserProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'quiz.quiz.headerItemActionOnPageProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["truthy", "acl.quiz.quiz.create"],
            ["truthy", "item.profile_settings.quiz_share_quizzes"],
            ["falsy", "item.is_pending"],
        ],
        'menu'       => 'quiz.quiz.headerItemActionOnPageProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen'   => [],
        'label'      => '',
        'ordering'   => 1,
        'menu'       => 'quiz.quiz.headerItemActionOnGroupProfileMenu',
        'name'       => 'search',
        'params'     => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen'   => [
            "and",
            ["truthy", "acl.quiz.quiz.create"],
            ["truthy", "item.profile_settings.quiz_share_quizzes"],
            ["truthy", "item.is_member"],
            ["falsy", "item.is_muted"],
            ["falsy", "item.is_pending"],
        ],
        'menu'       => 'quiz.quiz.headerItemActionOnGroupProfileMenu',
        'name'       => 'add_item',
        'label'      => '',
        'ordering'   => 2,
        'params'     => [
            'module_name'   => 'quiz',
            'resource_name' => 'quiz',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
];
