<?php

/* this is auto generated file */
return [
    [
        'tab'      => 'live-video',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.live_video'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_videos',
        'ordering' => 5,
        'to'       => '/live-video',
        'params'   => [
            'module_name'   => 'live_video',
            'resource_name' => 'live_video',
        ],
        'value' => 'viewOnOwner',
    ],
    [
        'params' => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'all_streaming',
        'label'    => 'livestreaming::phrase.all_live_videos',
        'ordering' => 1,
        'value'    => 'viewAllStreaming',
    ],
    [
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'my_streaming',
        'label'    => 'livestreaming::phrase.my_live_videos',
        'ordering' => 2,
        'value'    => 'viewMyStreaming',
    ],
    [
        'params' => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'all',
        'label'    => 'livestreaming::phrase.all_videos',
        'ordering' => 3,
        'value'    => 'viewAll',
    ],
    [
        'params' => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'my',
        'label'    => 'livestreaming::phrase.my_videos',
        'ordering' => 4,
        'value'    => 'viewMyLiveVideos',
    ],
    [
        'params' => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'showWhen' => [
            'and',
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'livestreaming::phrase.my_pending_videos',
        'ordering' => 5,
        'value'    => 'viewMyPendingLiveVideos',
    ],
    [
        'params' => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'friend',
        'label'    => 'livestreaming::phrase.friends_videos',
        'ordering' => 6,
        'value'    => 'viewFriendLiveVideos',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.approve'],
        ],
        'params' => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'livestreaming::phrase.pending_videos',
        'ordering' => 7,
        'value'    => 'viewPendingLiveVideos',
    ],
    [
        'menu'     => 'livestreaming.live_video.filter_menu',
        'name'     => 'all',
        'label'    => 'core::phrase.when.all',
        'ordering' => 1,
        'value'    => 'all',
    ],
    [
        'menu'     => 'livestreaming.live_video.filter_menu',
        'name'     => 'this_month',
        'label'    => 'core::phrase.when.this_month',
        'ordering' => 2,
        'value'    => 'this_month',
    ],
    [
        'menu'     => 'livestreaming.live_video.filter_menu',
        'name'     => 'this_week',
        'label'    => 'core::phrase.when.this_week',
        'ordering' => 3,
        'value'    => 'this_week',
    ],
    [
        'menu'     => 'livestreaming.live_video.filter_menu',
        'name'     => 'today',
        'label'    => 'core::phrase.when.today',
        'ordering' => 4,
        'value'    => 'today',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['falsy', 'item.is_streaming'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'livestreaming::phrase.edit_live_video',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'livestreaming::phrase.approve',
        'ordering' => 1,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'livestreaming::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'livestreaming::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'livestreaming::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'livestreaming::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'livestreaming::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'livestreaming::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion'],
            ['falsy', 'item.is_featured'],
            ['falsy', 'item.is_processing'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'className' => 'itemPrimary',
        'menu'      => 'livestreaming.live_video.itemActionMenu',
        'name'      => 'feature',
        'label'     => 'core::phrase.feature',
        'ordering'  => 7,
        'value'     => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 7,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion'],
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'className' => 'itemPrimary',
        'menu'      => 'livestreaming.live_video.itemActionMenu',
        'name'      => 'unfeature',
        'label'     => 'core::phrase.un_feature',
        'ordering'  => 8,
        'value'     => 'unfeatureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'livestreaming.live_video.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'livestreaming::phrase.delete',
        'ordering'  => 17,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_off_notification'],
            ['falsy', 'item.is_owner'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'livestreaming.live_video.itemActionMenu',
        'name'      => 'on_notification',
        'label'     => 'livestreaming::phrase.turn_on_notification',
        'ordering'  => 14,
        'value'     => 'onNotification',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_off_notification'],
            ['falsy', 'item.is_owner'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'livestreaming.live_video.itemActionMenu',
        'name'      => 'off_notification',
        'label'     => 'livestreaming::phrase.turn_off_notification',
        'ordering'  => 15,
        'value'     => 'offNotification',
    ],
    [
        'menu'     => 'livestreaming.live_video.sort_menu',
        'name'     => 'recent',
        'label'    => 'core::phrase.sort.recent',
        'ordering' => 1,
        'value'    => 'recent',
    ],
    [
        'menu'     => 'livestreaming.live_video.sort_menu',
        'name'     => 'most_viewed',
        'label'    => 'core::phrase.sort.most_viewed',
        'ordering' => 2,
        'value'    => 'most_viewed',
    ],
    [
        'menu'     => 'livestreaming.live_video.sort_menu',
        'name'     => 'most_liked',
        'label'    => 'core::phrase.sort.most_liked',
        'ordering' => 3,
        'value'    => 'most_liked',
    ],
    [
        'menu'     => 'livestreaming.live_video.sort_menu',
        'name'     => 'most_discussed',
        'label'    => 'core::phrase.sort.most_discussed',
        'ordering' => 4,
        'value'    => 'most_discussed',
    ],
    [
        'menu'     => 'livestreaming.live_video.sort_menu',
        'name'     => 'a_to_z',
        'label'    => 'core::phrase.sort.a_to_z',
        'ordering' => 5,
        'value'    => 'a_to_z',
    ],
    [
        'menu'     => 'livestreaming.live_video.sort_menu',
        'name'     => 'z_to_a',
        'label'    => 'core::phrase.sort.z_to_a',
        'ordering' => 6,
        'value'    => 'z_to_a',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['falsy', 'item.is_streaming'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'livestreaming::phrase.edit_live_video',
        'ordering' => 1,
        'value'    => 'editItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'approve',
        'label'    => 'livestreaming::phrase.approve',
        'ordering' => 1,
        'value'    => 'approveItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'livestreaming::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'livestreaming::phrase.sponsor_in_feed',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'unsponsor_in_feed',
        'label'    => 'livestreaming::phrase.unsponsor_in_feed',
        'ordering' => 4,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'livestreaming::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'livestreaming::phrase.sponsor_this_item',
        'ordering' => 5,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'unsponsor',
        'label'    => 'livestreaming::phrase.unsponsor_this_item',
        'ordering' => 6,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion'],
            ['falsy', 'item.is_featured'],
            ['falsy', 'item.is_processing'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'className' => 'itemPrimary',
        'menu'      => 'livestreaming.live_video.detailActionMenu',
        'name'      => 'feature',
        'label'     => 'core::phrase.feature',
        'ordering'  => 7,
        'value'     => 'featureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 7,
        'value'    => 'featureFreeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion'],
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 7,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion'],
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'className' => 'itemPrimary',
        'menu'      => 'livestreaming.live_video.detailActionMenu',
        'name'      => 'unfeature',
        'label'     => 'core::phrase.un_feature',
        'ordering'  => 8,
        'value'     => 'unfeatureItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'livestreaming.live_video.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'livestreaming::phrase.delete',
        'ordering'  => 17,
        'value'     => 'deleteItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_off_notification'],
            ['falsy', 'item.is_owner'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'livestreaming.live_video.detailActionMenu',
        'name'      => 'on_notification',
        'label'     => 'livestreaming::phrase.turn_on_notification',
        'ordering'  => 14,
        'value'     => 'onNotification',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_off_notification'],
            ['falsy', 'item.is_owner'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'livestreaming.live_video.detailActionMenu',
        'name'      => 'off_notification',
        'label'     => 'livestreaming::phrase.turn_off_notification',
        'ordering'  => 15,
        'value'     => 'offNotification',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'livestreaming',
        'label'     => 'livestreaming::phrase.live_videos',
        'ordering'  => 17,
        'value'     => '',
        'to'        => '/livestreaming',
        'as'        => 'item',
        'icon'      => 'videocam',
        'iconColor' => '#ff564a',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.view'],
        ],
        'module_name'   => 'livestreaming',
        'resource_name' => 'live_video',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'live_video',
        'label'         => 'livestreaming::phrase.live_video_global_search_label',
        'ordering'      => 3,
        'value'         => 'searchGlobalLiveVideo',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.view'],
        ],
        'module_name'   => 'livestreaming',
        'resource_name' => 'live_video',
        'menu'          => 'search.mobileHashtagCategoryMenu',
        'name'          => 'live_video',
        'label'         => 'livestreaming::phrase.live_video_global_search_label',
        'ordering'      => 2,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.view'],
        ],
        'module_name'   => 'livestreaming',
        'resource_name' => 'live_video',
        'menu'          => 'group.mobileCategoryMenu',
        'name'          => 'live_video',
        'label'         => 'livestreaming::phrase.live_video_global_search_label',
        'ordering'      => 3,
        'value'         => 'searchGlobalLiveVideo',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.view'],
        ],
        'module_name'   => 'livestreaming',
        'resource_name' => 'live_video',
        'menu'          => 'page.mobileCategoryMenu',
        'name'          => 'live_video',
        'label'         => 'livestreaming::phrase.live_video_global_search_label',
        'ordering'      => 3,
        'value'         => 'searchGlobalLiveVideo',
    ],
    [
        'description' => 'Go Live',
        'post_type'   => 'live_video',
        'icon_color'  => '#ff564a',
        'menu'        => 'feed.feed.feedComposerMenu',
        'name'        => 'go_live',
        'label'       => 'livestreaming::phrase.go_live',
        'ordering'    => 5,
        'as'          => 'post.live_video',
        'value'       => 'go_live',
        'icon'        => 'videocam',
        'to'          => 'go_live',
        'action'      => 'go_live',
        'showWhen'    => [
            'and',
            [
                'and',
                ['truthy', 'acl.livestreaming.live_video.create'],
                ['falsy', 'setting.livestreaming.display_live_section_on_mobile'],
                ['truthy', 'isHomeScreen'],
                ['truthy', 'setting.livestreaming.streaming_service_enable'],
            ],
        ],
    ],
    [
        'description' => 'Go Live',
        'post_type'   => 'live_video',
        'icon_color'  => '#ff564a',
        'menu'        => 'user.user.feedComposerMenu',
        'name'        => 'go_live',
        'label'       => 'livestreaming::phrase.go_live',
        'ordering'    => 5,
        'as'          => 'post.live_video',
        'value'       => 'go_live',
        'icon'        => 'videocam',
        'to'          => 'go_live',
        'action'      => 'go_live',
        'showWhen'    => [
            'and',
            [
                'and',
                ['truthy', 'acl.livestreaming.live_video.create'],
                ['truthy', 'isHomeScreen'],
                ['truthy', 'item.is_owner'],
                ['truthy', 'setting.livestreaming.streaming_service_enable'],
            ],
        ],
    ],
    [
        'description' => 'Go Live',
        'post_type'   => 'live_video',
        'icon_color'  => '#ff564a',
        'menu'        => 'group.group.feedComposerMenu',
        'name'        => 'go_live',
        'label'       => 'livestreaming::phrase.go_live',
        'ordering'    => 5,
        'as'          => 'post.live_video',
        'value'       => 'go_live',
        'icon'        => 'videocam',
        'to'          => 'go_live',
        'action'      => 'go_live',
        'showWhen'    => [
            'and',
            [
                'and',
                ['truthy', 'acl.livestreaming.live_video.create'],
                ['truthy', 'item.profile_settings.live_video_share_live_videos'],
                ['truthy', 'isHomeScreen'],
                ['truthy', 'setting.livestreaming.streaming_service_enable'],
            ],
        ],
    ],
    [
        'description' => 'Go Live',
        'post_type'   => 'live_video',
        'icon_color'  => '#ff564a',
        'menu'        => 'page.page.feedComposerMenu',
        'name'        => 'go_live',
        'label'       => 'livestreaming::phrase.go_live',
        'ordering'    => 5,
        'as'          => 'post.live_video',
        'value'       => 'go_live',
        'icon'        => 'videocam',
        'to'          => 'go_live',
        'action'      => 'go_live',
        'showWhen'    => [
            'and',
            [
                'and',
                ['truthy', 'acl.livestreaming.live_video.create'],
                ['truthy', 'item.profile_settings.live_video_share_live_videos'],
                ['truthy', 'isHomeScreen'],
                ['truthy', 'setting.livestreaming.streaming_service_enable'],
            ],
        ],
    ],
    [
        'tab'      => 'live-video',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_videos',
        'ordering' => 9,
        'to'       => '/live-video',
        'params'   => [
            'module_name'   => 'live_video',
            'resource_name' => 'live_video',
        ],
        'value' => 'viewOnOwner',
    ],
    [
        'tab'      => 'live-video',
        'showWhen' => [],
        'menu'     => 'page.page.profileMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_videos',
        'ordering' => 9,
        'to'       => '/live-video',
        'params'   => [
            'module_name'   => 'live_video',
            'resource_name' => 'live_video',
        ],
        'value' => 'viewOnOwner',
    ],
    [
        'showWhen' => [],
        'label'    => '',
        'ordering' => 1,
        'menu'     => 'livestreaming.live_video.headerItemActionOnUserProfileMenu',
        'name'     => 'search',
        'params'   => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'livestreaming.live_video.headerItemActionOnUserProfileMenu',
        'name'     => 'add_item',
        'label'    => '',
        'ordering' => 2,
        'params'   => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen' => [],
        'label'    => '',
        'ordering' => 1,
        'menu'     => 'livestreaming.live_video.headerItemActionOnPageProfileMenu',
        'name'     => 'search',
        'params'   => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.create'],
            ['truthy', 'item.profile_settings.live_video_share_live_videos'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'livestreaming.live_video.headerItemActionOnPageProfileMenu',
        'name'     => 'add_item',
        'label'    => '',
        'ordering' => 2,
        'params'   => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
    [
        'showWhen' => [],
        'label'    => '',
        'ordering' => 1,
        'menu'     => 'livestreaming.live_video.headerItemActionOnGroupProfileMenu',
        'name'     => 'search',
        'params'   => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'icon'       => 'search-o',
        'value'      => 'searchItemOnTab',
        'actionName' => 'searchInOwner',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.create'],
            ['truthy', 'item.profile_settings.live_video_share_live_videos'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'livestreaming.live_video.headerItemActionOnGroupProfileMenu',
        'name'     => 'add_item',
        'label'    => '',
        'ordering' => 2,
        'params'   => [
            'module_name'   => 'livestreaming',
            'resource_name' => 'live_video',
        ],
        'icon'       => 'plus',
        'value'      => 'addItemOnTab',
        'actionName' => 'addItem',
    ],
];
