<?php

/* this is auto generated file */
return [
    [
        'subInfo'  => 'livestreaming::phrase.browse_live_videos_you_like_to_watch',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_videos',
        'ordering' => 10,
        'icon'     => 'ico-videocam',
        'to'       => '/live-video',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.livestreaming.live_video.create'],
            ['truthy', 'setting.livestreaming.streaming_service_enable'],
        ],
        'menu'     => 'core.quickCreateMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_video',
        'icon'     => 'ico-videocam',
        'ordering' => 8,
        'to'       => '/live-video/add',
    ],
    [
        'subInfo'  => 'livestreaming::phrase.browse_live_videos_you_like_to_watch',
        'menu'     => 'core.primaryMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_videos',
        'ordering' => 10,
        'icon'     => 'ico-videocam',
        'to'       => '/live-video',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'livestreaming::phrase.home',
        'ordering' => 1,
        'icon'     => 'ico-video-player-o',
        'to'       => '/live-video',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['falsy', 'item.is_streaming'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'livestreaming::phrase.edit_live_video',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['truthy', 'item.is_streaming'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'manage',
        'label'    => 'livestreaming::phrase.manage_live_video',
        'ordering' => 2,
        'value'    => 'editLivestream',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'livestreaming::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'livestreaming::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'livestreaming::phrase.un_sponsor_in_feed',
        'ordering' => 6,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'livestreaming::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'livestreaming::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'livestreaming::phrase.unsponsor_this_item',
        'ordering' => 8,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'livestreaming.live_video.detailActionMenu',
        'name'       => 'feature',
        'label'      => 'core::phrase.feature',
        'ordering'   => 9,
        'value'      => 'featureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 9,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'livestreaming.live_video.detailActionMenu',
        'name'       => 'remove_feature',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 10,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
        ],
        'menu'     => 'livestreaming.live_video.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'livestreaming.live_video.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'livestreaming::phrase.delete',
        'ordering'  => 18,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_off_notification'],
            ['falsy', 'item.is_owner'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'livestreaming.live_video.detailActionMenu',
        'name'      => 'on_notification',
        'label'     => 'livestreaming::phrase.turn_on_notification',
        'ordering'  => 16,
        'value'     => 'livestreaming/onNotification',
        'icon'      => 'ico-bell2-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_off_notification'],
            ['falsy', 'item.is_owner'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'livestreaming.live_video.detailActionMenu',
        'name'      => 'off_notification',
        'label'     => 'livestreaming::phrase.turn_off_notification',
        'ordering'  => 17,
        'value'     => 'livestreaming/offNotification',
        'icon'      => 'ico-bell2-off-o',
    ],
    [
        'tab'      => 'live_video',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.livestreaming.live_video.create'],
            ['truthy', 'item.profile_settings.live_video_share_live_videos'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'livestreaming.live_video.headerItemActionOnGroupProfileMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.create_live_video',
        'ordering' => 1,
        'to'       => '/live-video/add?owner_id=:id',
    ],
    [
        'tab'      => 'live_video',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.livestreaming.live_video.create'],
            ['truthy', 'item.profile_settings.live_video_share_live_videos'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'livestreaming.live_video.headerItemActionOnPageProfileMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.create_live_video',
        'ordering' => 1,
        'to'       => '/live-video/add?owner_id=:id',
    ],
    [
        'tab'      => 'live_video',
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'livestreaming.live_video.headerItemActionOnUserProfileMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.create_live_video',
        'ordering' => 1,
        'to'       => '/live-video/add?owner_id=:id',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['falsy', 'item.is_streaming'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'livestreaming::phrase.edit_live_video',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
            ['truthy', 'item.is_streaming'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'manage',
        'label'    => 'livestreaming::phrase.manage_live_video',
        'ordering' => 2,
        'value'    => 'editLivestream',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'livestreaming::phrase.approve',
        'ordering' => 3,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'livestreaming::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'livestreaming::phrase.sponsor_in_feed',
        'ordering' => 5,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'livestreaming::phrase.un_sponsor_in_feed',
        'ordering' => 6,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'livestreaming::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'livestreaming::phrase.sponsor_this_item',
        'ordering' => 7,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'livestreaming::phrase.unsponsor_this_item',
        'ordering' => 8,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'livestreaming.live_video.itemActionMenu',
        'name'       => 'feature',
        'label'      => 'core::phrase.feature',
        'ordering'   => 9,
        'value'      => 'featureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 9,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'       => 'livestreaming.live_video.itemActionMenu',
        'name'       => 'remove_feature',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 10,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
        ],
        'menu'     => 'livestreaming.live_video.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'livestreaming.live_video.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'livestreaming::phrase.delete',
        'ordering'  => 18,
        'value'     => 'deleteItem',
        'icon'      => 'ico-trash-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_off_notification'],
            ['falsy', 'item.is_owner'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'livestreaming.live_video.itemActionMenu',
        'name'      => 'on_notification',
        'label'     => 'livestreaming::phrase.turn_on_notification',
        'ordering'  => 16,
        'value'     => 'livestreaming/onNotification',
        'icon'      => 'ico-bell2-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'item.is_off_notification'],
            ['falsy', 'item.is_owner'],
        ],
        'className' => 'itemDelete',
        'menu'      => 'livestreaming.live_video.itemActionMenu',
        'name'      => 'off_notification',
        'label'     => 'livestreaming::phrase.turn_off_notification',
        'ordering'  => 17,
        'value'     => 'livestreaming/offNotification',
        'icon'      => 'ico-bell2-off-o',
    ],
    [
        'tab'      => 'all_streaming',
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'all_streaming',
        'label'    => 'livestreaming::phrase.all_live_videos',
        'ordering' => 2,
        'icon'     => 'ico-videocam-o',
        'to'       => '/live-video/all-streaming',
    ],
    [
        'tab'      => 'my_streaming',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'my_streaming',
        'label'    => 'livestreaming::phrase.my_live_videos',
        'ordering' => 3,
        'icon'     => 'ico-user-man-o',
        'to'       => '/live-video/my-streaming',
    ],
    [
        'tab'      => 'all',
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'all',
        'label'    => 'livestreaming::phrase.all_videos',
        'ordering' => 4,
        'icon'     => 'ico-comment-play-o',
        'to'       => '/live-video/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'my',
        'label'    => 'livestreaming::phrase.my_videos',
        'ordering' => 5,
        'icon'     => 'ico-user-man-o',
        'to'       => '/live-video/my',
    ],
    [
        'tab'      => 'my_pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'livestreaming::phrase.my_pending_videos',
        'ordering' => 6,
        'icon'     => 'ico-user1-clock-o',
        'to'       => '/live-video/my-pending',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['falsy', 'setting.core.general.friends_only_community'],
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'friends',
        'label'    => 'livestreaming::phrase.friends_videos',
        'ordering' => 7,
        'icon'     => 'ico-user1-two-o',
        'to'       => '/live-video/friend',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.livestreaming.live_video.approve'],
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'livestreaming::phrase.pending_videos',
        'ordering' => 8,
        'icon'     => 'ico-clock-o',
        'to'       => '/live-video/pending',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.livestreaming.live_video.create'],
            ['truthy', 'setting.livestreaming.streaming_service_enable'],
        ],
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'menu'     => 'livestreaming.sidebarMenu',
        'name'     => 'add',
        'label'    => 'livestreaming::phrase.create_live_video',
        'ordering' => 9,
        'as'       => 'sidebarButton',
        'icon'     => 'ico-plus',
        'to'       => '/live-video/add',
    ],
    [
        'tab'      => 'live-video',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            [
                'or',
                ['truthy', 'acl.group.group.moderate'],
                ['truthy', 'item.is_member'],
            ],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_videos',
        'ordering' => 9,
        'to'       => '/live-video',
    ],
    [
        'tab'      => 'live-video',
        'showWhen' => [],
        'menu'     => 'page.page.profileMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_videos',
        'ordering' => 9,
        'to'       => '/live-video',
    ],
    [
        'tab'      => 'live-video',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_menu_settings.live_video'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_videos',
        'ordering' => 9,
        'to'       => '/live-video',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_video_global_search_label',
        'ordering' => 3,
        'to'       => '/search/live-video',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_video_global_search_label',
        'ordering' => 2,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.view'],
        ],
        'menu'     => 'search.webHashtagCategoryMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_video_global_search_label',
        'ordering' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.livestreaming.live_video.view'],
        ],
        'menu'     => 'group.searchWebCategoryMenu',
        'name'     => 'live_video',
        'label'    => 'livestreaming::phrase.live_video_global_search_label',
        'ordering' => 2,
    ],
];
