<?php

/* this is auto generated file */
return [
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'members',
        'name'        => 'members-settings',
        'label'       => 'core::phrase.settings',
        'ordering'    => 1,
        'to'          => '/user/setting',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'members',
        'name'        => 'genders',
        'label'       => 'user::phrase.genders',
        'ordering'    => 2,
        'to'          => '/user/user-gender/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'members',
        'name'        => 'relation',
        'label'       => 'user::phrase.relations',
        'ordering'    => 3,
        'to'          => '/user/relation/browse',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'user.admin',
        'name'     => 'userSettings',
        'label'    => 'core::phrase.settings',
        'ordering' => 1,
        'as'       => 'subMenu',
        'to'       => '/user/setting',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'user.admin',
        'name'     => 'userRegistration',
        'label'    => 'user::phrase.registration_settings',
        'ordering' => 2,
        'as'       => 'subMenu',
        'to'       => '/user/setting/registration',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'user.admin',
        'name'     => 'userSecurity',
        'label'    => 'user::phrase.security_settings',
        'ordering' => 2,
        'as'       => 'subMenu',
        'to'       => '/user/setting/security',
    ],
    [
        'menu'     => 'user.admin',
        'name'     => 'manageMembers',
        'label'    => 'user::phrase.members',
        'ordering' => 3,
        'as'       => 'subMenu',
        'to'       => '/user/user/browse',
    ],
    [
        'menu'     => 'user.admin',
        'name'     => 'manage_cancelled_members',
        'label'    => 'user::phrase.cancelled_members',
        'ordering' => 4,
        'to'       => '/user/cancelled/browse/feedback',
    ],
    [
        'menu'     => 'user.admin',
        'name'     => 'manageGenders',
        'label'    => 'user::phrase.genders',
        'ordering' => 5,
        'as'       => 'subMenu',
        'to'       => '/user/user-gender/browse',
    ],
    [
        'menu'     => 'user.admin',
        'name'     => 'userRelation',
        'label'    => 'user::phrase.relations',
        'ordering' => 7,
        'as'       => 'subMenu',
        'to'       => '/user/relation/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'members',
        'name'        => 'cancelReason',
        'label'       => 'user::phrase.cancel_reasons',
        'ordering'    => 7,
        'to'          => '/user/cancel-reason/browse',
    ],
    [
        'menu'     => 'user.admin',
        'name'     => 'cancelReason',
        'label'    => 'user::phrase.cancel_reasons',
        'ordering' => 9,
        'to'       => '/user/cancel-reason/browse',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'members',
        'name'        => 'inactiveUser',
        'label'       => 'user::phrase.inactive_user',
        'ordering'    => 8,
        'to'          => '/user/inactive/browse',
    ],
    [
        'menu'     => 'user.admin',
        'name'     => 'inactiveUser',
        'label'    => 'user::phrase.inactive_user',
        'ordering' => 11,
        'to'       => '/user/inactive/browse',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'user.admin',
        'name'     => 'export_histories',
        'label'    => 'user::phrase.export_histories',
        'ordering' => 12,
        'to'       => '/user/export-process/browse',
    ],
    [
        'name'     => 'basic_info',
        'menu'     => 'user.user.tabsEditMenu',
        'ordering' => 1,
        'label'    => 'user::phrase.basic_information',
        'value'    => 'editBasicInfo',
    ],
    [
        'name'     => 'custom_fields',
        'menu'     => 'user.user.tabsEditMenu',
        'ordering' => 2,
        'label'    => 'user::phrase.custom_fields',
        'value'    => 'editCustomFields',
    ],
    [
        'name'     => 'profile_privacy',
        'menu'     => 'user.user.tabsEditMenu',
        'ordering' => 3,
        'label'    => 'core::web.profile_privacy',
        'value'    => 'editProfilePrivacy',
    ],
    [
        'name'     => 'notification_setting',
        'menu'     => 'user.user.tabsEditMenu',
        'ordering' => 4,
        'label'    => 'notification::phrase.notification_settings',
        'value'    => 'editNotificationSetting',
    ],
];
