<?php

/* this is auto generated file */
return [
    [
        'showWhen'      => [
            'and',
            ['truthy', 'acl.user.user.view'],
            ['falsy', 'is_hashtag'],
        ],
        'module_name'   => 'user',
        'resource_name' => 'user',
        'menu'          => 'search.mobileCategoryMenu',
        'name'          => 'user',
        'label'         => 'user::phrase.user_global_search_label',
        'ordering'      => 1,
        'value'         => 'searchGlobalUser',
    ],
    [
        'selectedWhen' => ['eq', 'item.sort_type', 1],
        'menu'         => 'user.shortcut.itemActionMenu',
        'name'         => 'auto',
        'label'        => 'user::phrase.sort_automatically',
        'ordering'     => 1,
        'value'        => 'user/shortcut/sortAutomatically',
    ],
    [
        'selectedWhen' => ['eq', 'item.sort_type', 0],
        'menu'         => 'user.shortcut.itemActionMenu',
        'name'         => 'hide',
        'label'        => 'user::phrase.hide',
        'ordering'     => 3,
        'value'        => 'user/shortcut/hide',
    ],
    [
        'selectedWhen' => ['eq', 'item.sort_type', 2],
        'menu'         => 'user.shortcut.itemActionMenu',
        'name'         => 'pin',
        'label'        => 'user::phrase.pin_to_top',
        'ordering'     => 2,
        'value'        => 'user/shortcut/pinToTop',
    ],
    [
        'tab'        => 'all',
        'showWhen'   => [
            'and',
            ['falsy', 'acl.user.user.isGuest'],
        ],
        'params'     => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'       => 'user.tabMenu',
        'name'       => 'all',
        'label'      => 'user::phrase.all_members',
        'ordering'   => 1,
        'value'      => 'viewAll',
        'icon'       => 'ico ico-user1-three',
        'to'         => '/user/all',
        'is_deleted' => 1,
    ],
    [
        'tab'        => 'recommend',
        'showWhen'   => [
            'and',
            ['falsy', 'acl.user.user.isGuest'],
        ],
        'params'     => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'       => 'user.tabMenu',
        'name'       => 'recommend',
        'label'      => 'user::phrase.members_you_may_know',
        'ordering'   => 2,
        'value'      => 'viewRecommendUsers',
        'to'         => '/user/recommend',
        'is_deleted' => 1,
    ],
    [
        'tab'        => 'recent',
        'params'     => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'       => 'user.tabMenu',
        'name'       => 'recent',
        'label'      => 'user::phrase.recent_active',
        'ordering'   => 3,
        'value'      => 'viewRecentUsers',
        'to'         => '/user/recent',
        'is_deleted' => 1,
    ],
    [
        'tab'        => 'featured',
        'params'     => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'       => 'user.tabMenu',
        'name'       => 'featured',
        'label'      => 'user::phrase.featured_members',
        'ordering'   => 4,
        'value'      => 'viewFeaturedUsers',
        'to'         => '/user/featured',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            [
                'includes',
                'item.friendship',
                [0, 7],
            ],
            ['truthy', 'item.extra.can_add_friend'],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'add_friend',
        'label'    => 'user::phrase.add_friend',
        'ordering' => 1,
        'value'    => 'user/addFriend',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 3],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'user::phrase.cancel_request',
        'ordering' => 2,
        'value'    => 'user/cancelRequest',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 2],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'confirm_request',
        'label'    => 'user::phrase.accept',
        'ordering' => 4,
        'value'    => 'user/acceptFriendRequest',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.friend.friend_list.update'],
            ['eq', 'item.friendship', 1],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'edit_list',
        'label'    => 'user::phrase.move_to_friends_list',
        'ordering' => 4,
        'value'    => 'friend/assignFriendList',
    ],
    [
        'style'    => 'danger',
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 2],
        ],
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'delete_request',
        'label'    => 'user::phrase.delete',
        'ordering' => 5,
        'value'    => 'user/denyFriendRequest',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 1],
        'style'    => 'danger',
        'menu'     => 'user.user.itemActionMenu',
        'name'     => 'unfriend',
        'label'    => 'user::phrase.unfriend',
        'ordering' => 7,
        'value'    => 'user/unFriend',
    ],
    [
        'showWhen' => [
            'and',
            [
                'includes',
                'item.friendship',
                [0, 7],
            ],
            ['truthy', 'item.extra.can_add_friend'],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'add_friend',
        'label'    => 'user::phrase.add_friend',
        'ordering' => 1,
        'value'    => 'user/addFriend',
    ],
    [
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 3],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'cancel_request',
        'label'    => 'user::phrase.cancel_request',
        'ordering' => 2,
        'value'    => 'user/cancelRequest',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 2],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'confirm_request',
        'label'    => 'user::phrase.accept',
        'ordering' => 3,
        'value'    => 'user/acceptFriendRequest',
    ],
    [
        'style'    => 'danger',
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 2],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'delete_request',
        'label'    => 'user::phrase.delete',
        'ordering' => 4,
        'value'    => 'user/denyFriendRequest',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 1],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'edit_list',
        'label'    => 'user::phrase.move_to_friends_list',
        'ordering' => 5,
        'value'    => 'friend/assignFriendList',
    ],
    [
        'style'    => 'danger',
        'showWhen' => [
            'and',
            ['eq', 'item.friendship', 1],
        ],
        'menu'     => 'user.user.profileActionMenu',
        'name'     => 'un_friend',
        'label'    => 'user::phrase.un_friend',
        'ordering' => 7,
        'value'    => 'user/unFriend',
    ],
    [
        'tab'      => 'about',
        'showWhen' => [
            'and',
            ['truthy', 'item.profile_settings.profile_profile_info'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'about',
        'label'    => 'user::phrase.about',
        'ordering' => 2,
        'to'       => '/about',
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'value'    => 'userInfo',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 3],
        'menu'     => 'user.user.profilePopoverMenu',
        'name'     => 'cancel_request',
        'label'    => 'user::phrase.cancel_request',
        'ordering' => 1,
        'value'    => 'user/cancelRequest',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 1],
        'menu'     => 'user.user.profilePopoverMenu',
        'name'     => 'edit_list',
        'label'    => 'user::phrase.move_to_friends_list',
        'ordering' => 2,
        'value'    => 'friend/assignFriendList',
    ],
    [
        'showWhen' => ['eq', 'item.friendship', 1],
        'style'    => 'danger',
        'menu'     => 'user.user.profilePopoverMenu',
        'name'     => 'delete',
        'label'    => 'user::phrase.unfriend',
        'ordering' => 3,
        'value'    => 'user/unFriend',
        'icon'     => 'ico ico-user3-minus-o',
    ],
    [
        'style'    => 'danger',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_block'],
            ['falsy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'user.user.profilePopoverMenu',
        'name'     => 'block',
        'label'    => 'user::phrase.block_this_user',
        'ordering' => 4,
        'value'    => 'blockItem',
    ],
    [
        'menu'     => 'user.user.sort_menu',
        'name'     => 'full_name',
        'label'    => 'core::phrase.name',
        'ordering' => 1,
        'value'    => 'full_name',
    ],
    [
        'menu'     => 'user.user.sort_menu',
        'name'     => 'last_login',
        'label'    => 'user::phrase.last_login',
        'ordering' => 2,
        'value'    => 'last_login',
    ],
    [
        'menu'     => 'user.user.sort_menu',
        'name'     => 'last_activity',
        'label'    => 'user::phrase.last_activity',
        'ordering' => 2,
        'value'    => 'last_activity',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'user.user.detailActionMenu',
        'name'     => 'feature',
        'label'    => 'user::phrase.feature',
        'ordering' => 1,
        'value'    => 'featureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'user.user.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 8,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'user.user.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 8,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'apiVersion', 'v1.10'],
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
        ],
        'menu'     => 'user.user.detailActionMenu',
        'name'     => 'delete_feature',
        'label'    => 'user::phrase.un_feature',
        'ordering' => 1,
        'value'    => 'unfeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
            ['truthy', 'apiVersion', 'v1.10'],
        ],
        'menu'     => 'user.user.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 8,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'color'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'user.user.detailActionMenu',
        'name'     => 'edit_profile',
        'label'    => 'user::phrase.edit_profile',
        'ordering' => 2,
        'value'    => 'user/editItem',
        'icon'     => '',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_add_cover'],
        ],
        'menu'     => 'user.user.detailActionMenu',
        'name'     => 'update_cover',
        'label'    => 'user::phrase.update_cover',
        'ordering' => 3,
        'value'    => '@app/EDIT_ITEM_COVER',
        'icon'     => '',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'user.user.detailActionMenu',
        'name'     => 'update_avatar',
        'label'    => 'user::phrase.update_avatar',
        'ordering' => 4,
        'value'    => '@app/EDIT_ITEM_AVATAR',
        'icon'     => '',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_edit_cover'],
        ],
        'menu'      => 'user.user.detailActionMenu',
        'name'      => 'remove_cover',
        'label'     => 'user::phrase.remove_cover_photo',
        'ordering'  => 5,
        'value'     => 'removeCoverPhoto',
        'icon'      => '',
        'is_active' => 1,
    ],
    [
        'showWhen' => [],
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'user.user.detailActionMenu',
        'name'     => 'copy_link',
        'label'    => 'user::phrase.copy_link_profile',
        'ordering' => 6,
        'value'    => 'copyLink',
    ],
    [
        'style'    => 'danger',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_block'],
            ['falsy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'user.user.detailActionMenu',
        'name'     => 'block',
        'label'    => 'user::phrase.block_this_user',
        'ordering' => 10,
        'value'    => 'blockItem',
    ],
    [
        'style'    => 'primary',
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unblock'],
            ['truthy', 'item.is_blocked'],
            ['neq', 'item.friendship', 5],
        ],
        'menu'     => 'user.user.detailActionMenu',
        'name'     => 'unblock',
        'label'    => 'user::phrase.un_block_this_user',
        'ordering' => 10,
        'value'    => 'unblockItem',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'core.bodyMenu',
        'name'      => 'member',
        'label'     => 'user::phrase.members',
        'ordering'  => 10,
        'value'     => '',
        'to'        => '/user',
        'as'        => 'item',
        'icon'      => 'user1-three',
        'iconColor' => '#1d6f96',
    ],
    [
        'tab'      => 'all',
        'showWhen' => [
            'and',
            ['falsy', 'acl.user.user.isGuest'],
        ],
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'user.sidebarMenu',
        'name'     => 'all',
        'label'    => 'user::phrase.all_members',
        'ordering' => 1,
        'value'    => 'viewAll',
        'icon'     => 'ico ico-user1-three',
        'to'       => '/user/all',
    ],
    [
        'tab'      => 'recommend',
        'showWhen' => [
            'and',
            ['falsy', 'acl.user.user.isGuest'],
        ],
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'user.sidebarMenu',
        'name'     => 'recommend',
        'label'    => 'user::phrase.members_you_may_know',
        'ordering' => 2,
        'value'    => 'viewRecommendUsers',
        'to'       => '/user/recommend',
    ],
    [
        'tab'      => 'recent',
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'user.sidebarMenu',
        'name'     => 'recent',
        'label'    => 'user::phrase.recent_active',
        'ordering' => 3,
        'value'    => 'viewRecentUsers',
        'to'       => '/user/recent',
    ],
    [
        'tab'      => 'featured',
        'params'   => [
            'module_name'   => 'user',
            'resource_name' => 'user',
        ],
        'menu'     => 'user.sidebarMenu',
        'name'     => 'featured',
        'label'    => 'user::phrase.featured_members',
        'ordering' => 4,
        'value'    => 'viewFeaturedUsers',
        'to'       => '/user/featured',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'account',
        'label'    => 'user::phrase.account_settings_uppercase_label',
        'ordering' => 1,
        'as'       => 'section',
    ],
    [
        'menu'      => 'user.settingMenu',
        'name'      => 'edit_account',
        'label'     => 'user::phrase.edit_account',
        'ordering'  => 2,
        'to'        => '/settings/editAccount',
        'icon'      => 'pencilline-o',
        'iconColor' => '#1E90FF',
    ],
    [
        'showWhen'  => ['and', ['truthy', 'acl.user.user.update']],
        'menu'      => 'user.settingMenu',
        'name'      => 'edit_profile_info',
        'label'     => 'user::phrase.edit_profile_info',
        'ordering'  => 3,
        'to'        => '/settings/editProfileInfo',
        'icon'      => 'info-circle-alt-o',
        'iconColor' => '#1E90FF',
    ],
    [
        'menu'      => 'user.settingMenu',
        'name'      => 'language',
        'label'     => 'core::web.language',
        'ordering'  => 4,
        'to'        => '/settings/language',
        'icon'      => 'language',
        'iconColor' => '#1E90FF',
    ],
    [
        'menu'      => 'user.settingMenu',
        'name'      => 'video_settings',
        'label'     => 'user::web.account_video_settings',
        'ordering'  => 5,
        'to'        => '/settings/media',
        'icon'      => 'video-player-o',
        'iconColor' => '#1E90FF',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'privacy_setting',
        'label'    => 'user::phrase.privacy_settings_uppercase_label',
        'ordering' => 7,
        'as'       => 'section',
    ],
    [
        'showWhen'  => ['and', ['truthy', 'acl.user.user.update']],
        'menu'      => 'user.settingMenu',
        'name'      => 'profile',
        'label'     => 'user::phrase.your_profile',
        'ordering'  => 8,
        'to'        => '/settings/profilePrivacy',
        'icon'      => 'shield-o',
        'iconColor' => '#17A2B8',
    ],
    [
        'menu'      => 'user.settingMenu',
        'name'      => 'invisible',
        'label'     => 'user::phrase.invisible_mode',
        'ordering'  => 11,
        'to'        => '/settings/invisibleMode',
        'icon'      => 'eye-alt-blocked',
        'iconColor' => '#17A2B8',
    ],
    [
        'menu'      => 'user.settingMenu',
        'name'      => 'sharing',
        'label'     => 'user::phrase.sharing_items',
        'ordering'  => 15,
        'to'        => '/settings/sharingItemsPrivacy',
        'icon'      => 'text-file-lock',
        'iconColor' => '#17A2B8',
    ],
    [
        'menu'      => 'user.settingMenu',
        'name'      => 'blocked',
        'label'     => 'user::phrase.blocked_users',
        'ordering'  => 16,
        'to'        => '/settings/blockedUsers',
        'icon'      => 'businessman-del',
        'iconColor' => '#17A2B8',
    ],
    [
        'menu'     => 'user.settingMenu',
        'name'     => 'profile_menu_settings',
        'label'    => 'user::phrase.profile_menu_settings_uppercase_label',
        'ordering' => 21,
        'as'       => 'section',
    ],
    [
        'menu'      => 'user.settingMenu',
        'name'      => 'profile_menu',
        'label'     => 'user::phrase.menu',
        'ordering'  => 22,
        'to'        => '/settings/profileMenu',
        'icon'      => 'user3-text-o',
        'iconColor' => '#4A80C1',
    ],
    [
        'showWhen' => [],
        'menu'     => 'user.settingMenu',
        'name'     => 'appearance',
        'label'    => 'core::web.appearance_upper',
        'ordering' => 23,
        'as'       => 'section',
    ],
    [
        'showWhen'  => [],
        'menu'      => 'user.settingMenu',
        'name'      => 'dark_mode',
        'label'     => 'core::phrase.dark_mode',
        'ordering'  => 24,
        'to'        => '/settings/profileMenu',
        'icon'      => 'contrast',
        'iconColor' => '#2C2C2C',
        'as'        => 'darkMode',
    ],
];
