<?php

/* this is auto generated file */
return [
    [
        'driver'     => 'MetaFox\\Profile\\Http\\Resources\\v1\\Field\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'profile.field',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Http\\Resources\\v1\\Profile\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'profile.profile',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Http\\Resources\\v1\\Profile\\Admin\\StructureDataGrid',
        'type'       => 'data-grid',
        'name'       => 'profile.profile.structure',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'Data Grid Settings',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Http\\Resources\\v1\\Section\\Admin\\DataGrid',
        'type'       => 'data-grid',
        'name'       => 'profile.section',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'Data Grid Settings',
    ],
    [
        'driver'      => 'MetaFox\\Profile\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'        => 'form-settings',
        'name'        => 'profile',
        'version'     => 'v1',
        'resolution'  => 'admin',
        'title'       => 'core::phrase.settings',
        'url'         => '/profile/setting',
        'description' => 'profile::phrase.edit_profile_setting_desc',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Models\\Profile',
        'type'       => 'entity',
        'name'       => 'user_custom_profile',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'User Custom Profile',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Models\\Option',
        'type'       => 'entity',
        'name'       => 'user_custom_option',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'User Custom Options',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Models\\Value',
        'type'       => 'entity',
        'name'       => 'user_custom_value',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'User Custom Value',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Models\\Field',
        'type'       => 'entity',
        'name'       => 'user_custom_field',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'User Custom Fields',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Models\\OptionData',
        'type'       => 'entity',
        'name'       => 'user_custom_option_data',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'User Custom Option Data',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Http\\Resources\\v1\\Field\\Validation\\RegexField',
        'type'       => 'custom-field-validator',
        'name'       => 'validation.regex',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'Validation Regex',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Http\\Resources\\v1\\Field\\Admin\\DuplicateFieldForm',
        'type'       => 'form',
        'name'       => 'profile.field.duplicate',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'Duplicate Custom Fields',
        'type_label' => 'Form',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Http\\Resources\\v1\\Field\\Validation\\UrlField',
        'type'       => 'custom-field-validator',
        'name'       => 'validation.url',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'Validation Url',
    ],
    [
        'driver'     => 'MetaFox\\Profile\\Http\\Resources\\v1\\Field\\Admin\\BasicInfoDataGrid',
        'type'       => 'data-grid',
        'name'       => 'profile.field_basic_info',
        'version'    => 'v1',
        'resolution' => 'admin',
    ],
];
