<?php

/* this is auto generated file */
return [
    [
        'behavior' => 'close',
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'close',
        'label'    => 'chatplus::phrase.close',
        'ordering' => 0,
        'value'    => 'chatplus/closePanel',
        'icon'     => 'ico-close',
    ],
    [
        'showWhen' => ['truthy', 'perms.search-msg'],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'toggle',
        'label'    => 'chatplus::phrase.toggle_search',
        'ordering' => 0,
        'value'    => 'chatplus/room/toggleSearching',
        'icon'     => 'ico-search-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'perms.start-call'],
            ['truthy', 'settings.Metafox_Enable_Voice_Call'],
            ['falsy', 'room.archived'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'startCall',
        'label'    => 'chatplus::phrase.start_call',
        'ordering' => 0,
        'value'    => 'chatplus/room/startVoiceCall',
        'icon'     => 'ico-phone-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'settings.Metafox_Enable_Video_Chat'],
            ['truthy', 'perms.start-video-chat'],
            ['falsy', 'room.archived'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'videoCall',
        'label'    => 'chatplus::phrase.video_chat',
        'ordering' => 0,
        'value'    => 'chatplus/room/startVideoChat',
        'icon'     => 'ico-video',
    ],
    [
        'showWhen' => ['truthy', 'subscription.alert'],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'markAsRead',
        'label'    => 'chatplus::phrase.mark_as_read',
        'ordering' => 0,
        'value'    => 'chatplus/room/markAsRead',
        'icon'     => 'ico-envelope-opened-o',
    ],
    [
        'showWhen' => ['falsy', 'subscription.alert'],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'markAsUnRead',
        'label'    => 'chatplus::phrase.mark_unread',
        'ordering' => 0,
        'value'    => 'chatplus/room/markAsUnread',
        'icon'     => 'ico-envelope-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'perms.leave-room'],
            ['neq', 'room.t', 'd'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'leave',
        'label'    => 'chatplus::phrase.leave_room',
        'ordering' => 0,
        'value'    => 'chatplus/room/leaveRoom',
        'icon'     => 'ico-signout',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'perms.create-p'],
            ['neq', 'room.t', 'd'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'createGroup',
        'label'    => 'chatplus::phrase.create_group',
        'ordering' => 0,
        'value'    => 'chatplus/room/createChatRoomFromDirectMessage',
        'icon'     => 'ico-user2-plus-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'starred'],
            ['truthy', 'settings.Message_AllowStarring'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'unstarMessage',
        'label'    => 'chatplus::phrase.undo_starred_messages',
        'ordering' => 0,
        'value'    => 'chatplus/room/starredMessages',
        'icon'     => 'ico-star-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'starred'],
            ['truthy', 'settings.Message_AllowStarring'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'starMessage',
        'label'    => 'chatplus::phrase.starred_messages',
        'ordering' => 0,
        'value'    => 'chatplus/room/starredMessages',
        'icon'     => 'ico-star-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'pinned'],
            ['truthy', 'settings.Message_AllowPinning'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'pinnedMessages',
        'label'    => 'chatplus::phrase.pinned_messages',
        'ordering' => 0,
        'value'    => 'chatplus/room/pinnedMessages',
        'icon'     => 'ico-magic',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'pinned'],
            ['truthy', 'settings.Message_AllowPinning'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'undoPinMessages',
        'label'    => 'chatplus::phrase.undo_pinned_messages',
        'ordering' => 0,
        'value'    => 'chatplus/room/pinnedMessages',
        'icon'     => 'ico-magic',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'perms.add-members'],
            ['falsy', 'room.archived'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'addMembers',
        'label'    => 'chatplus::phrase.add_members',
        'ordering' => 0,
        'value'    => 'chatplus/room/addNewMembers',
        'icon'     => 'ico-user3-plus-o',
    ],
    [
        'showWhen' => ['truthy', 'perms.show-members'],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'members',
        'label'    => 'chatplus::phrase.members',
        'ordering' => 0,
        'value'    => 'chatplus/room/presentMembers',
        'icon'     => 'ico-user2-three-o',
    ],
    [
        'showWhen' => ['truthy', 'perms.hide-room'],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'hideRoom',
        'label'    => 'chatplus::phrase.hide_room',
        'ordering' => 0,
        'value'    => 'chatplus/room/hideRoom',
        'icon'     => 'ico-eye-off-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'settings.Favorite_Rooms'],
            ['truthy', 'subscription.f'],
            ['falsy', 'room.archived'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'unFavourite',
        'label'    => 'chatplus::phrase.unfavorite',
        'ordering' => 0,
        'value'    => 'chatplus/room/unfavoriteRoom',
        'icon'     => 'ico-heart',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'settings.Favorite_Rooms'],
            ['falsy', 'subscription.f'],
            ['falsy', 'room.archived'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'favourite',
        'label'    => 'chatplus::phrase.favorite',
        'ordering' => 0,
        'value'    => 'chatplus/room/favoriteRoom',
        'icon'     => 'ico-heart-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'perms.unarchive-room'],
            ['truthy', 'room.archived'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'unarchive',
        'label'    => 'chatplus::phrase.unarchive',
        'ordering' => 0,
        'value'    => 'chatplus/room/unarchiveRoom',
        'icon'     => 'ico-inbox',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'perms.archive-room'],
            ['falsy', 'room.archived'],
            ['neq', 'room.t', 'd'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'archive',
        'label'    => 'chatplus::phrase.archive',
        'ordering' => 0,
        'value'    => 'chatplus/room/archiveRoom',
        'icon'     => 'ico-inbox-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'perms.edit-room'],
            ['neq', 'room.t', 'd'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'editInfo',
        'label'    => 'chatplus::phrase.edit_info',
        'ordering' => 0,
        'value'    => 'chatplus/room/editSettings',
        'icon'     => 'ico-info-circle-alt-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'perms.edit-room'],
            ['neq', 'room.t', 'd'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'showInfo',
        'label'    => 'chatplus::phrase.info',
        'ordering' => 0,
        'value'    => 'chatplus/room/presentSettings',
        'icon'     => 'ico-info-circle-alt-o',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'perms.edit-notification'],
            ['falsy', 'room.archived'],
        ],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'editNotification',
        'label'    => 'chatplus::phrase.edit_notification',
        'ordering' => 0,
        'value'    => 'chatplus/room/editNotificationSettings',
        'icon'     => 'ico-bell-o',
    ],
    [
        'showWhen' => ['truthy', 'perms.delete-room'],
        'menu'     => 'chatplus.room.panelMenu',
        'name'     => 'delete',
        'label'    => 'chatplus::phrase.delete',
        'ordering' => 0,
        'value'    => 'chatplus/room/deleteRoom',
        'icon'     => 'ico-trash-o',
    ],
    [
        'preventDefault' => true,
        'behavior'       => 'more',
        'menu'           => 'chatplus.room.panelMenu',
        'name'           => 'more',
        'label'          => 'chatplus::phrase.more',
        'ordering'       => 0,
        'icon'           => 'ico-dottedmore-vertical-o',
    ],
    [
        'placement' => 'bottom',
        'content'   => [
            'component' => 'messages.ui.MessagesPopper',
        ],
        'menu'     => 'core.headerSubMenu',
        'name'     => 'new_chat_message',
        'label'    => 'chatplus::phrase.messages',
        'ordering' => 3,
        'as'       => 'popover',
        'icon'     => 'ico-comments-o',
        'to'       => '/messages',
        'showWhen' => [
            'and',
            ['truthy', 'setting.chatplus.server'],
            ['neq', 'params.appName', 'chatplus'],
        ],
    ],
    [
        'menu'                 => 'core.primaryMenu',
        'name'                 => 'chatplus',
        'label'                => 'chatplus::phrase.messages',
        'ordering'             => 4,
        'icon'                 => 'ico-comments',
        'to'                   => '/messages',
        'exclude_from_sitemap' => 1,
        'showWhen'             => [
            'and',
            ['truthy', 'setting.chatplus.server'],
        ],
    ],
];
