<?php

/* this is auto generated file */
return [
    [
        'subInfo'  => 'marketplace::phrase.browse_listings_you_like_to_buy',
        'menu'     => 'core.dropdownMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.marketplace',
        'ordering' => 15,
        'icon'     => 'ico-shopbasket',
        'to'       => '/marketplace',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.marketplace.marketplace.create'],
        ],
        'menu'     => 'core.quickCreateMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.marketplace',
        'ordering' => 14,
        'icon'     => 'ico-shopbasket',
        'to'       => '/marketplace/add',
    ],
    [
        'subInfo'  => 'marketplace::phrase.browse_listings_you_like_to_buy',
        'menu'     => 'core.primaryMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.marketplace',
        'ordering' => 15,
        'icon'     => 'ico-shopbasket',
        'to'       => '/marketplace',
    ],
    [
        'tab'      => 'marketplace',
        'showWhen' => [
            'or',
            ['eq', 'item.reg_method', '0'],
            ['truthy', 'item.is_member'],
        ],
        'menu'     => 'group.group.profileMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.marketplace',
        'ordering' => 8,
        'to'       => '/listing',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.marketplace.marketplace.view'],
        ],
        'menu'     => 'group.searchWebCategoryMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.marketplace_global_search_label',
        'ordering' => 4,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'edit',
        'label'    => 'marketplace::phrase.edit',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'marketplace::phrase.sponsor_in_feed',
        'ordering' => 2,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'marketplace::phrase.sponsor_in_feed',
        'ordering' => 2,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'marketplace::phrase.un_sponsor_in_feed',
        'ordering' => 2,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'sponsor',
        'label'    => 'marketplace::phrase.sponsor_this_item',
        'ordering' => 3,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'marketplace::phrase.sponsor_this_item',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'marketplace::phrase.unsponsor_this_item',
        'ordering' => 3,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen'   => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'       => 'marketplace.marketplace.detailActionMenu',
        'name'       => 'feature',
        'label'      => 'core::phrase.feature',
        'ordering'   => 6,
        'value'      => 'featureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'       => 'marketplace.marketplace.detailActionMenu',
        'name'       => 'unfeature',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 7,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'       => 'marketplace.marketplace.detailActionMenu',
        'name'       => 'approve',
        'label'      => 'marketplace::phrase.approve',
        'ordering'   => 8,
        'value'      => 'approveItem',
        'icon'       => 'ico-check-circle-o',
        'is_active'  => 0,
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_invite'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'manage_invite',
        'label'    => 'marketplace::phrase.manage_invites',
        'ordering' => 9,
        'value'    => 'marketplace/viewInvitedPeople',
        'icon'     => 'ico-user-man-three-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_reopen'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'reopen',
        'label'    => 'marketplace::phrase.reopen',
        'ordering' => 10,
        'value'    => 'marketplace/reopenItem',
        'icon'     => 'ico-folder-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.has_sold_invoice'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'soldInvoice',
        'label'    => 'marketplace::phrase.sold_invoices',
        'ordering' => 10,
        'icon'     => 'ico-merge-file-o',
        'value'    => 'marketplace/soldInvoice',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'marketplace.marketplace.detailActionMenu',
        'name'      => 'delete',
        'label'     => 'marketplace::phrase.delete',
        'ordering'  => 20,
        'value'     => 'deleteItemDetail',
        'icon'      => 'ico-trash-o',
    ],
    [
        'tab'      => 'marketplace',
        'showWhen' => [
            'and',
            ['truthy', 'acl.marketplace.marketplace.create'],
            ['truthy', 'item.profile_settings.marketplace_share_marketplace_listings'],
            ['falsy', 'item.is_muted'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'marketplace.marketplace.headerItemActionOnGroupProfileMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.add_new_listing',
        'ordering' => 1,
        'to'       => '/marketplace/add?owner_id=:id',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_edit'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'edit',
        'label'    => 'marketplace::phrase.edit',
        'ordering' => 1,
        'value'    => 'editItem',
        'icon'     => 'ico-pencilline-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor_in_feed'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'sponsor_in_feed',
        'label'    => 'marketplace::phrase.sponsor_in_feed',
        'ordering' => 2,
        'value'    => 'sponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor_in_feed'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'purchase_sponsor_in_feed',
        'label'    => 'marketplace::phrase.sponsor_in_feed',
        'ordering' => 2,
        'value'    => 'advertise/purchaseSponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor_in_feed'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'remove_sponsor_in_feed',
        'label'    => 'marketplace::phrase.un_sponsor_in_feed',
        'ordering' => 2,
        'value'    => 'unsponsorItemInFeed',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_sponsor'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'sponsor',
        'label'    => 'marketplace::phrase.sponsor_this_item',
        'ordering' => 3,
        'value'    => 'sponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_sponsor'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'purchase_sponsor',
        'label'    => 'marketplace::phrase.sponsor_this_item',
        'ordering' => 3,
        'value'    => 'advertise/purchaseSponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unsponsor'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'remove_sponsor',
        'label'    => 'marketplace::phrase.unsponsor_this_item',
        'ordering' => 3,
        'value'    => 'unsponsorItem',
        'icon'     => 'ico-sponsor',
    ],
    [
        'showWhen'   => [
            'and',
            ['falsy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'       => 'marketplace.marketplace.itemActionMenu',
        'name'       => 'feature',
        'label'      => 'core::phrase.feature',
        'ordering'   => 6,
        'value'      => 'featureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen'   => [
            'and',
            ['truthy', 'item.is_featured'],
            ['truthy', 'item.extra.can_feature'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'       => 'marketplace.marketplace.itemActionMenu',
        'name'       => 'unfeature',
        'label'      => 'core::phrase.un_feature',
        'ordering'   => 7,
        'value'      => 'unfeatureItem',
        'icon'       => 'ico-diamond',
        'is_deleted' => 1,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.is_pending'],
            ['truthy', 'item.extra.can_approve'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'approve',
        'label'    => 'marketplace::phrase.approve',
        'ordering' => 8,
        'value'    => 'approveItem',
        'icon'     => 'ico-check-circle-o',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_reopen'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'reopen',
        'label'    => 'marketplace::phrase.reopen',
        'ordering' => 9,
        'value'    => 'marketplace/reopenItem',
        'icon'     => 'ico-folder-o',
    ],
    [
        'showWhen'  => [
            'and',
            ['truthy', 'item.extra.can_delete'],
        ],
        'className' => 'itemDelete',
        'style'     => 'danger',
        'menu'      => 'marketplace.marketplace.itemActionMenu',
        'name'      => 'delete',
        'label'     => 'marketplace::phrase.delete',
        'ordering'  => 20,
        'value'     => 'deleteItemDetail',
        'icon'      => 'ico-trash-o',
    ],
    [
        'tab'      => 'landing',
        'menu'     => 'marketplace.sidebarMenu',
        'name'     => 'landing',
        'label'    => 'marketplace::phrase.home',
        'ordering' => 1,
        'icon'     => 'ico-shopbasket',
        'to'       => '/marketplace',
    ],
    [
        'tab'      => 'all',
        'menu'     => 'marketplace.sidebarMenu',
        'name'     => 'all',
        'label'    => 'marketplace::phrase.all_listings',
        'ordering' => 2,
        'icon'     => 'ico-hashtag',
        'to'       => '/marketplace/all',
    ],
    [
        'tab'      => 'my',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'marketplace.sidebarMenu',
        'name'     => 'my',
        'label'    => 'marketplace::phrase.my_listings',
        'ordering' => 3,
        'icon'     => 'ico-user-man-o',
        'to'       => '/marketplace/my',
    ],
    [
        'tab'      => 'my_pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['neq', 'session.user.role.id', 1],
        ],
        'menu'     => 'marketplace.sidebarMenu',
        'name'     => 'my_pending',
        'label'    => 'marketplace::phrase.my_pending_listings',
        'ordering' => 4,
        'icon'     => 'ico-user1-clock-o',
        'to'       => '/marketplace/my-pending',
    ],
    [
        'tab'      => 'friend',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'marketplace.sidebarMenu',
        'name'     => 'friends',
        'label'    => 'marketplace::phrase.friends_listings',
        'ordering' => 5,
        'icon'     => 'ico-user1-two-o',
        'to'       => '/marketplace/friend',
    ],
    [
        'tab'      => 'invite',
        'menu'     => 'marketplace.sidebarMenu',
        'name'     => 'invite',
        'label'    => 'marketplace::phrase.listing_invites',
        'ordering' => 6,
        'icon'     => 'ico-price-tag-o',
        'to'       => '/marketplace/invite',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
    ],
    [
        'tab'      => 'history',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'marketplace.sidebarMenu',
        'name'     => 'history',
        'label'    => 'marketplace::phrase.history',
        'ordering' => 7,
        'icon'     => 'ico-calendar-o',
        'to'       => '/marketplace/history',
    ],
    [
        'tab'      => 'expire',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            [
                'or',
                ['truthy', 'acl.marketplace.marketplace.moderate'],
                ['truthy', 'acl.marketplace.marketplace.view_expired'],
            ],
        ],
        'menu'     => 'marketplace.sidebarMenu',
        'name'     => 'expire',
        'label'    => 'marketplace::phrase.expired',
        'ordering' => 8,
        'icon'     => 'ico-sandclock-exprired-o',
        'to'       => '/marketplace/expire',
    ],
    [
        'tab'      => 'pending',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.marketplace.marketplace.approve'],
        ],
        'menu'     => 'marketplace.sidebarMenu',
        'name'     => 'pending',
        'label'    => 'marketplace::phrase.pending_listings',
        'ordering' => 9,
        'icon'     => 'ico-clock-o',
        'to'       => '/marketplace/pending',
    ],
    [
        'tab'      => 'bought_invoice',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'marketplace.sidebarMenu',
        'name'     => 'bought_invoice',
        'label'    => 'marketplace::phrase.bought_invoices',
        'ordering' => 10,
        'icon'     => 'ico-merge-file-o',
        'to'       => '/marketplace/invoice-bought',
    ],
    [
        'tab'      => 'sold_invoice',
        'showWhen' => [
            'and',
            ['truthy', 'session.loggedIn'],
        ],
        'menu'     => 'marketplace.sidebarMenu',
        'name'     => 'sold_invoice',
        'label'    => 'marketplace::phrase.sold_invoices',
        'ordering' => 10,
        'icon'     => 'ico-merge-file-o',
        'to'       => '/marketplace/invoice-sold',
    ],
    [
        'buttonProps' => [
            'fullWidth' => true,
            'color'     => 'primary',
            'variant'   => 'contained',
        ],
        'showWhen'    => [
            'and',
            ['truthy', 'session.loggedIn'],
            ['truthy', 'acl.marketplace.marketplace.create'],
        ],
        'menu'        => 'marketplace.sidebarMenu',
        'name'        => 'add',
        'label'       => 'marketplace::phrase.add_listing',
        'ordering'    => 11,
        'as'          => 'sidebarButton',
        'icon'        => 'ico-plus',
        'to'          => '/marketplace/add',
    ],
    [
        'tab'      => 'marketplace',
        'showWhen' => [],
        'menu'     => 'page.page.profileMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.marketplace',
        'ordering' => 8,
        'to'       => '/listing',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.marketplace.marketplace.view'],
        ],
        'menu'     => 'search.webCategoryMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.marketplace_global_search_label',
        'ordering' => 7,
        'to'       => '/search/marketplace',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.marketplace.marketplace.view'],
        ],
        'menu'     => 'search.webCategoryOrderingMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.marketplace_global_search_label',
        'ordering' => 6,
    ],
    [
        'tab'      => 'marketplace',
        'showWhen' => [
            'and',
            ['truthy', 'acl.marketplace.marketplace.view'],
            ['truthy', 'item.profile_settings.profile_view_profile'],
            ['truthy', 'item.profile_menu_settings.marketplace'],
        ],
        'menu'     => 'user.user.profileMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.marketplace',
        'ordering' => 8,
        'to'       => '/listing',
    ],
    [
        'tab'      => 'marketplace',
        'showWhen' => [
            'and',
            ['truthy', 'acl.marketplace.marketplace.create'],
            ['truthy', 'item.profile_settings.marketplace_share_marketplace_listings'],
            ['falsy', 'item.is_pending'],
        ],
        'menu'     => 'marketplace.marketplace.headerItemActionOnPageProfileMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.add_new_listing',
        'ordering' => 1,
        'to'       => '/marketplace/add?owner_id=:id',
    ],
    [
        'tab'      => 'marketplace',
        'showWhen' => [
            'and',
            ['truthy', 'acl.marketplace.marketplace.create'],
            ['truthy', 'item.is_owner'],
        ],
        'menu'     => 'marketplace.marketplace.headerItemActionOnUserProfileMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.add_new_listing',
        'ordering' => 1,
        'to'       => '/marketplace/add?owner_id=:id',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_invite'],
        ],
        'menu'     => 'marketplace.marketplace.itemInviteMenu',
        'name'     => 'invite_people',
        'label'    => 'core::web.invite_friends',
        'ordering' => 1,
        'value'    => 'marketplace/invitePeopleToCome',
        'icon'     => 'ico-user-man-plus',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.marketplace.marketplace.view'],
        ],
        'menu'     => 'search.webHashtagCategoryMenu',
        'name'     => 'marketplace',
        'label'    => 'marketplace::phrase.marketplace_global_search_label',
        'ordering' => 6,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_repayment'],
            ['falsy', 'item.extra.can_change'],
        ],
        'menu'     => 'marketplace.marketplace_invoice.itemActionMenu',
        'name'     => 'repayment',
        'label'    => 'marketplace::phrase.repayment',
        'ordering' => 1,
        'value'    => 'marketplace/getRepaymentForm',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_repayment'],
            ['truthy', 'item.extra.can_change'],
        ],
        'menu'     => 'marketplace.marketplace_invoice.itemActionMenu',
        'name'     => 'change',
        'label'    => 'marketplace::phrase.change_invoice',
        'ordering' => 2,
        'value'    => 'marketplace/changeItem',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_feature_free'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'feature_free',
        'label'    => 'core::phrase.feature',
        'ordering' => 9,
        'value'    => 'featureFreeItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 9,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_purchase_feature'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'purchase_feature',
        'label'    => 'core::phrase.purchase_feature',
        'ordering' => 9,
        'value'    => 'purchaseFeatureItem',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
        ],
        'menu'     => 'marketplace.marketplace.detailActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'item.extra.can_unfeature'],
        ],
        'menu'     => 'marketplace.marketplace.itemActionMenu',
        'name'     => 'remove_feature_new',
        'label'    => 'core::phrase.un_feature',
        'ordering' => 10,
        'value'    => 'unfeatureItemNew',
        'icon'     => 'ico-diamond',
    ],
];
