<?php

/* this is auto generated file */
return [
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'dashboard',
        'label'    => 'core::phrase.dashboard',
        'ordering' => 1,
        'icon'     => 'ico-bar-chart-2',
        'to'       => '/',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'apps',
        'label'    => 'core::phrase.apps',
        'ordering' => 2,
        'as'       => 'subMenu',
        'icon'     => 'ico-box',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'app-settings',
        'label'    => 'core::phrase.app_settings',
        'ordering' => 3,
        'as'       => 'subMenu',
        'icon'     => 'ico-controlboard-h',
        'order_by' => 'label',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'localization',
        'label'    => 'core::phrase.localization',
        'ordering' => 4,
        'as'       => 'subMenu',
        'icon'     => 'ico-globe',
        'to'       => '/',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'appearance',
        'label'    => 'core::phrase.appearance',
        'ordering' => 5,
        'as'       => 'subMenu',
        'icon'     => 'ico-paint-brush',
        'to'       => '/',
        'order_by' => 'label',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'members',
        'label'    => 'core::phrase.members',
        'ordering' => 6,
        'as'       => 'subMenu',
        'icon'     => 'ico-user-circle-o',
        'to'       => '/',
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'settings',
        'label'    => 'core::phrase.settings',
        'ordering' => 7,
        'as'       => 'subMenu',
        'icon'     => 'ico-gear',
        'to'       => '/core/setting',
        'order_by' => 'label',
    ],
    [
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'maintenance',
        'label'    => 'core::phrase.maintenance',
        'ordering' => 8,
        'as'       => 'subMenu',
        'icon'     => 'ico-power',
        'to'       => '/',
        'order_by' => 'label',
    ],
    [
        'showWhen' => [
            'and',
            ['falsy', 'isMobile'],
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'core.adminSidebarMenu',
        'name'     => 'toggleEditor',
        'label'    => 'core::phrase.toggle_editor',
        'ordering' => 9,
        'value'    => '@layout/toggleEditor',
        'icon'     => 'ico-color-palette',
    ],
    [
        'showWhen'    => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'settings',
        'name'        => 'generalSettings',
        'label'       => 'core::phrase.site_settings',
        'ordering'    => 1,
        'to'          => '/core/setting',
    ],
    [
        'showWhen'    => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'settings',
        'name'        => 'licenseKey',
        'label'       => 'core::phrase.license_key',
        'ordering'    => 3,
        'to'          => '/core/setting/license-key',
    ],
    [
        'showWhen'    => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'toggleSite',
        'label'       => 'core::phrase.toggle_site',
        'ordering'    => 4,
        'to'          => '/core/setting/site-mode',
    ],
    [
        'showWhen'    => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'settings',
        'name'        => 'attachment',
        'label'       => 'core::phrase.attachments',
        'ordering'    => 6,
        'to'          => '/core/setting/attachment',
        'is_deleted'  => 1,
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'members',
        'name'        => 'browse',
        'label'       => 'core::phrase.browse',
        'ordering'    => 0,
        'to'          => '/user/user/browse',
    ],
    [
        'showWhen'    => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'overview',
        'label'       => 'core::phrase.system_overview',
        'ordering'    => 1,
        'to'          => '/core/overview/system',
    ],
    [
        'showWhen'    => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'phpinfo',
        'label'       => 'core::phrase.phpinfo',
        'ordering'    => 2,
        'to'          => '/core/overview/phpinfo',
    ],
    [
        'showWhen'    => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'change_files',
        'label'       => 'core::phrase.change_files',
        'ordering'    => 3,
        'to'          => '/core/overview/change-files',
    ],
    [
        'showWhen'    => ['eq', 'setting.app.env', 'local'],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'routes',
        'label'       => 'core::phrase.routes',
        'ordering'    => 10,
        'to'          => '/core/maintain/browse/route',
    ],
    [
        'showWhen'    => ['eq', 'setting.app.env', 'local'],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'events',
        'label'       => 'core::phrase.events',
        'ordering'    => 11,
        'to'          => '/core/maintain/browse/event',
    ],
    [
        'showWhen'    => ['eq', 'setting.app.env', 'local'],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'maintenance',
        'name'        => 'drivers',
        'label'       => 'core::phrase.drivers',
        'ordering'    => 11,
        'to'          => '/core/maintain/browse/driver',
    ],
    [
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'appearance',
        'name'        => 'block',
        'label'       => 'core::phrase.blocks',
        'ordering'    => 0,
        'to'          => '/',
        'is_active'   => 0,
    ],
    [
        'showWhen' => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'     => 'core.bundle_task.admin',
        'name'     => 'bundle',
        'label'    => 'core::phrase.rebuild_site',
        'ordering' => 1,
        'icon'     => 'ico-bar-chart-2',
        'to'       => '/layout/build/create',
    ],
    [
        'showWhen'    => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'parent_name' => 'settings',
        'name'        => 'provider_keys_config',
        'label'       => 'core::phrase.service_keys',
        'ordering'    => 0,
        'to'          => '/core/setting/provider',
    ],
    [
        'showWhen'    => [
            'and',
            ['truthy', 'acl.core.admincp.has_system_access'],
        ],
        'menu'        => 'core.adminSidebarMenu',
        'name'        => 'site_statistic',
        'parent_name' => 'maintenance',
        'label'       => 'core::phrase.site_statistics',
        'to'          => 'core/statistic/browse/type',
        'ordering'    => 5,
    ],
    [
        'menu'     => 'core.admin',
        'name'     => 'site_settings',
        'label'    => 'core::phrase.site_settings',
        'ordering' => 1,
        'to'       => '/core/setting',
    ],
    [
        'menu'     => 'core.admin',
        'name'     => 'security_settings',
        'label'    => 'core::phrase.security',
        'ordering' => 2,
        'to'       => '/core/setting/security',
    ],
];
