<?php

/* this is auto generated file */
return [

    [
        'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Admin\\FacebookSettingForm',
        'type'       => 'form-settings',
        'name'       => 'socialite.facebook',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'socialite::facebook.site_settings',
        'url'        => '/socialite/setting/facebook',
    ],
    [
        'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Admin\\GoogleSettingForm',
        'type'       => 'form-settings',
        'name'       => 'socialite.google',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'socialite::google.site_settings',
        'url'        => '/socialite/setting/google',
    ],
    // [
    //     'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Admin\\TwitterSettingForm',
    //     'type'       => 'form-settings',
    //     'name'       => 'socialite.twitter',
    //     'version'    => 'v1',
    //     'resolution' => 'admin',
    //     'title'      => 'socialite::twitter.site_settings',
    //     'url'        => '/socialite/setting/twitter',
    // ],
    [
        'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Admin\\AppleSettingForm',
        'type'       => 'form-settings',
        'name'       => 'socialite.apple',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'socialite::apple.site_settings',
        'url'        => '/socialite/setting/apple',
    ],
    [
        'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Admin\\TiktokSettingForm',
        'type'       => 'form-settings',
        'name'       => 'socialite.tiktok',
        'version'    => 'v1',
        'resolution' => 'admin',
        'title'      => 'socialite::tiktok.site_settings',
        'url'        => '/socialite/setting/tiktok',
    ],
    [
        'driver'  => 'MetaFox\\Socialite\\Http\\Resources\\v1\\PackageSetting',
        'type'    => 'package-setting',
        'name'    => 'socialite',
        'version' => 'v1',
    ],
    [
        'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Auth\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'socialite_auth',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Auth\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'socialite_auth',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Invite\\VerifyInviteForm',
        'type'       => 'form',
        'name'       => 'socialite_invite.verify_invite',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Invite\\VerifyInviteMobileForm',
        'type'       => 'form',
        'name'       => 'socialite_invite.verify_invite',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Invite\\WebSetting',
        'type'       => 'resource-web',
        'name'       => 'socialite_invite',
        'version'    => 'v1',
        'resolution' => 'web',
    ],
    [
        'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Invite\\MobileSetting',
        'type'       => 'resource-mobile',
        'name'       => 'socialite_invite',
        'version'    => 'v1',
        'resolution' => 'mobile',
    ],
    [
        'driver'     => 'MetaFox\\Socialite\\Http\\Resources\\v1\\Admin\\SiteSettingForm',
        'type'       => 'form-settings',
        'name'       => 'socialite',
        'version'    => 'v1',
        'resolution' => 'admin',
        'is_active'  => true,
        'is_preload' => false,
        'title'      => 'core::phrase.settings',
        'url'        => '/socialite/setting',
    ],
];
